prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:X+42gsKYwo+eOhhkymcW4E6MGnxP9O1cHCx8WtTt8LPCLkAcip/qUWzj6W8nhwNQUdKNMPniyTbtirywsvqBUg==,iv:1kWw3BgFlA1g6UzxHlv7zNES4Gh8EF8GZHZ04h3/ARo=,tag:Z/Y5HoL5Y2IL8Lg0ugAmJw==,type:str]
    password: ENC[AES256_GCM,data:ih765BtD0CK/7WJODsEFWMHNaRDd50o+IAmvb5Ggt7DqNEyULUEbj9ej3enDyrIVIhkkAyOikdjQ4TdwCwbhXA==,iv:MyDnlVkFH2v78Z1LIcIAWrrkdhLeUhxbtLzJb9MhFzA=,tag:L9Zk0NB7vt5kH/efM0g5rQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:vt3HnmXwhQxlab9zx8H48vDk4Fs=,iv:3raX0fu+J4Ei1//NPSRiQjPCgFL98Fk1hwKvj0MIBHQ=,tag:WSDP6chGwaS2I3u3Eeun0w==,type:str]
      client_secret: ENC[AES256_GCM,data:5GpowujUUDYWgGv5if6XvlH74ZXwM7e1XtqjjnJ+Kt5GqKyw1GBJ6w==,iv:X8ocm70MhCwkm6GNuhp9TMaYYgRFo22y8uyeXpVZzPI=,tag:x2MBucxUEb8uYn6yIMGLUg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:40:59Z'
    enc: CiUA4OM7eP/hz64qx7hOu7y1+RmR5titXpU9OqtnTv4BSFVK5NZ8EkkAZoeZplzAYa9MsSV+KrID7MFRVkjDEPPgQMls0Rsljxr0QMGFzBXuseY1kKwhAg+qvs5hUtifBvAiPMvNow3wXkp+l+3jEba1
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:00Z'
  mac: ENC[AES256_GCM,data:LH/5gtPPGtlzI9FTlgez0kBD+4/+Bzx2a9U3cwG30UeMPf62Y6DOnDfIdRDfsQV8hbdRwKGskX9llfeCxHatfC4pWZQWhOLhC1ZSbsIB2zJBiWbf8d4I2sZBHibkNaDQXeqRaPtbkBk/8eFSECXYFx3xz8hEB0JYtX6gJTMO1Y8=,iv:xUQmR5Jd2WMH9Oc8yVdYxXPDfImC37kEDemuDEsM81A=,tag:Lsq72Z0cHlzlEelCHRJ0TQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
