basehub:
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:RDesaa0Wr6pnfklWU0BtoHaWw9g=,iv:C4bBjlkhdM7Xz87/QrEss6QP5ZRb+wPFArDLJCAZ+Ns=,tag:ivt931zOLG1xTsZ694WzKg==,type:str]
          client_secret: ENC[AES256_GCM,data:1IGyE4+VKCF6IiHHlCv4hhJLQphz2ax5oEUF4QXjSEQtZGzsU0s10Q==,iv://RLs5scN6NOL/XDmQAPkO+cTcDe2FLkWFS+Uj/+TJs=,tag:d0KTBJOdfdAcR+NFxjVUEA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-10-24T10:37:44Z'
    enc: CiUA4OM7eCQWEyht09mKKgbUxNyGoo+QsRZBAI6cVr2XWCEo/dCZEkkAq2nhVakyUtf6neyKXwWWxWPtq6iSLvuhHoswkNlxnuBBVxN1RSFeBEPy8b85Hj0FnSMBy0/tgqEwAbkp7wUz1MYTIbhdzqIo
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2023-10-24T10:37:44Z'
  mac: ENC[AES256_GCM,data:g0NOs7Qli/aUO3ZFwCQcFWr+i9tfDnkiyzU8LIDAoaM4BGAzJcRwnjzUO3MfnRjOk4tOS16V1m2eiH8FIWy6sa8kJxJYEO0cU/kKZk+ojCf0txyYE0ZV+gN7w4mb8ZYGP6f4LPwhjy330dkq7uExFaqqLNzDcduWSMAJeBKy2XI=,iv:cZigjUvK0LCwZIBDL+CzOLObBZaiZqJmH+iRoZxPWlk=,tag:Cu3Qgpb2pJD4C4gsUSTNdg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
