prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:Y9YBU79Th7DZ0hZW8FqfP2BmmTnrliVrwzawOqAQ73F89VR8kfmuRZwZy/39X8DbhTL2WQQuFszZzjkWG1wdtedNYEjF7Ew0HoNDh+Crx2R/YQ+qywP+AczlDWKFr6gTBIrdGHbuxkYY0ArTAZxCyymMSewkhSXJRfAMKLX6oGHUAsTbLi0DwFcQ+z5TxnTeP5O21Af1GBDiXEuZ,iv:tUaaHs1tpvy23Mot7UDvIAyckiEEYUShurGIMThSGzo=,tag:UuBoELhRrFysh2ckflH3Yw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:RyHeHH6Qkmoy6Xs7NIgFAbi463+M+0NWfHvKbqpTu34rlyij+DxA7WdSxSppgREEyTCtYGHac0Em1QdHSVj1hg==,iv:4k8SFw20JIu7gU99GgEFCVg2Ky9TpPenw5BwuUbQzbI=,tag:mAooT1c6DU4BI4v5Ho+4zA==,type:str]
    password: ENC[AES256_GCM,data:yas04nAehmMPpgNXBuF2bevxFULJrlb08DcXQWmdtZjhmrG4rudZx+mWPjG3rBzC3NiHcTXxIvfKCROBoL/E1w==,iv:vvNhYJeviN2Sr0blQiV/N/2l+Enszg2aujhNt7fvsC8=,tag:y33FaHE/4RXNZhKAcx2ogA==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:1GNVqMDzvgl8s24nvNZQcB+Rlxs=,iv:Z9uvg0YlF4uBDw95jJyPYznUwg6aJb37RoomvxwqcHI=,tag:TrMQk2Wxfv4FnHlvBaKv/g==,type:str]
      client_secret: ENC[AES256_GCM,data:1QNixTP5xV31WruOswGIYLLtldAZZYkOm39wWZVW7dqBjuEY02iJdA==,iv:iXUBICVhRJAHp6Sz5YmhZyu4ORlpATghRXAQNqpjMhs=,tag:k8rMzsXPX/4mTFkhkPQ3Kg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:05Z'
    enc: CiUA4OM7eD57oHMfCsjm+Gwvq96yCuZ1cGTcdDlN1fjBp68O+Xx9EkkAZoeZpgoRToPD06a94x9S8ii31wPxceTwSanA/ICb1973UQs26861Zy+7F0J3VTNpCLSQoa/9PPay/d6fFPtoCrQ3TKm4Fbj7
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:06Z'
  mac: ENC[AES256_GCM,data:n4rEiEXCUiDJUHXKOYJUCPgOBpk+wAkTzJHcTC2fEQvNJkzJ7QMI8cHpcbA1UnZvZDufG/jY4kL+ISo4/r4iWMhEQAAmwCu7+0pi1f7sCS3bJwfR/L5C0SQERvi22Gm78hy/soBYdevLqiI2wIlp6tt6TdU323MKrvQwjHoYlfI=,iv:oSRoe1wzp8bAzUQcxKYZzsvd/85hEQNKcp6Kb4gb8+g=,tag:jCkDv87AKeeu/xW5LS0sYA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
