prometheusIngressAuthSecret:
  enabled: true

nginx-ingress:
  enabled: true
  controller:
    ingressClass:
      # Claim the `nginx` ingress class
      create: true

ingress-nginx:
  controller:
    # Turn off this controller
    replicaCount: 0
    # Let go of the `nginx` ingress class
    ingressClassResource:
      enabled: false

trafficEntrypoint:
  targetController: nginx-ingress

grafana:
  grafana.ini:
    server:
      root_url: https://grafana.aws.2i2c.cloud/
    auth.github:
      enabled: true
      allowed_organizations: 2i2c-org
  ingress:
    hosts:
    - grafana.aws.2i2c.cloud
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.aws.2i2c.cloud

prometheus:
  server:
    ingress:
      enabled: true
      hosts:
      - prometheus.aws.2i2c.cloud
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.aws.2i2c.cloud
    persistentVolume:
      size: 500Gi

cluster-autoscaler:
  enabled: true
  autoDiscovery:
    clusterName: 2i2c-aws-us
  awsRegion: us-west-2

redirects:
  rules:
  - from: researchdelight.2i2c.cloud
    to: showcase.2i2c.cloud

calico:
  enabled: true

# FIXME: remove this once eksctl is fixed
nvidiaDevicePlugin:
  aws:
    enabled: true
