nvidiaDevicePlugin:
  gke:
    enabled: true
    version: "latest"

grafana:
  ingress:
    hosts:
      - grafana.m2lines.2i2c.cloud
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.m2lines.2i2c.cloud
  grafana.ini:
    server:
      root_url: https://grafana.m2lines.2i2c.cloud
    auth.github:
      enabled: true
      allow_sign_up: true
      scopes: "user:email,read:org"
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      allowed_organizations: 2i2c-org

prometheusIngressAuthSecret:
  enabled: true

prometheus:
  server:
    ingress:
      enabled: true
      hosts:
        - prometheus.m2lines.2i2c.cloud
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.m2lines.2i2c.cloud
    resources:
      limits:
        cpu: 2
        memory: 12Gi
