prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:JeddUFZLlp67lpC2YhyuV+xaF4Sm3txkWNHtcyiQdD1kTT/0L7zvuGUqbIYj/0ZQ8B9Ej+i6QWvNJAqylzJ67g==,iv:zA538/zmQ1tdQr0sx3o+3C0WADWpb4r/8ZV/s7Z4frg=,tag:TAcbMLs8YY+ec6dIU8FixQ==,type:str]
    password: ENC[AES256_GCM,data:iDOmKYDctg1i1OHsJnsvkh7iKtx8X43H3CmuCQaPWUPHMvr0TtcFhOntzNosxdHRwZ6lHDY5/4bdEr5dgKJoFg==,iv:JncG3yPz4R0hSXof13KccwUfQS6n/YMjn2rbBCYLeeA=,tag:M9/MCP1q0v1QU0j90AAJUA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:14Z'
    enc: CiUA4OM7eG/hj1+7Ta5CSqobjK/16LsSLesGnMmBnkeGD3WqX+SMEkkAZoeZpoMW2Z0R0zEhUfUI36JxdEsl/BuTX5HfcpPf+j80WSgxitl0ICTS+TivNHX0om1CA1O9lEV6ywpPu+T1+FhtL+BvALY3
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:14Z'
  mac: ENC[AES256_GCM,data:kpC3g6fjl2eDPOSme3dqYagzRhYQ86qoOXBHR1zi2ZvATtbLRNSkI3VcTAM6c9ITs0ZmHdmWPQBRPCD62oZg2ZHNaFYs9drHN8fZczmzP9YWcgVgkHTzjdHBJXy0gcAfJ3m3F33IZRe5OhEy2PIJvc9cr0BzHkhh/6W37dZzUAs=,iv:Z/yS2UzDnODN5srShDzkPM4fNIAU41Hmji50isfAoJk=,tag:DoeeCjJnUbGiY1SrxdOF/Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
