prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:wXKw+Ja+AhLBbfK99QHw66W+Z2TGwy67nRlDVbH5tePt8DoX8TXlHdljb/MWiFI8mZRs2rhcpHnX6D+WTloySowWje/1a6TYK5VgUAnM+XMqXxCNjgI/K9UsC66rsJQoSU0Qyx20mF+mmyzFS70ooVOpXAB0y358qv7sx6YT2sYbRXzZS4ooI5P6F8vdpLmDaDOvHWhdZN/qx6bB,iv:nc5hoMbLtNdzw5cseHWlxIpuLpTSRr2DevjH32SubwI=,tag:Ra/RKcvWFYGrSnzSXIRC1w==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:qqdNv3z9WT8LEq+4QTY8vAgxD7kA3FKTOCERGjNCU70WArOC89stce0nL2nsC82xGax9yYL85AS5LhUgWJpWOQ==,iv:05EXVSglD/2yV5uh2mPn/pH2RHUb9zN90+aPnL4SiMY=,tag:r6qrcNGJ20aNxJehDmvL/Q==,type:str]
    password: ENC[AES256_GCM,data:t/ldKEKzCXAsy8fPn/p0m8jtVnMrx3XmJ4U3XeLtbFDzbIPSri3v+GOK4XLoFqm/fdgDdbvE2hCko//tEk0q+Q==,iv:y131tow+6oDAg/LilRwlPTSBLEWWUtI7Oy2gKdCLCzw=,tag:iyig0o1K6Jk6gXy34KmWPA==,type:str]
  - username: ENC[AES256_GCM,data:RsDbW2/3zVxJN4liACW3Na/K1HmfVdKCNnM3h8Ci2bD0VEJB9KN+sH1h+1gLllVj6ZnvlA+cCY26yaQNSDdUqw==,iv:kpBgE7YbOe/h5lrphWH5D/dJ1cR2v3t9skG8pnCrtlI=,tag:vILQIc9YlXZTVv+vvdwG5w==,type:str]
    password: ENC[AES256_GCM,data:7euF2BDNpDbaqOrl4J/HGNqZOwDN/aqwl+Tb7mBPPsDo+jKVT/pSWpBSfcW/7QAlmjfLbs1tDcMeBaL4yd35Fg==,iv:bRZArngXI1HFW2F/WfgcXOPmtkSordnhWk6hc74N0nk=,tag:9tYJVh8SdIjeZYyMNiZvWA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:20Z'
    enc: CiUA4OM7eIYeMhximvFCvbDWN+FxTvDYtPbO3zJdwxSClFKDAhleEkkAZoeZphTXevHf45eiGBjJXG84HqtwSlUv1fFWxnmX8rSmunESeTQtj17pdIPtOG44lKRCLuieGCXyf73V5WhNDB/N/mQC98PT
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:49:45Z'
  mac: ENC[AES256_GCM,data:rXVtGwGdqOYc2xNlHVUyiwXxKPt5zm8r19lbSuOA0IKekPeY7FTskqDkIesv/Aijhm4YdrgnRYw7PbyPu+wdvWLHnY8Pgr7PC25bV1SW1+bc/CA60e67AUwqJY1thiy71oU4xUKWS5LIzY9+lbvGglB6WyOqoftQqWXf9FiOA7E=,iv:pTwy4smyRsUPUoE0eLvuVj8AIy43EUpMBGFNmBQDbpU=,tag:/Bet1vWFp79aMCQ+BjJy4g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
