prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:wXKw+Ja+AhLBbfK99QHw66W+Z2TGwy67nRlDVbH5tePt8DoX8TXlHdljb/MWiFI8mZRs2rhcpHnX6D+WTloySowWje/1a6TYK5VgUAnM+XMqXxCNjgI/K9UsC66rsJQoSU0Qyx20mF+mmyzFS70ooVOpXAB0y358qv7sx6YT2sYbRXzZS4ooI5P6F8vdpLmDaDOvHWhdZN/qx6bB,iv:nc5hoMbLtNdzw5cseHWlxIpuLpTSRr2DevjH32SubwI=,tag:Ra/RKcvWFYGrSnzSXIRC1w==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:qqdNv3z9WT8LEq+4QTY8vAgxD7kA3FKTOCERGjNCU70WArOC89stce0nL2nsC82xGax9yYL85AS5LhUgWJpWOQ==,iv:05EXVSglD/2yV5uh2mPn/pH2RHUb9zN90+aPnL4SiMY=,tag:r6qrcNGJ20aNxJehDmvL/Q==,type:str]
    password: ENC[AES256_GCM,data:t/ldKEKzCXAsy8fPn/p0m8jtVnMrx3XmJ4U3XeLtbFDzbIPSri3v+GOK4XLoFqm/fdgDdbvE2hCko//tEk0q+Q==,iv:y131tow+6oDAg/LilRwlPTSBLEWWUtI7Oy2gKdCLCzw=,tag:iyig0o1K6Jk6gXy34KmWPA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:20Z'
    enc: CiUA4OM7eIYeMhximvFCvbDWN+FxTvDYtPbO3zJdwxSClFKDAhleEkkAZoeZphTXevHf45eiGBjJXG84HqtwSlUv1fFWxnmX8rSmunESeTQtj17pdIPtOG44lKRCLuieGCXyf73V5WhNDB/N/mQC98PT
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:20Z'
  mac: ENC[AES256_GCM,data:iPYteKFJBOqKRanAo8uMsAIjUjr8h8KLNRfSEZrH99onOLqFutDZ4zJ0iiIJLpuSuojQQfsXfkZys04r2+Cz4Q/gNfCzIf98BPBjTiyPf0di0ouetG02n3I9syjemSRJRqu9zCEn5SQxp5HO9BbwccUBsN1gu/1vskbATTN4eTk=,iv:4yLYEBIyjZy/ZqNM0nMAHvhu8lvt9IR2OAUEu3TRz3Q=,tag:qVnbSMWtQgq99Yhb0niJzw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
