name: nasa-esdis
provider: aws
aws:
  key: enc-deployer-credentials.secret.json
  clusterType: eks
  clusterName: nasa-esdis
  region: us-west-2
support:
  helm_chart_values_files:
    - support.values.yaml
    - enc-support.secret.values.yaml
hubs: []
