prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:e3XJwQ1e9TuLS94P1+1vbLMh3fbpqQvQhqQbKJazCHcvLWTagbddKqnHOfPfK48GG+pYgpmniOZKobx8IGkt9A==,iv:urUTF8oM+kpoqGK36W53ONMRR5yIwh/j+kWFYszz5/I=,tag:EghLncjDF7Bz0sxUaOYt2Q==,type:str]
    password: ENC[AES256_GCM,data:CpUB/7TmwXUOzd1mJY37v0lH40shpnMuyj6Oio8AijXR6AiGNfDbQWrSVwodVHEfaupt7Qu3YRawZUuzNqr3tg==,iv:TDdtA1XdLE/QYSzjifQ1ID4gkzW4U0dsMQBBxePwCxw=,tag:eU05MbLrRMDsYWs/DUOaVA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:10Z'
    enc: CiUA4OM7eCjHAVKvz1l0VztIvWYoCbeIMzLwPIM3fmR1/bj9B8vfEkkAZoeZpq3yp/Pf5dbi6GbeOGMPdqpoGl84CWdwso9o3NhF27MbxbqsDlnujsZ+AOxTQ89goFa4zOkSbpfJQq/aQL89x/YJWFr+
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:10Z'
  mac: ENC[AES256_GCM,data:PtY9xwZHik0ywh29fRrMu8/FFolfOTu8gu3dHb5vR51ClBMggUGzp9VCkwqE15pdAHn8Za+B0JE0HfGAS+Lr6WPYzVmKKyXGOHDYAu8luPwvhSaTmAkOLszeZ5rQRsGc7kwkBKMY17Xcitky7sUCgYnVW2gmwlafp8NmLGnJljc=,iv:gQYhPA1WMMDdCu8VUEJnE6WQtQyw+4HZyjizAzAyZ8Y=,tag:YEVsm8IN9o0AWLvNCzAvKA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
