jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:jGqHTThMjWwpr1Nn3ar8bLPzYlcB5ZkHJLBe7fbIpC+Qcm+i0/93eTdLjblTR/DdF9mf7INHN8X3gWoLkk98YRvcCPzvB1eLNQesy8QNMUGTXRJE/GbfF5D/QRsZYEixltXZRMCZgI4j1eyR,iv:EMogVQxIPvQuz+7c2hIGGidm8vcM95kQOPOo4I9a7rc=,tag:rZYwFwjq0bd+R3hGyP9s9w==,type:str]
jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:pY2yCA4YZs4WPV/ErhnK,iv:ro117Cl7l/PnbPtp5l1A+DlIiE/GmGK0o68t+/+oJdA=,tag:ar/R9jt+w8mqn/ZA0BROJw==,type:str]
        client_secret: ENC[AES256_GCM,data:aEJFvmCz8R9Vnb8WZ9igBg==,iv:zi2XcrJFzgOXy4HFYE4Jk9V2fe/YCJoBc6iC2IZ8IRo=,tag:IljEFhZqRN2HFi2pFeLQQA==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:SKjWcoVyc0Cep3e+bcW8cEaRlkk=,iv:+aXSXE9+hw1zW/kF6V/gNSR8YhTmEa7o4eJLYa80RGo=,tag:6ePElT0HaTiCKfpQLo3zDA==,type:str]
        client_secret: ENC[AES256_GCM,data:XlxBcGhMNu8v4topVgUDlBAZd1zPWzlNWNf6g9IcqBRBQc6kzFrv4w==,iv:wf0Gn8sJn4nrJFl3eHhYYdO0C5iQD/5rvCgPfqG2Q20=,tag:Ed6qTXg/veJMUSkLhP65pg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2024-08-28T17:11:51Z'
    enc: CiUA4OM7eE42MAnJnSRbSgcixhYQanLcxwpkon6oodvg2vfsHlPuEkkA5dG1Q+XBCcm6hV3EDD8c3e85Wdjkcv5CgftsEAzTcvFNGuijE6dUcPxi8yRhjELV8cHYPOwXuFUkdlq3L6LekDrzZoda9fjH
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2025-11-26T14:02:11Z'
  mac: ENC[AES256_GCM,data:YGlY2n1crtqDPJ1gC0o1b0VAmddFlBUMfslWB2MeeRinENqnNA4iC2a1m+PsPCfOO5V9Sqq8hlvyJsg3NEkV+oDL2b63L+dnv8gVZ2BvaOubvY9DtjQjxWHVAnCLI/IeZkRyQUROLKrmAuPNj2D3M/ooIOVAF6o4EPmekhgfLDk=,iv:nRgGuvw+WPgiEYCuC70nvwcOVgEZ7nvZveVn0rALfT8=,tag:8GfLVfrxW6d0LIbSBa/pjw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.10.2
