prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:kZ5Vrd66MbkRG8/XoG9MWabfoigbvLWwf0B+4BWm8CdcrLr1Eeaz9wq0NcCeqavHniXdjlNTTPQK10mLS9cQRuOcLDyLRhLmjE/AlCPmHrd59+UMlEhyHWZsvHe1oJmUTrXiIdSyWJ6cslvFlw+ZTifqZZ/PeTRrR8reyHxf+C3vkgSUmasfx1IGeuFFfX9aaCTE2zkVmt/9xEbk,iv:4F78imdKS85obfMB3qdvGK4csNQ2ht/FLbcKGLVL9C4=,tag:eqeuNqYlCbp53fJjXNiOMg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:PvMk7C3Gl37e2zFlnLF01VCrdHKIW1MwRV0DCorq5eQVCzmEqD1TsV1m+W2GpsF/e+LTKY8j8qgQe/HL3KYweg==,iv:NahLkIbukoroL7q7/VscABbQEwv5dwTFZOf3rZ5+IhY=,tag:5SFLD85iFVCPuSL1Wc825Q==,type:str]
    password: ENC[AES256_GCM,data:82kR0UxC7DQdXEEETi728YYdyX/1OSYp3b0P5YQ5/0tQaMRtDWwaPLj6qAl2R3c9ElsCsuBXu9/npaKWQXq9yQ==,iv:z2D9Ed2XB8GCXwzaWF4qP8iilyfjFwObWM/h/mzFjuU=,tag:2rxksgl08IHV2uhelBGf4A==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:16Z'
    enc: CiUA4OM7eHZfF/I43b8iIcQa2NeavkMZpmZnfsKGieTV+4XyCntLEkkAZoeZptAidavzSFcpaes9NGWItt8WMFNncVw7P7vyw4yZWKihAVF1821UzSTa530+i0Z4zFPGVQM5zxeaAXcd5E+/2ioa+j5x
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:16Z'
  mac: ENC[AES256_GCM,data:68aHWtXeBU6qPnw8HozrnAzPqbZVk71hpc6ZcW7hjNCmpz7PmFMRTKtChlWN8cPiv9kDn5IseB5XsC5Xuiqhp6DoR3FTwGyB2xfGNkazD3S130cP2SZtRWct8WEddIeWwsLaXgpKwRz0cbJGeyiZNHlmR8gRYlAmuxF2WLqR+NU=,iv:MDAGgM4mXEdQif3esgDeLx4mVgS0dI8SkcVE2z+JF4k=,tag:Ooguj0v+rLSmB1PA2dELnw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
