jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:JroeQv1wywhRKcmgYAD9Riv+/Pb7ZhlZz2PVGAQfvsV1VfEG3HEECD0ggKVJg69Z/v3c/KFPuhGvE7ifJaHeDSE1YDLgfoHXd/nd6QWzvP1klTBlCQFgSr+vyhNhNSzcea+oxa24aPW1UFZD,iv:/eBkanb2DJ67a2evehXd3ABjI2rorH9vlUPVeOG0GcE=,tag:k3ETnVtaAvBk54ZPsIIPwA==,type:str]
jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:pY2yCA4YZs4WPV/ErhnK,iv:ro117Cl7l/PnbPtp5l1A+DlIiE/GmGK0o68t+/+oJdA=,tag:ar/R9jt+w8mqn/ZA0BROJw==,type:str]
        client_secret: ENC[AES256_GCM,data:aEJFvmCz8R9Vnb8WZ9igBg==,iv:zi2XcrJFzgOXy4HFYE4Jk9V2fe/YCJoBc6iC2IZ8IRo=,tag:IljEFhZqRN2HFi2pFeLQQA==,type:str]
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:SKjWcoVyc0Cep3e+bcW8cEaRlkk=,iv:+aXSXE9+hw1zW/kF6V/gNSR8YhTmEa7o4eJLYa80RGo=,tag:6ePElT0HaTiCKfpQLo3zDA==,type:str]
        client_secret: ENC[AES256_GCM,data:XlxBcGhMNu8v4topVgUDlBAZd1zPWzlNWNf6g9IcqBRBQc6kzFrv4w==,iv:wf0Gn8sJn4nrJFl3eHhYYdO0C5iQD/5rvCgPfqG2Q20=,tag:Ed6qTXg/veJMUSkLhP65pg==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2024-08-28T17:11:51Z"
      enc: CiUA4OM7eE42MAnJnSRbSgcixhYQanLcxwpkon6oodvg2vfsHlPuEkkA5dG1Q+XBCcm6hV3EDD8c3e85Wdjkcv5CgftsEAzTcvFNGuijE6dUcPxi8yRhjELV8cHYPOwXuFUkdlq3L6LekDrzZoda9fjH
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-12-02T00:29:23Z"
  mac: ENC[AES256_GCM,data:mlcEaZqKd3K2eJL+X0aMNn9zhpvT59/7V8iadsDSfjOIlof/czYiCtLmulP3qMTA5IzySU1sbaBFcmzh7G11RMzSHxVtXdhUreWQO8ZfroDmtjOgrPTLOkCVP+/EA6Tll/ZuqhCDyGZf/IgPy0a10HUlC94QE0CwuGfQcHdjSyM=,iv:h5WHDQ5/G3Jf5yAJ9FiSZo288mGVQTee6pkSVisy/ek=,tag:1NmIpo8IwyWMAxaTaC8J8g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.10.2
