prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:HT4J5CKI8p0bHA5877+RfH+PKs7f5ccM/uCUU0hS9i5QKAAFU8Ex+wZN6sQuCXtbjInGAnVDn1F+h8XeZh7DsiRIgI41woIbl3zXZ93InY9GEe3Q7yXQLfwOemr7FHNjTwra40gxPbnuVJXOT6knoQ0hE/oLsNUVQHNkWS6yxVEpg4eW/nUQnKSDNeJpEWypcK5JM2SLPxyDQlnZ,iv:wCtnlZaVKSIz4BUq+dMmAFrG6GRMP646RkP5KTbCldI=,tag:Bu+PY7vosF5YQxOcamERwg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:164Z9T6QXJ88RrDf+fwCIkzmiBSrc5xicMJEUBikFpELV1mpx2A1xTnecUxXlYrJeLbQr7q5pzi0+w9vWanCJQ==,iv:VGuuWzYaGHDkWgbWi1M30kYkIXJ0y8jbU79DepLQLDE=,tag:Zr6cdy4XG9OXwZvAHbHSOA==,type:str]
    password: ENC[AES256_GCM,data:gQMD9zuSjLynTfDQuZ4xi75hrxhxtKRacqtqm7lU/S2XsGn6CkFM03kmUGCZA7VbmErdQXV7c4XgQqLOGJzOSw==,iv:H4Aaj0kPYdrwkaBDlBeMDRvGojY9zH/0tuvScouSYGA=,tag:oVr2fawAzyzHBYV26zr5iA==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:kIX3pVhnztpQI2Dx8tXVAnmd6xM=,iv:tVvj347UHIfC4Oe7DSdfDgMiuCaiDTQCezya+Vn1RdM=,tag:zt4JAc4HZflzg+Qxkkx0iQ==,type:str]
      client_secret: ENC[AES256_GCM,data:ZW1+unvHL61RJYY+snG7SUib1+FBbHVG1QSvclF+XWhMvoIRCNA4vw==,iv:fRI+AfyHsgMhzl8jxyhfxEpWnv1O6T6QjVvhSwp1+gY=,tag:Tc6Wh/yuhgr0lgN1Zkxaag==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:08Z'
    enc: CiUA4OM7eIZytD5JB9ho4vQhMCLWjU4b6dev3JJtj1gHMppD5em/EkkAZoeZpkGxYcCXTHbX1YbCVD843YG1UXk3sGpdhNHzSaI1gqkjVJbURnY8F1eJ3T1nYnpYPF05j/gblzi5IDbp3tHSQx8ZEvmi
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:09Z'
  mac: ENC[AES256_GCM,data:MhgbtAT/Zr9KpE0vEYqI/LxnZhs204SxUi9S7amLFAGtaPWfpGgYZ08qTxS/L/Qln9odiefUpM+zMCqTjmo1S6lFp31hs4cNkYW2y8GkOM5ThFZPnwMzNdujonRTeuuai5UpVR8w2tw5V9sPsylu7kL63qT5pUdTRUaj7ZnBjJk=,iv:+k4e1aas7dQgTaa5ztSBP2Ozy9g5vyilwKb9CLgC/xo=,tag:JGNuW8y8KcpsRsn/HuA6ww==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
