prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:HY2Tkz5Zuk2Bg2PAmwmDsOUDHlb2E3nRgEKHFA/CMJgHH9MK8v1z1PzM1daCk0VP5POHtcBsTGtLD0SbfChJxA==,iv:vJPqpnmGisoKkzBdayjDgoEKFughhF5q/qgoaRYZWsk=,tag:lJoE08pRvnTOg9pQNKLQIA==,type:str]
    password: ENC[AES256_GCM,data:vrQkD4fNcmeIFun0PHc4dqi8ycQXydPq6SG69OS/gEfTad0yQ2X/NlvRQU4DiS0OVIzrcaVXkbJMBIfucj6syQ==,iv:J2G0ts/eeErK3ieW9G8l7aesl9Af7kaERIS8yu/XAIA=,tag:XSKkbzerkz2fDXn5IC7EGA==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:OQRNJI/Jb00qQLHet/8CgHfqpuM=,iv:7my3/eAIdb2E9lfMKXZWRgcImmic87r7tZPoWra71kg=,tag:f4He/tVlfHeJuHIqKQMaPA==,type:str]
      client_secret: ENC[AES256_GCM,data:uaPlES0RjsVtZHEDiqX+VcJQPPdQ0I+62nMybwxjfBKZRm6CpQWyiQ==,iv:x/L7m7D7hBRaDU4ISmUJIcRrRSq3bnECA+7Ms03Tt70=,tag:fbYexDVU/zBsvWhlH+GxNA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:03Z'
    enc: CiUA4OM7eHnj2sR51kmIxzvxjS8E/9pn/oCXcXFTwEYCMpjATN7FEkkAZoeZpot/tDHqLQwAGNdgn+d6yIFDSekiMyIJnpRX9miKAT5/Bsi0qyqJBmOi44DRDE4r1X6F+UtHEiayv70Xdka17GFvDDe4
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:03Z'
  mac: ENC[AES256_GCM,data:klxiDwq1zts+yKC0UvUU+Xse8svDwqThIUExv4F8VXg76J0Fj1CWfED3CzJ5EQlAz9hlf36GLsdhiVj2AVtYVmTk/exAONt2J+P2+Rv14IJK3tSQ9UZgWGufZhCkhPLybXCrQqXmm8N3ZB6ORxaGMGKdpLV3ims5vte0j7wPeL8=,iv:I/V2EXcdpyPskxHYp0sksHT7mywdq+hMt84cLHCfslY=,tag:YnsgJtsyeU1PaUoKVwccTA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
