nfs:
  pv:
    serverIP: 10.15.246.63
jupyterhub:
  ingress:
    hosts: [iner.latam.catalystproject.2i2c.cloud]
    tls:
    - hosts: [iner.latam.catalystproject.2i2c.cloud]
      secretName: https-auto-tls
  custom:
    homepage:
      templateVars:
        org:
          name: Catalyst Project, LatAm - INER
  hub:
    config:
      JupyterHub:
        authenticator_class: github
      GitHubOAuthenticator:
        oauth_callback_url: https://iner.latam.catalystproject.2i2c.cloud/hub/oauth_callback
        allowed_organizations:
        - CatalystProject-Hubs:iner
      Authenticator:
        admin_users:
        - Gabo8611
        - Yalbibalderas
jupyterhub-home-nfs:
  gke:
    volumeId: projects/catalystproject-392106/zones/southamerica-east1-c/disks/hub-nfs-homedirs-iner
  persistentVolume:
    size: 10Gi
