userServiceAccount:
  annotations:
    iam.gke.io/gcp-service-account: latam-valledellili@catalystproject-392106.iam.gserviceaccount.com
jupyterhub:
  ingress:
    hosts: [valledellili.latam.catalystproject.2i2c.cloud]
    tls:
    - hosts: [valledellili.latam.catalystproject.2i2c.cloud]
      secretName: https-auto-tls
  custom:
    homepage:
      templateVars:
        org:
          name: Catalyst Project, LatAm - Fundaci√≥n Valle del Lili-UMBC & AC3
  singleuser:
    extraEnv:
      SCRATCH_BUCKET: gs://latam-scratch-valledellili/$(JUPYTERHUB_USER)
  hub:
    config:
      JupyterHub:
        authenticator_class: github
      GitHubOAuthenticator:
        oauth_callback_url: https://valledellili.latam.catalystproject.2i2c.cloud/hub/oauth_callback
        allowed_organizations:
        - catalystproject-hubs:valledellili
      Authenticator:
        admin_users:
        - pattiordonez
jupyterhub-home-nfs:
  gke:
    volumeId: projects/catalystproject-392106/zones/southamerica-east1-c/disks/hub-nfs-homedirs-valledellili
  persistentVolume:
    size: 10Gi
nfs:
  pv:
    serverIP: 10.15.255.113
