name: carbonplan
provider: aws # https://631969445205.signin.aws.amazon.com/console
account: "631969445205"
aws:
  key: enc-deployer-credentials.secret.json
  clusterType: eks
  clusterName: carbonplanhub
  region: us-west-2
support:
  helm_chart_values_files:
    - support.values.yaml
    - enc-support.secret.values.yaml
hubs:
  - name: staging
    display_name: "Carbon Plan (AWS, staging)"
    domain: staging.carbonplan.2i2c.cloud
    helm_chart: daskhub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: github
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - common.values.yaml
  - name: prod
    display_name: "Carbon Plan (AWS, prod)"
    domain: carbonplan.2i2c.cloud
    helm_chart: daskhub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: github
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - common.values.yaml
