prometheusIngressAuthSecret:
  enabled: true

prometheus:
  server:
    ingress:
      enabled: true
      hosts:
        - prometheus.carbonplan.2i2c.cloud
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.carbonplan.2i2c.cloud
    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 4
        memory: 8Gi

cluster-autoscaler:
  enabled: true
  autoDiscovery:
    clusterName: carbonplanhub
  awsRegion: us-west-2

grafana:
  grafana.ini:
    server:
      root_url: https://grafana.carbonplan.2i2c.cloud/
    auth.github:
      enabled: true
      allowed_organizations: 2i2c-org
  ingress:
    hosts:
      - grafana.carbonplan.2i2c.cloud
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.carbonplan.2i2c.cloud
