# See https://pre-commit.com/ for more information
repos:

# Autoformat YAML with ruamel.yaml, so we can also use its roundtripping
# capabilities for writing mass refactoring scripts.
- repo: https://github.com/yuvipanda/ruamelfmt
  rev: v1.0.0
  hooks:
  - id: ruamelfmt
    exclude: helm-charts/.*|config/clusters/templates/.*

  # Autoformat: Python code, syntax patterns are modernized
- repo: https://github.com/asottile/pyupgrade
  rev: v3.21.2
  hooks:
  - id: pyupgrade
    args:
    - --py36-plus

  # Autoformat: Python code
- repo: https://github.com/pycqa/isort
  rev: 7.0.0
  hooks:
  - id: isort

  # Autoformat: Python code
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 25.11.0
  hooks:
  - id: black

  # Lint: Python code
- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
  - id: flake8

  # Run `terraform fmt` on all our terraform files automatically
- repo: https://github.com/yuvipanda/terraform-bin
  rev: v3.0.0
  hooks:
  - id: terraform-fmt
    exclude: terraform/aws/projects/template.tfvars

  # Prevent unencrypted files from being committed
- repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
  rev: v1.1
  hooks:
  - id: sops-encryption
    # Add files here if they contain the word 'secret' but should not be encrypted
    exclude: secrets\.md|helm-charts/support/templates/prometheus-ingres-auth/secret\.yaml|helm-charts/basehub/templates/dex/secret\.yaml|helm-charts/basehub/templates/static/secret\.yaml|config/clusters/templates/common/support\.secret\.values\.yaml|helm-charts/basehub/templates/ingress-auth/secret\.yaml|helm-charts/aws-ce-grafana-backend/templates/secret\.yaml

  # Prevent known typos from being committed
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args:
    # Autofix known typos
    - --write-changes
    additional_dependencies:
    - tomli

# Autoformat jsonnet
- repo: https://github.com/google/go-jsonnet
  rev: v0.21.0
  hooks:
  - id: jsonnet-format
    exclude: eksctl/template.jsonnet

- repo: local
  hooks:
  - id: disallow-dev-commands
    name: disallow dev commands in commands
    language: pygrep
    entry: \b(from|import)\b.*dev_commands
    files: ^deployer/commands/.*$

# pre-commit.ci config reference: https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
