- name: nfs server setup
  hosts: nfs_servers
  connection: ssh
  become: true
  handlers:
    - name: re-export NFS Shares
      command:
        cmd: exportfs -ra
  tasks:
    - name: Install NFS packages
      apt:
        pkg:
          - nfs-kernel-server
          - nfs-common
          - xfsprogs
    - name: Setup XFS
      filesystem:
        fstype: xfs
        dev: /dev/disk/azure/scsi1/lun{{ disk_lun }}
        resizefs: true

    - name: Mount disk
      mount:
        path: /export/{{ disk_name }}
        src: /dev/disk/azure/scsi1/lun{{ disk_lun }}
        state: mounted
        fstype: xfs
        opts: inode64,prjquota

    - name: Create home container directory
      file:
        state: directory
        owner: "1000"
        group: "1000"
        path: /export/{{disk_name}}/homes
        mode: 0700

    - name: setup exports file
      notify:
        - re-export NFS Shares
      copy:
        dest: /etc/exports
        content: >
          /export/disk1 10.0.0.0/8(all_squash,anonuid=1000,anongid=1000,no_subtree_check,rw,sync)
