name: bnext-bio
provider: aws
provider_url: https://2i2c.awsapps.com/start#/
aws:
  account: 882437028641
  key: enc-deployer-credentials.secret.json
  clusterType: eks
  clusterName: bnext-bio
  region: us-west-2
  billing:
    paid_by_us: true
support:
  helm_chart_values_files:
  - support.values.yaml
  - enc-support.secret.values.yaml
hubs:
- name: staging
  display_name: bnext-bio - staging
  domain: staging.beta-hub.nucleus.engineering
  helm_chart: basehub
  helm_chart_values_files:
  - common.values.yaml
  - staging.values.yaml
  - enc-staging.secret.values.yaml
  chart_override: staging-chart.yaml
- name: prod
  display_name: bnext-bio - prod
  domain: beta-hub.nucleus.engineering
  helm_chart: basehub
  helm_chart_values_files:
  - common.values.yaml
  - prod.values.yaml
  - enc-prod.secret.values.yaml
