prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:v67glZpAsM/bJPz3VyYZ4yt93tlpL7WE+9069O3YEOOaaAwytQtkIKh8wclZENXqPLxURTuWR0jW874xjVBGcikk05E0cZGRe7uSOqFFVMOHg3Ql0Lc8zwOqdxkwX/jd3sN/JirxAhg8s9zcj0FVUaJClVGjAZ5kLfG0WzFnE8yYeFLsM2xTGiQ/J9lUxXpev1u3CsehHVuf9GNq,iv:mVl54HkVT61zGFUedyAyjQJMTBBtYYvqq9fkCor4BhA=,tag:1vlKSsvCWpEX9wFenpAL5g==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:G5vJC8Thf9tcS9xy7ugeHPf2uY9L7rz23XWpv5+44C6p/37OPAv6RrT4oryd6t4RGRPBhawyMjO92lEtxHzJTQ==,iv:DU8B3pIO1y1Pl+mmuHtzuRipuHmlELaOGb1+fB56xMI=,tag:0Ckl2ZE4Ye979nRyC9rh6g==,type:str]
    password: ENC[AES256_GCM,data:M4mUOuK2FPq1MDi95ABR5M0wbd043ieiQ82I44CEbGtjc9Spz9hyXbNwJTJW20vmH4JM1FMdtjOL8g7FRHdOrg==,iv:Kzu8ZkoJBcyb4IUnpNSx7uce9unRD3hbSW+vuOYTBjg=,tag:NdwTce7/GM+3uxW3buVCOA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:17Z'
    enc: CiUA4OM7eDAd+Dg76fSNLkrTuXf9TvUsF73Hdf03pY7k2uBwW3nmEkkAZoeZpkZRLC5cubeI9v1lqKWTC6oZNELFTM0qr8XOTXh5DXFnaOw4L3XrrF3260dw6rfdDeaD1BaXIOjF5KBTkQKfQ1FXrygp
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:18Z'
  mac: ENC[AES256_GCM,data:2dV907tLhdPpvnKw18QJEFnJmmpCnQ9YNQVPicyYSzp79odV+fUNV3H6MwzkYBWJovD0LDfwWi27Tnoa17CfD0ISzQrYohcFF+IMjjpfUbn2d+986K03zIn7+RDAwv7iIZs4xfpacb69iSZNa8juV45zfHhKLVIgTIVoc6ujmLI=,iv:/tCStgBQjRSrFKogDzeT3wY5Clw+ymVsfDkDSHimWJM=,tag:9topEmjOX5Q/PVhMdJOqZg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
