prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:HMKqqUShhyvc88784xb8sFQOJDMOqvPx3dRWfDc1pnBOBJk0UeCdlufabKc00gSKrucz81H8JoLhfPV8A+3kmg==,iv:dz7JNHGhpNUl0MsPtljSDXDNGviLUH4Sh4vJraqeA28=,tag:/jO771KzglStgs8O1bHGwg==,type:str]
    password: ENC[AES256_GCM,data:PqmrbdxbhwQcS/i0W1f0tzpFt1weV1pAuPEJGOdWate0FN1WbR4wSN7Bei6jQC02qyb8HRI/hV9Djokdwyq/KA==,iv:8GBbqbDo55cLXa6E5Hjm5bDUa4cOjeaYppu/K69+dFM=,tag:Uh7EnMpqjVNGdQjDOBArfQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:12Z'
    enc: CiUA4OM7eM4gBcfSTdm826WjRguthIs76Ji3tqGRqoEobf6h2tduEkkAZoeZpgMiLfi2YSTZ0pjKYQNvtBZT5oH1arF6PkLWFQ+QT7rWmds3A2FoDjaQvkk/vcEiHv7Y+iNp6i69yKhaRA4C+Ef/2LHV
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:12Z'
  mac: ENC[AES256_GCM,data:r8ozTX8ajluXRT80baa9PrdEuanI4ZoQTeXufn39ed25TRof73a+tNr9VlqnfMc30nd4rbYPoH+e8KyQyEWlyVBtLgiq1Ndy9pF1xTRQPmCLrWJM86U5XtseMz0ihBMjs/ud+27Y6AkDWODwDd8XAvz80RIALetrgC8k1FmRBwM=,iv:wHTvXBEH95vfGq1J3oUGR0YBDMGGGQ880pWngpclVbY=,tag:iMfN2lu2X/UhvirFNG+3NQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
