nfs:
  pv:
    serverIP: 10.100.10.116

userServiceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::882437028641:role/bnext-bio-prod

jupyterhub:
  ingress:
    hosts: [hub.nucleus.engineering]
    tls:
    - hosts: [hub.nucleus.engineering]
      secretName: https-auto-tls
  hub:
    config:
      JupyterHub:
        authenticator_class: github
      GitHubOAuthenticator:
        oauth_callback_url: https://hub.nucleus.engineering/hub/oauth_callback
  singleuser:
    image:
      name: quay.io/nucleus/nucleus-hub
      tag: 2i2c
      pullPolicy: Always
    memory:
      guarantee: 3902839759
      limit: 3902839759
    cpu:
      guarantee: 0.4563125
      limit: 3.6505
    nodeSelector:
      node.kubernetes.io/instance-type: r5.xlarge
      2i2c/hub-name: prod
    extraEnv:
      SCRATCH_BUCKET: s3://bnext-bio-scratch/$(JUPYTERHUB_USER)
      PERSISTENT_BUCKET: s3://bnext-bio-persistent/$(JUPYTERHUB_USER)
      GH_SCOPED_CREDS_CLIENT_ID: Iv23liocJ0YYNRVKqmxr
      GH_SCOPED_CREDS_APP_URL: https://github.com/apps/bnext-prod-github-push-access

jupyterhub-home-nfs:
  eks:
    volumeId: vol-05cb0def7452bcedf


binderhub-service:
  config:
    BinderHub:
      image_prefix: quay.io/imagebuilding-non-gcp-hubs/bnext-bio-prod-
