prometheusIngressAuthSecret:
  enabled: true

prometheus:
  server:
    persistentVolume:
      size: 100Gi
    ingress:
      enabled: true
      hosts:
      - prometheus.bnext-bio.2i2c.cloud
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.bnext-bio.2i2c.cloud

grafana:
  grafana.ini:
    server:
      root_url: https://grafana.bnext-bio.2i2c.cloud/
  auth.github:
    enabled: true
    allowed_organizations: 2i2c-org
  persistence:
    # We don't need 10Gi on the Grafana persistent directory
    size: 1Gi
  ingress:
    hosts:
    - grafana.bnext-bio.2i2c.cloud
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.bnext-bio.2i2c.cloud

cluster-autoscaler:
  enabled: true
  autoDiscovery:
    clusterName: bnext-bio
  awsRegion: us-west-2

calico:
  enabled: true

nvidiaDevicePlugin:
  aws:
    enabled: true

redirects:
  rules:
  - from: staging.bnext-bio.2i2c.cloud
    to: staging.hub.nucleus.engineering
  - from: bnext-bio.2i2c.cloud
    to: hub.nucleus.engineering
