basehub:
  nfs:
    pv:
      # from https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-nfs-mount-settings.html
      mountOptions:
        - rsize=1048576
        - wsize=1048576
        - timeo=600
        - soft # We pick soft over hard, so NFS lockups don't lead to hung processes
        - retrans=2
        - noresvport
      serverIP: fs-b25253b5.efs.us-west-2.amazonaws.com
      baseShareName: /
  jupyterhub:
    custom:
      2i2c:
        add_staff_user_ids_to_admin_users: true
        add_staff_user_ids_of_type: "github"
      homepage:
        templateVars:
          org:
            name: Openscapes
            logo_url: https://www.openscapes.org/img/logo.png
            url: https://www.openscapes.org/
          designed_by:
            name: 2i2c
            url: https://2i2c.org
          operated_by:
            name: 2i2c
            url: https://2i2c.org
          funded_by:
            name: Openscapes
            url: https://www.openscapes.org/
    singleuser:
      serviceAccountName: cloud-user-sa
      defaultUrl: /lab
      # User image repo: https://github.com/NASA-Openscapes/corn
      image:
        name: 783616723547.dkr.ecr.us-west-2.amazonaws.com/user-image
        tag: "d78bb6c"
      storage:
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/shared
            subPath: _shared
            readOnly: false
      profileList:
        # NOTE: About node sharing
        #
        #       CPU/Memory requests/limits are actively considered still. This
        #       profile list is setup to involve node sharing as considered in
        #       https://github.com/2i2c-org/infrastructure/issues/2121.
        #
        #       - Memory requests are lower than the description, with a factor
        #         of (node_max_mem - 4GB) / node_max_mem.
        #       - CPU requests are lower than the description, with a factor of
        #         10%.
        #
        - display_name: "Small: up to 4 CPU / 32 GB RAM"
          description: &profile_list_description "Start a container with at least a chosen share of capacity on a node of this type"
          slug: small
          default: true
          profile_options:
            image: &profile_options_image
              display_name: Image
              choices:
                python:
                  display_name: Python
                  default: true
                  slug: python
                  kubespawner_override:
                    image: openscapes/python:2d9c952
                rocker:
                  display_name: R
                  slug: rocker
                  kubespawner_override:
                    image: openscapes/rocker:a7596b5
                matlab:
                  display_name: Matlab
                  slug: matlab
                  kubespawner_override:
                    image: openscapes/matlab:fb41496
            requests:
              # NOTE: Node share choices are in active development, see comment
              #       next to profileList: above.
              display_name: Node share
              choices:
                mem_1:
                  default: true
                  display_name: ~1 GB, ~0.125 CPU
                  kubespawner_override:
                    mem_guarantee: 0.875G
                    cpu_guarantee: 0.013
                mem_2:
                  display_name: ~2 GB, ~0.25 CPU
                  kubespawner_override:
                    mem_guarantee: 1.75G
                    cpu_guarantee: 0.025
                mem_4:
                  display_name: ~4 GB, ~0.5 CPU
                  kubespawner_override:
                    mem_guarantee: 3.5G
                    cpu_guarantee: 0.05
                mem_8:
                  display_name: ~8 GB, ~1.0 CPU
                  kubespawner_override:
                    mem_guarantee: 7.0G
                    cpu_guarantee: 0.1
                mem_16:
                  display_name: ~16 GB, ~2.0 CPU
                  kubespawner_override:
                    mem_guarantee: 14.0G
                    cpu_guarantee: 0.2
                mem_32:
                  display_name: ~32 GB, ~4.0 CPU
                  kubespawner_override:
                    mem_guarantee: 28.0G
                    cpu_guarantee: 0.4
          kubespawner_override:
            cpu_limit: null
            mem_limit: null
            node_selector:
              node.kubernetes.io/instance-type: r5.xlarge
        - display_name: "Medium: up to 16 CPU / 128 GB RAM"
          description: *profile_list_description
          slug: medium
          profile_options:
            image: *profile_options_image
            requests:
              # NOTE: Node share choices are in active development, see comment
              #       next to profileList: above.
              display_name: Node share
              choices:
                mem_1:
                  display_name: ~1 GB, ~0.125 CPU
                  kubespawner_override:
                    mem_guarantee: 0.969G
                    cpu_guarantee: 0.013
                mem_2:
                  display_name: ~2 GB, ~0.25 CPU
                  kubespawner_override:
                    mem_guarantee: 1.938G
                    cpu_guarantee: 0.025
                mem_4:
                  default: true
                  display_name: ~4 GB, ~0.5 CPU
                  kubespawner_override:
                    mem_guarantee: 3.875G
                    cpu_guarantee: 0.05
                mem_8:
                  display_name: ~8 GB, ~1.0 CPU
                  kubespawner_override:
                    mem_guarantee: 7.75G
                    cpu_guarantee: 0.1
                mem_16:
                  display_name: ~16 GB, ~2.0 CPU
                  kubespawner_override:
                    mem_guarantee: 15.5G
                    cpu_guarantee: 0.2
                mem_32:
                  display_name: ~32 GB, ~4.0 CPU
                  kubespawner_override:
                    mem_guarantee: 31.0G
                    cpu_guarantee: 0.4
                mem_64:
                  display_name: ~64 GB, ~8.0 CPU
                  kubespawner_override:
                    mem_guarantee: 62.0G
                    cpu_guarantee: 0.8
                mem_128:
                  display_name: ~128 GB, ~16.0 CPU
                  kubespawner_override:
                    mem_guarantee: 124.0G
                    cpu_guarantee: 1.6
          kubespawner_override:
            cpu_limit: null
            mem_limit: null
            node_selector:
              node.kubernetes.io/instance-type: r5.4xlarge
        - display_name: "Large: up to 64 CPU / 512 GB RAM"
          description: *profile_list_description
          slug: large
          profile_options:
            image: *profile_options_image
            requests:
              # NOTE: Node share choices are in active development, see comment
              #       next to profileList: above.
              display_name: Node share
              choices:
                mem_4:
                  display_name: ~4 GB, ~0.5 CPU
                  kubespawner_override:
                    mem_guarantee: 3.969G
                    cpu_guarantee: 0.05
                mem_8:
                  display_name: ~8 GB, ~1.0 CPU
                  kubespawner_override:
                    mem_guarantee: 7.938G
                    cpu_guarantee: 0.1
                mem_16:
                  default: true
                  display_name: ~16 GB, ~2.0 CPU
                  kubespawner_override:
                    mem_guarantee: 15.875G
                    cpu_guarantee: 0.2
                mem_32:
                  display_name: ~32 GB, ~4.0 CPU
                  kubespawner_override:
                    mem_guarantee: 31.75G
                    cpu_guarantee: 0.4
                mem_64:
                  display_name: ~64 GB, ~8.0 CPU
                  kubespawner_override:
                    mem_guarantee: 63.5G
                    cpu_guarantee: 0.8
                mem_128:
                  display_name: ~128 GB, ~16.0 CPU
                  kubespawner_override:
                    mem_guarantee: 127.0G
                    cpu_guarantee: 1.6
                mem_256:
                  display_name: ~256 GB, ~32.0 CPU
                  kubespawner_override:
                    mem_guarantee: 254.0G
                    cpu_guarantee: 3.2
                mem_512:
                  display_name: ~512 GB, ~64.0 CPU
                  kubespawner_override:
                    mem_guarantee: 508.0G
                    cpu_guarantee: 6.4
          kubespawner_override:
            cpu_limit: null
            mem_limit: null
            node_selector:
              node.kubernetes.io/instance-type: r5.16xlarge
    scheduling:
      userScheduler:
        enabled: true
      userPods:
        nodeAffinity:
          matchNodePurpose: require
    hub:
      allowNamedServers: true
      networkPolicy:
        # FIXME: For dask gateway
        enabled: false
      readinessProbe:
        enabled: false
      config:
        Authenticator:
          admin_users: &users
            - amfriesz
            - jules32
            - erinmr
            - betolink
          # Without this, any GitHub user can authenticate
          allowed_users: *users
dask-gateway:
  gateway:
    extraConfig:
      idle: |-
        # timeout after 30 minutes of inactivity
        c.KubeClusterConfig.idle_timeout = 1800
