name: 2i2c
provider: gcp
provider_url: https://console.cloud.google.com/kubernetes/clusters/details/us-central1-b/pilot-hubs-cluster/details?project=two-eye-two-see
tenancy: shared
gcp:
  key: enc-deployer-credentials.secret.json
  project: two-eye-two-see
  cluster: pilot-hubs-cluster
  zone: us-central1-b
  billing:
    paid_by_us: true
    bigquery:
      project: two-eye-two-see
      dataset: cloud_costs
      billing_id: 0157F7-E3EA8C-25AC3C
support:
  helm_chart_values_files:
  - support.values.yaml
  - enc-support.secret.values.yaml
hubs:
- name: staging
  display_name: 2i2c staging
  domain: staging.2i2c.cloud
  helm_chart: basehub
  helm_chart_values_files:
  - basehub-common.values.yaml
  - staging.values.yaml
  - enc-staging.secret.values.yaml
- name: dask-staging
  display_name: 2i2c dask staging
  domain: dask-staging.2i2c.cloud
  helm_chart: daskhub
  helm_chart_values_files:
  - daskhub-common.values.yaml
  - dask-staging.values.yaml
  - enc-dask-staging.secret.values.yaml
- name: mtu
  display_name: Michigan Technological University
  domain: mtu.2i2c.cloud
  helm_chart: basehub
  helm_chart_values_files:
  - basehub-common.values.yaml
  - mtu.values.yaml
  - enc-mtu.secret.values.yaml
