jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:5+R0hkuhxaQ4X06AGQRTN5NfLlETd1ORNecL5dlwcta8UmZEt/i0V3ZKJrallxyRHjDmLoic,iv:J0UdCasG63PXTXY4SNaSizP3LRg53U4xDZDCKMIb3rw=,tag:ViXYgWzWKYAXd6Gm0+JF0A==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-11-24T12:45:43Z'
    enc: CiUA4OM7eM+DVPb60c1Q9JHMBJvw0FOwkt3z1VEqYB3ugy68eoRWEkkAZoeZpsa8s7YSsNlF657VhFnmY4AMkroA69h0W779iNSINSAjWR0fNRhE+bynfH32n1K+QB0b0QQJFSk632Vp0p3hOlhW+Ss8
  lastmodified: '2025-11-24T12:45:43Z'
  mac: ENC[AES256_GCM,data:CXu8FWJGyP6UjhE5uFHy3F1IpYS4h4k0KYdXlI6McuNIHxtlGCS7K9BqCjZtBF+oqDq5gyzzYslugYmpI0mrxH1S5UNRXBqB/l+4A2DBoCgnGIpABPGHJEqqRTsgttOybLSpqz9QV9wIH5INDU3zU0BZyVwP+dId8uluQdvlJxc=,iv:sB8g8DHNA1jKDK1JJM+Yxof67xyleTmm+kghu3MRii8=,tag:g9/vjdfY31lGiZ3wQRVBng==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
