prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:ZrKSIJSDbIsJt+OhLBiHL31OdsphbOUMKoY1QPK9NII7l/RIVlKW8S6+1OkP2b+xFyHdP06tkriDPhI3aLqnNw==,iv:5q/UXZmFvryThc3wV7KaNwSBbPpaXp6Q9askH8MANes=,tag:wM+/xDtZNUyhS29dTfOvlA==,type:str]
    password: ENC[AES256_GCM,data:R3KD2WfgV+Mz7adbn6Fx8PO1UWdYsKWTISgXrwWZlEeGolPpVuGXpaSZk+rtkVwDGKZ3zjNBmvfuhbFrnV0k3g==,iv:mUlq2tENwYDEHUHZxRy5cjsHORzMu6XDxf6X9FQUqmQ=,tag:CNRkJLBM1b3V9zvb6CDVAA==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:TNvvL0bqGf3ohrXRwQNGHUwtINE=,iv:nAap/R2Xvv3EqRS3ki/a+gTYi9r23dI3dmhCUK10Pt0=,tag:FbFMAvYo2JEryObQ16BJfg==,type:str]
      client_secret: ENC[AES256_GCM,data:cWaFHZDKq3jELClA2PjyvqStRFLMhDGlfXpSYpykVuCOm8CS68ZQ0w==,iv:SEFxQ1Jpt+PaeVzCXiVg+iDY0CEL4G8NELunEj2TY9M=,tag:Qssph+Fdwqq8e7JLSyEzeA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:05Z'
    enc: CiUA4OM7eGpUzM1l+yq3+H1fRH16skntfek0/ppVzQon64p1QIGYEkkAZoeZpjObmwmS4q84b+WMwnnrMAdvXq3FHO+ubzdiExEMr9REXZW1e3MEflzUluoxRy7F7U8mVICFIgmWT2AfLwDUTFyZXdxN
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:05Z'
  mac: ENC[AES256_GCM,data:WcvLKAfq2IUbk73VWGUa/Ixzdzf1JkmijrfvTokP5kbHeBBrO+gUzacZsz7YH94wGXq7rzRt/nlQ54MeMZ/15JMv5GtmfW7zA4z2n/Z/tbL5bWNJguiBvaHT6kXilrCq+zeBl2Vw9S6FP9EcdhVkSRo8b/GMaIXE2C4Aj+M0z7k=,iv:WhhrUWhfcp7qq4IxIPxejdsWWQAt6g7l877iO8wZFmc=,tag:fx/cuT9jz9BxzpS+D/vPOw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
