prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:W0G6H+16dxKihTFt0BHYwS4tgUxj14VshZffW52nHpAMY8M0vCkxfY6WCwP5G9jRmGQ1Ccb3RDJX8n4WS5VjOivzRz1r0N7YxGKncc5RsdDFEDO+ghhU7SoBPg3dujqhOD4At1KYGPONMNO6TNMQ55xLdO4f+OvtPOR1QrVB69QEBNQhlFejyEhd2s/9+reJ0jL2AW571ubGBT7I,iv:Qxxr+yDjhJwoZqCEFCf7+Pg9KNF5nzaWZDzDItK/FXQ=,tag:LtoQJy5TRz8DrCdJnCsJHw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:2Jp7e6sQeEjpt2ay5QjzBMcPfOAMzJH7RYts+tZRs+YmwacHcbfDhSwNdkmyeO6xJuDo6pAkdwIGS+ukNAKOBg==,iv:CkGI9nsrqKQVqQy2PzaOuG4piPZ9niLGisybQspYM2Q=,tag:m2MP8g83pcMqsSYBA6Ponw==,type:str]
    password: ENC[AES256_GCM,data:R8jKbcQ6bmptGfOF8pX+rT2hO70UE8aVgxTrwezecBSP4MAfB12VYTVlx3wjbDA3SjrXSOzH+eWU1AmM8yw4sg==,iv:9GNZx0ZB1dY6ciInybzm0xKG1sUwmx+mpKcVfPuZ4i8=,tag:pDawR/bbvw7jtcXqO4zwuQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:awkOJ+Q7cKcK9zOIrZ6lnAJ0vkk=,iv:sU1sSLrLEdEY03G06TLcC/1rF8eC69D+77xAVSiYjRo=,tag:AELDcubVAgviuqbBwq+bEg==,type:str]
      client_secret: ENC[AES256_GCM,data:6RImEO7oyYzS6GYzP78XJxQLl3PjASjgKbEM44o4DhW1F5sKrcVbBQ==,iv:3t5xV4DazfT5Bwy4kIy6A4uJUsbzbnAn3CAhJjiduMo=,tag:AZeH29a0V/GgHMRdevbD0Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:11Z'
    enc: CiUA4OM7eHiDYvlRsfXsLusWmoIgoYTS4zp+fRRF8e9PysWz4KC5EkkAZoeZppKP/ednLsPK93qP9JZ3621jDb5tHhBNMdWnsWgbpctEZokVxnEOdu5ijzNR5xA4ErxnQvwS9n+ysnBNpfgUjFpOI8y5
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:11Z'
  mac: ENC[AES256_GCM,data:PXRnwWBlklg7CgEPGRspXi7X0kClJ1Y5EYsOen46vicc3t3ljmx9AzzU5hnBuQdTGnrxROnSXSz94kimzgnz+oQjMqRrOebd6hGHn3qd1kpb+a2q+Vu/v7JCvNrQHKTvhWg25/RfDCrZ6uPa9iYmKGXyAfvv0j7t9VFgS3rvgsI=,iv:eb3mKfTS0c4aM6spz4qvULmZomg3yP8iSYKkp8FvJwQ=,tag:GfGs49A+I6iu3KlO7R01nw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
