basehub:
  userServiceAccount:
    annotations:
      iam.gke.io/gcp-service-account: pilot-hubs-ohw@two-eye-two-see.iam.gserviceaccount.com
  jupyterhub:
    ingress:
      hosts:
        - oceanhackweek.2i2c.cloud
      tls:
        - secretName: https-auto-tls
          hosts:
            - oceanhackweek.2i2c.cloud
    # Enabled prepuller for event: https://github.com/2i2c-org/infrastructure/issues/2879
    prePuller:
      hook:
        enabled: true
      continuous:
        enabled: true
    singleuser:
      nodeSelector:
        2i2c.org/community: ohw
      extraTolerations:
        - key: "2i2c.org/community"
          operator: "Equal"
          value: "ohw"
          effect: "NoSchedule"
      networkPolicy:
        # In clusters with NetworkPolicy enabled, do not
        # allow outbound internet access that's not DNS, HTTP or HTTPS
        # For OHW, we allow 8080 (for DAP) and 22 (for ssh)
        # https://github.com/2i2c-org/infrastructure/issues/549#issuecomment-892276020
        enabled: true
        egress:
          - ports:
              - port: 53
                protocol: UDP
          - ports:
              - port: 80
                protocol: TCP
          - ports:
              - port: 443
                protocol: TCP
          - ports:
              - port: 8080
                protocol: TCP
          - ports:
              - port: 22
                protocol: TCP
      profileList:
        - display_name: "Python using JupyterLab"
          description: "~2 CPU, ~8G RAM"
          default: true
          kubespawner_override:
            image: "ghcr.io/oceanhackweek/python:b6177db"
            default_url: "/lab"
            mem_limit: 8G
            mem_guarantee: 4G
            cpu_limit: 2
            cpu_guarantee: 0.5
        - display_name: "R using RStudio"
          description: "~2 CPU, ~8G RAM"
          kubespawner_override:
            image: "ghcr.io/oceanhackweek/r:2b505d5"
            default_url: "/rstudio"
            mem_limit: 8G
            mem_guarantee: 4G
            cpu_limit: 2
            cpu_guarantee: 0.5
      extraEnv:
        GH_SCOPED_CREDS_CLIENT_ID: "Iv1.9c20af442fad0d86"
        GH_SCOPED_CREDS_APP_URL: "https://github.com/apps/ohw-gh-scoped-creds-app"
    custom:
      cloudResources:
        provider: gcp
        gcp:
          projectId: two-eye-two-see
        scratchBucket:
          enabled: true
      2i2c:
        add_staff_user_ids_to_admin_users: true
        add_staff_user_ids_of_type: "github"
      homepage:
        templateVars:
          org:
            name: OceanHackWeek
            logo_url: https://avatars.githubusercontent.com/u/33128979
            # logo_url: https://intercoonecta.github.io/_static/OHWe.png
            url: https://oceanhackweek.org/
          designed_by:
            name: 2i2c
            url: https://2i2c.org
          operated_by:
            name: 2i2c
            url: https://2i2c.org
          funded_by:
            name: IOOS
            url: https://ioos.us/
    hub:
      config:
        JupyterHub:
          authenticator_class: github
        GitHubOAuthenticator:
          oauth_callback_url: https://oceanhackweek.2i2c.cloud/hub/oauth_callback
          allowed_organizations:
            - 2i2c-org:hub-access-for-2i2c-staff
            - oceanhackweek:ohw23-organizers
            - oceanhackweek:ohw23-participants-australia
            - oceanhackweek:ohw23-participants-seattle
            - oceanhackweek:ohw23-participants-virtual
            - oceanhackweek:ohw23-project-mentors
            - oceanhackweek:ohw23-tutorial-presenters
          scope:
            - read:org
        Authenticator:
          admin_users:
            - ocefpaf
            - abkfenris
