dex:
  enabled: false
  hubHostName: staging.2i2c.cloud

staticWebsite:
  enabled: false
  source:
    git:
      repo: https://github.com/jupyter/try.jupyter.org
      branch: gh-pages
  ingress:
    host: staging.2i2c.cloud
    path: /textbook
  githubAuth:
    enabled: false

jupyterhub:
  ingress:
    hosts:
      - staging.2i2c.cloud
    tls:
      - secretName: https-auto-tls
        hosts:
          - staging.2i2c.cloud
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: true
      add_staff_user_ids_of_type: "google"
    homepage:
      templateVars:
        org:
          name: 2i2c Staging
          url: https://2i2c.org
          logo_url: https://2i2c.org/media/logo.png
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: 2i2c
          url: https://2i2c.org
  hub:
    # FIXME: dex and oauth2-proxy is commented out to avoid error messages until
    #        its fixed to work again, it also makes jupyterhub 5.2.0 fail to
    #        start if it can't connect to this during startup.
    #
    # services:
    #   dex:
    #     url: http://dex:5556
    #     oauth_redirect_uri: https://staging.2i2c.cloud/services/dex/callback
    #     oauth_no_confirm: true
    #     display: false
    #   oauth2-proxy:
    #     url: http://dex:9000
    #     display: false
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        oauth_callback_url: "https://staging.2i2c.cloud/hub/oauth_callback"
        allowed_idps:
          http://google.com/accounts/o8/id:
            default: true
            username_derivation:
              username_claim: "email"
jupyterhub-home-nfs:
  gke:
    volumeId: projects/two-eye-two-see/zones/us-central1-b/disks/hub-nfs-homedirs-staging
  quotaEnforcer:
    # Default quota is 10 GB per user. Uncomment below variable to edit this.
    # hardQuota: "10" # in GB
nfs:
  pv:
    serverIP: 10.3.249.107
