prometheusIngressAuthSecret:
  # First user is reserved for internal 2i2c use, never share this externally. Subsequent user entries are for external use and can be shared with communities.
  users:
    - username: {{ username }}
      password: {{ password }}