prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:4cB3hjfQFQExa/0yBRu5r7zAlGifCVwUO30wWMjeBCFGj3/aWplBIMgsuM/0+MrwFngQljUdBobAjeoHxZ6KT0OIH69FBBfs/RRxsvm/RLgm2z6lLqEtRydvm8uFfnyvg87vCiGlTkYTc4e4oqEr+RX7yCq3e+TUzv+3Zrlu+QHeN2iXP0my4BfqVyj3a0Dxc/xgpbH3P8SQGzm4,iv:LResWWAbyNp9niF3uoXw9rQvLROpiEd32jZRTBPl1oY=,tag:GZb4Vmhd88UdNJOSyh17QA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:kd8OC6FiIzlFJl3hvROOrimtqHDuboQWyY7orrCvPVN5ltnT043T7rGxyuce8Fx2x8NjK8JUFFBFGlWLp03hPQ==,iv:kn/y3uhg4rklfZRaPrA8mOzb3VNom0H834zLDRUYoeE=,tag:KRVH5Gc1itd+PjkMjMIgYA==,type:str]
    password: ENC[AES256_GCM,data:ORhYmopXzVLFxVBpnKsSfhAwyqEtU8Jlp+UMpYl+TkderYzOfxI6vLbIB36E1OsjD+klGrFcHQUOerA9NbUjcQ==,iv:yjs00WkdHDyrG9gxEMn2DVdKv/oYzxNkmR2KmMF7Nw8=,tag:aBxVbKevZgwHPGLP8P15Tg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:JHYI0qgj0i1BkBSE+6HmpphswsQ=,iv:AtO6AoKw2VLOhF9rYkNzRaZxge3XmVNtOVDCmrg9IEQ=,tag:q7MPQjS2AxbxLj126pHGyw==,type:str]
      client_secret: ENC[AES256_GCM,data:HX2IIyJIbHNNvHzwnq0Fwv1fN+kD0nDp+xb+0Psec1NjQOkjL7p7eg==,iv:ubJuKeSpATfVllNkWwSCrQE6cf85mI981vZNAdyMymE=,tag:maCotIXidcArsw+ruqutiQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:11Z'
    enc: CiUA4OM7eFGA/b6lG2GX4fpIvSLkZEcpBgEAMqHHZgwGOF7CuJbdEkkAZoeZppBrmNFSpjQFvE6oSd4pYxBJiAMzirnzZoTPCtJ+jmPb3FgTzEKynvchIjxc9ajMnQnSPX7l5VqLkgZx1NDOvQzz1f/u
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:12Z'
  mac: ENC[AES256_GCM,data:Q/m3BSJvQshYckyGx9kFaEaAeqx7ZQ6MrcJjzU8Jzosjk+a1MVEpyywwU8FXhXE+Df0ZdiSidG0BWCxCZk2AlBejH6HWyqd4qWVJEfYZ5xYAEtt8/6EZtMINtDM6Q0FPo2EjYShBDqlGZjt/z6mfMdr5k7QC0jBHJ8WUfBOza0Y=,iv:JYf0tSnYKX7nH4uDSbOGcTugxEW+y79iYbU/hFY+Goo=,tag:JJhTeHMiphenCMvKYBVcYA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
