prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:L/+8urkmtqIIXvSIZo2a/8OQ049JkD6m8Q6kClqrG2Q+GHMykWgupI0qLZTI5J5srOUFeDtXJgGz+ZbJ7BvRCw==,iv:8M01f9OI2BSlDfk6wF4H/Mc5KWxhXaZ+DSRr6tw5fac=,tag:ZoqDfB5c5fkOJUgMUQbwSg==,type:str]
    password: ENC[AES256_GCM,data:Zd/YKn752fQfnl88IIwvkkwIqofexZ1s44PcrozzOAaJGi9Ppqzq5uCyjdFFVk5XRNdLgJrEk7I1ULGPiPDeEA==,iv:RavTW7nj4lrPORJ9CZ/QyMDf9hl4TomkzmzdscKgAoQ=,tag:UucXtAsSBv6su8DBUitRBg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:pVYQnEsK75e0oTxBIvFT021zOFM=,iv:FrbMJT9OQ+uSOQy99/himfImQr1UXluKcKEXoJ0AZR0=,tag:bB++jCZ+E0QFRN0AwLqs3w==,type:str]
      client_secret: ENC[AES256_GCM,data:QpKeqTNDQwSjHqu4gLqFFgj/TKetTuI5vZNex5QEVix3tbS4mgoVsA==,iv:7wF+xfPmaPjZBARTWmNsAXSQ7Uu4TCYj2+KpxBPYf8U=,tag:0awhvAJly8f1Kir4rgT1Hg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:06Z'
    enc: CiUA4OM7eIFri/BGX5IgLXt0PsLKyOJzfTnmCA0VMnGQg5j4zXOeEkkAZoeZpmOO9t2kYJUZ6nAlb2dRn7/92lWDRuHKzbdns1gjDf1/8RmaMc/YQd3RzfN71Td64vPeyG4CFFl2FwHmugCZIXhaZ7Pi
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:06Z'
  mac: ENC[AES256_GCM,data:xhgXH22IhTMxJvqrW4nRzHKrprP4hUgNKgQv9zwnglhTtmF4FLDG/uFCKpOS2VxsXUoQL94IXjEYhk0IT8grHtzdnQAUmDUMnjD+NkDuUv3KwfVc6stKANMuqn+I2SfNtF0A4V5sd8eO+5NxKm3ogqkfUGkti/qUq20szlWTzAc=,iv:DIy3Qd4mlSPMNEy4DWIwkDObB9l5eTTqPK4wRoDrYps=,tag:xCVAGKnczAnYr8hTKhgJmw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
