prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:AOgZL+um9yy4sIhH+vz6I35LH2Y8jryOeD0m/ebmitQIWtYGumpS9DCn8PNfGm6lEU4iaAWP6mF/6GQZuQWo2S1TYH8pYCmmcmzJf6Hdac7vkJ28BGQXpL826Xp9SHYlL+rIlj072HBqZbxNf/RLEAmEj+kgAadQAtp//UgRw3q1Bi2aLIUVKlmwUhlJF0hjy9PWPAKE+VHulW89,iv:YD+sj5rcnXe0br6w9waXIRsdnTptqg/Vm3VUht3Z+AQ=,tag:GQGTHH6BC1/l/BHVYF11Xg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:RoWEYlcEctK5AOetYw6vk1uaBIlrd5jhWKvmACLCG+Ri8kzTP7fU2HYga8FmXgqLFKO647Z1x6cCU3cdrxYsfw==,iv:UqhCtVKvmlW7FMzZEiQmGVYGpXtC5hJpkz/T5j0jQfY=,tag:HPr3Q+hPfKHhMWjoSHGvvg==,type:str]
    password: ENC[AES256_GCM,data:eagiLVIHo8iKsrV+1ZR/uA5zaHSpWuwXbfzxcM9EchkjRHw+wHP6Qj9Z3QXA6xS8tGAGODxOH7hs3C650q1m4w==,iv:/C1uFpGqeJe0jzPBA6816HWffcFCML4yYhbGNFmB228=,tag:yHF9mGOuUOc/rfH0lRDL9w==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:08Z'
    enc: CiUA4OM7eDA57G7YLzXjfbAv0lUg2mD0INBswbAoIejMdiGSfV6BEkkAZoeZpjtgYhDTIQpx8NcD0+ea8U3taNZ2otBsBGUM6YFmGKRkkKtfxvNo2pLvVqax+krUNEp5hb7c+TF1UEzmSiwPZL3mJezE
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:08Z'
  mac: ENC[AES256_GCM,data:u7DttDCoxZ//D3X5KgI04e22ZxWjKkdoQibD+e5HTCyA8RmGlx619Sy+neFP8vOyDsWq2QoIQ3WCP+Ld3X+DngWOU1hct8WYQCS5ShtUtOwmPsf3wqQSfueja8KzS2vpBfMzUPGrNWjyjJEV3Nni9ETLzeiLxBX/YWWtWKxGaUo=,iv:fKwRr9654hrIvIP9n322l7bqBwPS+gyjebGyoXGxLy0=,tag:Dxz9dSXyxQiQKdf9lwVJ5g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
