prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:i6z9YRZ/cRke1+PdiKIB6Yb1YaRi3Aa2+U00EExoTvGRQUBvjKdJ7aFGR9h5tVcINICHjI6rlWSQMx36hU+sMQ==,iv:7f1Zei6aRzT81UBr1uvaX1WgzU6KC15Kx4Jme3fhqSM=,tag:9xBy9ehcGx8F5Pd7L1v3VA==,type:str]
    password: ENC[AES256_GCM,data:VvCzYnPUF/q4qOXUmbytKiknOTgQ35c30A+P/YagligkRZG5+5Y1nWMhyow9HHVqoJDui/13SsxeANhiE1k4aQ==,iv:RNJO4aX4I45nUse8VzVvEf6W15I6GtQZow8I1jpftHM=,tag:IA4w7QTofUyTc3ZM9Y13/Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:02Z'
    enc: CiUA4OM7eCf2Djyh1VKQevZ8qoMmmhxyZd6XfHUTAzbhseIi7q5oEkkAZoeZpjw08mDwY4hnfKV9kL3CVKpMvpBiynpp6MivVVxHr/3Yucv70ukR/Krxy7H3Wl2uXz/dwi6X45KQzW/o0NxPcCzMjJ/1
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:02Z'
  mac: ENC[AES256_GCM,data:75VLbAhRfcX+O37unpY/5kqDcosNExgxzGyV2uhQpKu5OJobdO4xHbXWy7AUZIrTfle8/9a7rAC2AtCGifsk2FzjfDnDvglh60rYnWLxMhTDwGPmSjwRyCx+Ad4Hp6G5FGGEVjjHaPY82vxR6lOk1I5TAaXMafI1WzXR8BIjq08=,iv://vSjd6Ql0cnWN85XixpzEMnDrHQOVnCIwg9GDQuknA=,tag:prX/nuWC3D8Q0k1572LTWg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
