prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:Tt8nMNficx1lexqmhUgvvPwUG0vxV9QshG6nKmcwjQkmO0R1Sopqc9ffOUI8sJPPoGl7GuG98Sw2mY3sLneXOg==,iv:Iz0DdapStV7+C2jctVhVk+6/YuiNv9qDznJRlAT4f9M=,tag:YTSt4B/ezkljKPksTtp6rQ==,type:str]
    password: ENC[AES256_GCM,data:UKYsroi1HO6eol0ubRBPyKWRbTJjGLN7mscbFwEdoQQ1vis+yxcFnF1ltqnej0vIBEqLYsNHJ1jA//N7eLFA5w==,iv:deKlJsGtHt81jqBNYRGK3BcxgIXhYybqB6+JD94Ve78=,tag:FPWjy5V9MUfMMkd0M11PcQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:pv5AkLsxABfLVQxAlO/3HRxIziA=,iv:4gC9kJhZawQujczInlmkWpZ9ZfN6Wg/PR2vUEAPZ/x0=,tag:7MT6oVeGVcBnPPF49MRP0Q==,type:str]
      client_secret: ENC[AES256_GCM,data:ugqPChhY/0ZNC1rqflIIYfVaTL4+UR2UahPM+zqNYQ/HOoH6ENvEsQ==,iv:9iOzXXsudwfNtXaWlEEIEPkBQK36K/UaruLwK1dn/c4=,tag:QydW0Aqp/2ud7wb+cFgdLA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:40:59Z'
    enc: CiUA4OM7eCWHyXzM1Q+ne0VDVWcRfohii8czwCGh/sE/XezIVoomEkkAZoeZprVdPcxsPUWACaIph4RAQLRBVIBXJOyhhMxvWBTX+kV8AAXqI6uElR/a/T1JYnjV1ijlWzDWnrURdr0T5g/vFH8UP59C
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:40:59Z'
  mac: ENC[AES256_GCM,data:pYTctTGROVrYhM2q2N4PnIw2EYiHOprL3h8fDlGwhYdhhFP3TT8kwayLvWRuVqBetSRQd1h0gPgbaSlqzxh+SxmqvBtSVvQloxy0GJHadtbFdPykGWgzn8TiSCvjUzAw51tzxKGH56fuzXk/OErqa7ElhxwV2FvKrgq7QJBGrsI=,iv:AzHK/KHaPPC1Gx85ZTL4362oSqOtPmwWfoAxpTQkX2s=,tag:23Ty9/mQE3DFB/MCXrJqqA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
