prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:CDmJqEavQP9PWDvaY3ojwV8BsqhYgH304iuDEHW3KLOVnRoUvryebswlWhip9z3jhW3kGCHIMGL1JOiRWCUVRu+0nBXLxFyfCOwWTiQxcbP+ulJ9yNe8ukEyiiJxvL4ie6nLmo953tjdaNMXRoRi9mke6U6zzJdSDqtLyV6VWRSeeJoof+7CADBK/EXHLGMRi4QMoVIh2TxNYpRy,iv:U2OXoBxYAcBySEsQVpB697Tj9QwWAJCWif+ACWnmpBY=,tag:B1BaM/hYw4LkSD8cckk3sQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:RoCyd9KJyUwn4AQzcI51JJAe9pQPpr1M5qhVHJfZYvClcSCk7mrOyJS5q8cZwu66XNOucxvPPZ3l/90VnlvmSQ==,iv:/H5AIevLiparEuPLn/NetvdqlbtL4Pjjk7Qjd3cEuks=,tag:X5/1HV6J7NAZxStHU0Fb4g==,type:str]
    password: ENC[AES256_GCM,data:XhRPRFGTjrsYu7fjqaIgk/hfmSFNgM8jmcRSBIPXZu9wjIkvthvkaqbtjazPaOIwecXk63AMh8251VAo/MiAUA==,iv:nn+pWN1RlqHciNzY2AvTAI9tH1Q7G/RMDWhExmed0ps=,tag:qQAf3CKjQn949KsFjMtFeg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:J1CRlvpYDWzSAKBxyzhO/bKm8+Q=,iv:c33cm5GHTKzYE69XW238Yrj/USFOfFGB7/pfXlZJnxY=,tag:Z4qYZbRRqPC4ChLg4FSwsA==,type:str]
      client_secret: ENC[AES256_GCM,data:O2hHcDLHmqzI+ZZCBSchn5Lecr7Q1Ug/fcgWwdV+Egy4cn3uP8nj4Q==,iv:PW2O7RYtWFgzuOCtn6IhcMIgGn5YVvnpRTs6bqE1ANs=,tag:1Nsv8dv8wYVwtQDzUkx9xA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:05Z'
    enc: CiUA4OM7eBUaDMfh6tkBJaALiyBMyR41OK1uhVBphh1fDtVwRlwEEkkAZoeZpiRlGX2f+eM4wrA1H/Xhnx4YEKQwwoabK5BSn3D9FzWH5PBCFkF8DCSRhWENekUlx40kkzCdlqwcUfJshhXK6Ea+6Jtd
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:05Z'
  mac: ENC[AES256_GCM,data:qLETlFnpIhAE9i84mlm9pDCO5AD0o+ZDo4DwTXs+TzmKnM4K71EOX+z2Hs1EgK/Ub/xyg5ceQ8UC+cwFLHiEQClMoQFGlGI3kRB9BFlo0gIWfh8tqWtoTESDue9n7UoBoKqAJ1pOJb4qCdiL5ilP5RD1GVmWfZToq65OhTYLpXs=,iv:y/A2JPaCua6/ZSjTsCo0qFsEIULNOIhxz0ekPrqODrU=,tag:YWalMdbW/O7mARw4JC5iHQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
