jupyterhub:
  ingress:
    hosts: [bmcc.cloudbank.2i2c.cloud]
    tls:
    - hosts: [bmcc.cloudbank.2i2c.cloud]
      secretName: https-auto-tls
  singleuser:
    defaultUrl: /lab
    memory:
      guarantee: 512M
      limit: 1G
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/workshop-user-image
      tag: 60943b1dc997
  custom:
    2i2c:
      add_staff_user_ids_of_type: google
      add_staff_user_ids_to_admin_users: true
    homepage:
      templateVars:
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        org:
          logo_url: https://s3.amazonaws.com/files.commons.gc.cuny.edu/wp-content/blogs.dir/9457/files/2021/01/bmcc-logo-two-line-RGB-final-1024x663.png
          name: Borough of Manhattan Community College, CUNY
          url: https://www.bmcc.cuny.edu/
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        oauth_callback_url: https://bmcc.cloudbank.2i2c.cloud/hub/oauth_callback
        allowed_idps:
          http://login.microsoftonline.com/common/oauth2/v2.0/authorize:
            default: true
            username_derivation:
              username_claim: email
            allowed_domains:
            - bmcc.cuny.edu
            - stu.bmcc.cuny.edu
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: email
      Authenticator:
        admin_users:
        - sean.smorris@berkeley.edu
        - ericvd@berkeley.edu
        - vznamenskiy@bmcc.cuny.edu
jupyterhub-home-nfs:
  gke:
    volumeId: projects/cb-1003-1696/zones/us-central1-b/disks/hub-nfs-homedirs-bmcc
nfs:
  pv:
    serverIP: storage-quota-home-nfs.bmcc.svc.cluster.local
