name: cloudbank
image_repo: "quay.io/2i2c/2i2c-hubs-image"
provider: gcp
gcp:
  key: enc-deployer-credentials.secret.json
  project: cb-1003-1696
  cluster: cb-cluster
  zone: us-central1-b
support:
  helm_chart_values_files:
    - support.values.yaml
    - enc-support.secret.yaml
hubs:
  - name: spelman
    display_name: "Spelman College"
    domain: spelman.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - spelman.values.yaml
  - name: ccsf
    display_name: "City College SF"
    domain: ccsf.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - ccsf.values.yaml
  - name: elcamino
    display_name: "El Camino College"
    domain: elcamino.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - elcamino.values.yaml
  - name: howard
    display_name: "Howard University"
    domain: howard.cloudbank.2i2c.cloud
    domain_override_file: enc-howard.domain-override.secret.yaml
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - howard.values.yaml
  - name: skyline
    display_name: "Skyline College"
    domain: skyline.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - skyline.values.yaml
  - name: demo
    display_name: "Cloudbank demo"
    domain: demo.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: password
      password:
        database_name: database-demo
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - demo.values.yaml
  - name: lassen
    display_name: "Lassen College"
    domain: lassen.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - lassen.values.yaml
  - name: clovis
    display_name: "Clovis College"
    domain: clovis.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - clovis.values.yaml
  - name: sbcc
    display_name: "Santa Barbara City College"
    domain: sbcc.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - sbcc.values.yaml
  - name: mills
    display_name: "Mills College"
    domain: datahub.mills.edu
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - mills.values.yaml
  - name: palomar
    display_name: "Palomar Community College"
    domain: palomar.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - palomar.values.yaml
  - name: sjcc
    display_name: "San Jose Community College"
    domain: sjcc.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - sjcc.values.yaml
  - name: avc
    display_name: "Antelope Valley College"
    domain: avc.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: google-oauth2
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - avc.values.yaml
  - name: csu
    display_name: "California State University"
    domain: csu.cloudbank.2i2c.cloud
    helm_chart: basehub
    auth0:
      # connection update? Also ensure the basehub Helm chart is provided a
      # matching value for jupyterhub.custom.2i2c.add_staff_user_ids_of_type!
      connection: password
      password:
        database_name: database-csu
    helm_chart_values_files:
      # The order in which you list files here is the order the will be passed
      # to the helm upgrade command in, and that has meaning. Please check
      # that you intend for these files to be applied in this order.
      - csu.values.yaml
