nfs:
  enabled: true
  shareCreator:
    enabled: false
  pv:
    enabled: true
    mountOptions:
    - soft
    - noatime
    # MUST HAVE TRAILING SLASH
jupyterhub:
  singleuser:
    cpu:
      # Each node has about 4 CPUs total, and if we limit users to no more than
      # 2, no single user can take down a full node by themselves. We have to
      # set the guarantee to *something*, otherwise it is set to be equal
      # to the limit! We don't explicitly set a guarantee, because there is
      # a guarantee of 0.05 set in basehub/values.yaml
      limit: 2
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image
      tag: 6d61d3c15d47
    nodeSelector:
      # Put everything on the most appropriate instance type for these users
      node.kubernetes.io/instance-type: n2-highmem-4
jupyterhub-home-nfs:
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 5 # in GiB
