jupyterhub:
  ingress:
    hosts: [csm.cloudbank.2i2c.cloud]
    tls:
    - hosts: [csm.cloudbank.2i2c.cloud]
      secretName: https-auto-tls
  singleuser:
    memory:
      # Increased to help deal with possible kernel restarts
      # https://2i2c.freshdesk.com/a/tickets/567
      guarantee: 384M
      limit: 1.5G
    defaultUrl: /lab
    image:
      name: us-central1-docker.pkg.dev/cal-icor-hubs/user-images/base-user-image
      tag: 79e7ee67211e
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: true
      add_staff_user_ids_of_type: google
    homepage:
      templateVars:
        org:
          name: College of San Mateo
          logo_url: https://collegeofsanmateo.edu/marketing/images/logos/CSM_Monogram_process_blue.jpg
          url: https://collegeofsanmateo.edu/
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        oauth_callback_url: https://csm.cloudbank.2i2c.cloud/hub/oauth_callback
        allowed_idps:
          http://google.com/accounts/o8/id:
            default: true
            username_derivation:
              username_claim: email
            allowed_domains:
            - my.smccd.edu
            - smccd.edu
      Authenticator:
        admin_users:
        - ericvd@berkeley.edu
        - k_usovich@berkeley.edu
        - sean.smorris@berkeley.edu
        - pachecoh@smccd.edu
        - hellenpacheco@my.smccd.edu
    extraFiles:
      configurator-schema-default:
        data:
          properties:
            Spawner.default_url:
              type: string
              title: Default User Interface
              enum:
              - /tree
              - /lab
              - /retro
              default: /lab
              enumMetadata:
                interfaces:
                - value: /tree
                  title: Classic Notebook
                  description: The original single-document interface for creating Jupyter Notebooks.
                - value: /lab
                  title: JupyterLab
                  description: A Powerful next generation notebook interface
                - value: /retro
                  title: RetroLab
                  description: A JupyterLab distribution with a retro look and feel, more similar to the classic Jupyter notebook.
