jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:PI6yjbL3olWLlq26koCg6KABc+ybCCGy+pFE2Il98tf3xPU9HaCoZH1dKt7SD1NKA4R8,iv:kA/EGMlmkT1WqSqOy+2Xd3JZ+Sq1PZ7SWuCX9tZRxGg=,tag:xItpD8XkXb6xpE46N6ulaQ==,type:str]
        client_secret: ENC[AES256_GCM,data:2wL5CGzri078gTbAM9Hr13gVK9HJ7k4aRjHECB1Pzx1VoWjnCoPdjY4DJoj8dygNuWdnaqnWyVCnkRvbB8uaGOfS0CxidqW6Ss613ImzHTbXp+e7mZ4=,iv:DfnyJUC2+yvSQ+YWUdTyTz91LYgvSpxLgDUSlObGTOE=,tag:dSWrZQvBC7ZLRAIdKH1F/Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-10-05T00:31:30Z'
    enc: CiUA4OM7eNtG1cNIv4QB2VH+JKlAqe1Ov+Ap54lkXgvDCpUCh+kFEkkAq2nhVYtYZdZ1IuUmDQqdgK0ayXaFp6C11QLcZPGd3Gunnimn+wKHgWfXpVu/g2Y1SWk4OUC4XGzKSimRw0fojqk8628chIjL
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2023-10-05T00:31:31Z'
  mac: ENC[AES256_GCM,data:vniIZBRVrriTVZ17PTdIPoTpJRlxChLBcBA8Sg8okwcvZ/JGsaCF56GYYvdDg+V8jmQodQP93bWP1Cje3AsI6tDKREJmeZriy18zWl1I7R+XHqqE3wID1tVo+e902PeN/Kz0IjbxZuvBkEB/2Fbl+pSiu8zqF/DAOFQaylbdpd4=,iv:JymaZDho32gpLREJwWFdMYSOCKqk15QEUsO1heu/vKo=,tag:0C3L9TAzY+rmBQXdXbAizA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.1
