jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:Eat+qDzW81GuPTooTgG8eTW190zLSc3bIojlvs3uT/YZh6amMeIcDyLEx/7oWhGQAMxm,iv:t1ZU0sKqqO4OdlSpM5K/o40yZA47BB9MCm67HDWGHS8=,tag:EuuQGxiBIUeobgvuLGbvjQ==,type:str]
                client_secret: ENC[AES256_GCM,data:bECQMBE9tsXZaH/aWwDLmUY4Grm35O6oWELVmSAH8a343Mt2RGvmlifOMMQXaTF7KjpCJZDRN0QQkPlnGwOn0/Nlp/ikh1fyeaJ4+G9Cpt82VXODIXk=,iv:76uDDBcgrnZqHea+DtPJ/XrKaj2P5ptLFhmgczMRaYg=,tag:fqSQ5JJEFiLxHyvHAgznTg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-01-28T00:57:35Z"
          enc: CiUA4OM7eH7QXG4ocIT/LLgUtPfhfVu9bBebOzy7ggJUH3HT4492EkkAZoeZpowRK2vmHoyXDxmPjOAa206qCKlWtDSsMz98hnkTtbAafcABCv6igAQYhm7Ohd0m67M5cZUK0tb25uJ5MY3MJ0bfUeKG
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-28T00:57:36Z"
    mac: ENC[AES256_GCM,data:aeDKgCy8S/ZuZXjK+T32tao9I8AYDvBmkRAsMhgagrN0+EwWQ/3bXxYWWLvbEdUb02zpm/O8HwRRQBvV974Tb7NI8YZWCVur9R7f6WF3lj0FRihaQyeC4MhzkqTe6NihosMCzFBuqD/WLNt+rbVMjeBWEpM7KJg973ixN5qXr9Q=,iv:cJtAuJDHDf9xozSEWBdVYil7nJEUkP//mv4C+CMTOdw=,tag:xkchm8D5114wE/wsmZxZVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
