jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:wA+Dtkvl3/GABUUBEMfkI5iQ5y/yrILuiEBPm1Qe21YFYRxd4OnkOZF5GWluMNwHkoLL,iv:osJHkREei4DujzZEwMqt5yujw9KePz14VWn82faiPM4=,tag:6NCnNggKV6GKJ4ltVM3/3w==,type:str]
        client_secret: ENC[AES256_GCM,data:ME/h4Ni5kLglnQsW442TMiDXLr/GTOHoKMwLPca9Hg4sAId4nrl/T1hh8NOyuLc0m5msjg7GJ568m0tu9qzcvQsaIUICKePsO6ihSZWAj53j/PRX4A4=,iv:4e8+TzUCes1V0hUlFpYtasS1vg50MjML2JEyK3+Suzw=,tag:CnJH3ZkE3HK8qr33+JCndQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-27T03:57:40Z'
    enc: CiUA4OM7eF5uBfjRAcFZip9xNo/Oaasm3uyhUtsQGKyGZVyvVkgDEkkAZoeZppRKdBiFNJ3j4BzNfZYsgWVTDkXzrL8I+d+KvNmnCr6uZvxNRlGoTdd/a23hZ8zAU0ZPbr38nOeK1qJnLDpNU9OPf2qC
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-27T03:57:41Z'
  mac: ENC[AES256_GCM,data:nDIHtFhVCPdSRRz9MPKJZPy5SZ5M7RBeugfG+LHd5mb47n/BeSviZKNQxlNX/6fUVkfS6IAHRm/q7tk6jXHWpDlczt3ieAYlaLy6npcdk9Q/DMDDQHvtUZd4Qgd/N+9IU+LWXLBYvxlHgG0czCFt7oMNWckaSniDSS974XVX0rU=,iv:nM9nCSwKf0dbZbOKUMZHsNYWXevAXJ8AWz214JeJC/A=,tag:QDlWlc4CYUNJJ0gqX3AUlQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
