jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:HMOYiDYIC38pTVM4xY4ENfMQUyOBTt5rg6oH9+HY4A/61xKB2v211qKvsjgetF8V2W8t,iv:oKzB+ft1nk+0R1IZv8/Hw2MU4Q65SBNQ+3Bk8kpguoE=,tag:0JN1FYnI3pgJkarb8gRY8Q==,type:str]
        client_secret: ENC[AES256_GCM,data:l8SjEught1NfkBrUHJIpXRG/kynKqu/26gRGGQjvCq6iQsLPSXlN6BUIbMw4KeppYEilz1tefSSPqV8ac16/70xYgd7jX4cDjQvP2WCVcXT68ExitHc=,iv:wN2/9j6Wf5ftl9k2WBoTv5Z3XfO5RxAt09jh9CDYV3k=,tag:hXvLPe0NRwL44EZzvDc6Eg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-15T23:20:25Z'
    enc: CiUA4OM7eBNzJfh6vkpGmlsC6Qo5qRKjJd94tDTIFDuIesnVl+L/EkkAZoeZpiGpnMnXbVEL6qCqPzrfLmg6xWf8001wzfLYpjN+jcAOXx6JoNxqCtQLGB90+xN950oQ9uoQ8Dfea8cnn30VNKl9/h8m
  lastmodified: '2026-01-15T23:20:26Z'
  mac: ENC[AES256_GCM,data:yFEKs9HOkQ0lepsdPOzPmGWRwF0xcOOtQ5WUViW3J0NYgupcO2VzylfCPZJj6eoQO9VY7lVIDbVIoO/Iem4B+knFRuxHMU1E+S2J049ekrhFOHrFhmR8YMeXjWUMOhuDb2UulbgBNvkvmePISOrix4glhDOtYm6Cer8UcyR4gYY=,iv:tuSfkWnEh/nJEcPc0G7LMlaqSP46JVZ9LMl47FSyWJw=,tag:EbxDkk1elHRyH03+aWas0g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
