jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:w/CSfJA1ikCl4We4FufZ/2/cy3+bKKpZujzuaQvcYYYC6C7015Lb9BkAzf67emgwvrML,iv:ZyEBouVzwUgbnuap3HGi78DRS+QPDIk0clmRGGQLHZE=,tag:qYkJ8lucP2cvZ+SCxJV93g==,type:str]
                client_secret: ENC[AES256_GCM,data:jFQ7DsVDGcHRAVIPz+wnyCFguGNGbfGHD01Pp00RmWwPYvu1S9fxpzl3CVTVy9aZYtk7i6SrZMDBxbvuCxhTb65akPwpKJoLChQ8WyRcVVzM260f0Gg=,iv:FacWTMoYRDInan1F5wuR+/Fz8CHmuv+Qa5HeBjKWqN4=,tag:HUPXkOCr4k+pH1L5cltSGQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-01-27T02:08:06Z"
          enc: CiUA4OM7eCySxMj80PaZE6l4p2MioYfYniX8YLttmq4Nu2OvFzCFEkkAZoeZplkbDe4lg0R4hNHGHD30nMhz7ZKai9eA2chtxBL14PlECy8dd6PDP+22zQmIywdPVDMo+o0/0w8vgwDVN0q0rvpt9dHr
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-27T02:08:06Z"
    mac: ENC[AES256_GCM,data:k6WfC8VkRSJKsASjp3iVVsexpdXoS9D5Rviflr/hOSzQd+2qj78BnYpWCk6Jq7EkhAvMdbTAQMxCo1oMFU9iEhhmGNYO+k8agh3BUX59dQtyuciAAHmVz0W5twdMVzIT3QK+LE8PkfcGOBtpiVRLt85AcdyO6f7Hn0umVud8qE8=,iv:bTp1h9NnCvFiGTkt/2hb+NfPKa2eT3zn2zG83g4eKBI=,tag:7dxdvONrWG3jRGXMJhfszg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
