jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:OWa0OcmuvIjB/1V2aGKyv70EZRjth4EEmk+vPSlCFBbC+xbqWsOlfrMzha/QYLf8guze,iv:YC9mUs1AagfrzwWSxtG6bQSvaixDf5XUVULNQLRUKSQ=,tag:vtTXp9HLK6GdlO18nWSHEQ==,type:str]
        client_secret: ENC[AES256_GCM,data:GavGP7D6fMKPyfquB+vnJggzmaARqmsnvWtYbQL9clSUi4vOPKCXbybH9vXWZQtL+to5lX530LhGUD/By1dElBRlz2+5GL40HDYM9p2W8UtNJoxVUtc=,iv:jsLAsvMAEwS+MRqOfnHZRV2UHXsTal4seKdx/DbnGsc=,tag:E5V/mB28yEG7P9v/c/6Uog==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-28T01:10:00Z'
    enc: CiUA4OM7eNJBk8DAejtzHVUEAw5AKD1TesYZSDCJve2BJ0uzzUb3EkkAZoeZpjOhKngS3gzgooid+fk9Lr8KcvkXrxx9+Q6ZWforc2cpwJdEOZV7tqF2BGfcr2vUI1P77/EeG+cZSDGpOUibngAjz8IG
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-28T01:10:00Z'
  mac: ENC[AES256_GCM,data:u5/eNmQ278DRJ0rBhorP5RZgM95kkf4TmIkBItDkNLJ2HG46Ve4jD0EradVMgoXdNHNcx3jkrAwXEwG1nnr+aNRTAUrsyxrvlX/WgBy97mFMkJHcc1g+CM8ZTU0b2sTrteYwWBmuQ20P0eHVMQfznCLxXSYXUsxFOnmCw6FTa2k=,iv:V9IYnKJTaNBeNpnMrF2zHMvRvDGvJtdiY2ziW318Fb4=,tag:PnjYSBpCMi958uvVnGLnpA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
