jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Gq/3j+w7SuP/L50z2AgdjKfFAFF5zinW2t1Of34+tVp0JvYAzzejCHuSKc1YLwrgMVZX,iv:no9tf9Q412yHx6Unc4MxnzTqQOTwxkcL9ui1DdSYM/s=,tag:jH9NScHnYgtnyJExY0doSg==,type:str]
        client_secret: ENC[AES256_GCM,data:kqxdjAR05EC/uBte8X4ZpGKQdYwG7CZ4MkkOTOGjWUD6zX12f+CjHnfZh7K240vvtxsbgOcEEdkBSH+SkrOy4UjfFChyjCG3WhOuXDaSUrcgVVGvPzg=,iv:mtpot7t6c+ghzohsS1bWxqqVl319sxlHI+limrx/woA=,tag:58pjPn85noBGQyBBS4J4ZA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-22T00:51:08Z'
    enc: CiUA4OM7ePkrdrMxVk/xgMmF450Od9MF2a1bC83gDS3a838cJ59EEkkAZoeZpgnfaw7sjz0KdG2psRlw1S+Q72ezCOt49LOtL3tzxMQCyhz0kvMf31zZ1tLVxwPBO+j3buI6Ia3ZhUS0C/txkokyJrB9
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-22T00:51:09Z'
  mac: ENC[AES256_GCM,data:pz2GHQNHajyQxGS7Hghr28MyVxzsRHqZFAY6jKQjjhOoTyzZxq8FlXdIjHwRltbdb0FG5KdHnJIBv8WMZtCXsQmOZu+v/CqD7hUoXdZ4Ub6eigKNaK4gNyi7VHIbhTmTPJQFcRf1d6bcy1GKdt96VtTNOticTsajpWr68GuBpiw=,iv:8sczbyglVB+6y8rupaVLMkMH8Jz8Z6+DJE+Miw42jAQ=,tag:q5YZ69k1u2Rp3M9gzW4h9A==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
