jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:5S7rW+L04Y5GU4TsapYEkjMktO7np36SuO24DU29yUaKp/gzN5NOPHfr8nGHKSx87us3,iv:l/cFhOxCNWsph5MTaobYPtDXERfbUqoO/8VoFNm8v5o=,tag:atyp/wfEl3ERnHj4doQdpQ==,type:str]
                client_secret: ENC[AES256_GCM,data:oFwBvxQ9xbB8jivxj/9r06Y/VHDmxS0YaCtIOSpj6yyHa3Y3vGnRkZeKqDI5hiKvmFx/E+KrDcfvH/KFwO8U7m/ShlvNK6ASxoBn9VNzwSH0WeMcWDc=,iv:mczeeIla4zmPPzDQpqTeBPJ6IK15CX3jnOSLAvJTWcQ=,tag:NIQMbrKLhAZQpkUpxa8sLA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2025-11-08T17:47:27Z"
          enc: CiUA4OM7eEtoOr9et777HBOKUlWq4box1yqdKkHdWqQxckbWmifZEkkAZoeZpoA1JkTK0dH3ei5EyX/eeuLdtg3oErSSu0WSMTfUMZYd+P+1UA4Ccz9RCKd2p6Ym6N4HDdYyXNYfWTPee0oKekWmwzB3
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-08T17:47:27Z"
    mac: ENC[AES256_GCM,data:iYxxKuSBhRBUlXg4uGDJYH2IkvF+fY8kVaNJqSbqM2jMWiefYiAZ9PXTiMXaPIluW0Gx422iMIXkBDJChf/y41/Qo4NMb+zWGIlNiWoRnrVpWB0DT5VOp5fMGPOGTGzACHi4NT0L/h4tIVl7kT49ShRnBeNhvF/WLYHBBqg7Khw=,iv:f/mMyMhlYo+5Jc5c+3GMacUoz445G/I84c7C76g4xxM=,tag:063WYbmoIrktwRjgnXLtDQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
