jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:WuNVaJ5zZsn8Po0aXofzE+pj54rXbdPAgSxsFVY9H+tc2MAtYvok7WScuvdTtw6Uw1wh,iv:PrYGwP5C4DUDNCtsf9efSSjQSA7SLFVvGlkYc4nN9/k=,tag:SegWAOErQlTFkcwz399hCg==,type:str]
        client_secret: ENC[AES256_GCM,data:bOhK0/qiPlgou8uCMWbq0rPvwk9Qlp5NZkFiGia2Ha9OyeT36VXU1idEBw06BbPW97By58C3vKDYjp/yfDKbuDytUVs8HDP42t3lO1OpQagVwZO/uHI=,iv:bz6WDXJpC1akZlCZ69W0ZRD++fVoXcwyEWCxQLY+jac=,tag:RxhhHpa2Ngw4gH20TgrR1w==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2022-05-29T21:38:16Z'
    enc: CiQA4OM7eHKhDsPulyQ9SLZLvFXokkaIWSHnns0N8mi4YvG2TBMSSQBq6cPrChjTHue9/3D/gdvymUI/TZnExe1t97YWXhy+aFl2j6Ks/AdcE7kaFkVkfv5mR6ih/OTBcD31c4RaOEfMYkEt3c4BXl4=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-05-29T21:38:17Z'
  mac: ENC[AES256_GCM,data:AjqTdZYbMmSwyUV8hskTCGsg/Cg9YgH8CVJriIVuuyJlIzAa0s2mVILe0j1WmvDYBJhtbJZrkmV73bwEEZl91M/r7fRx6lciR8xPKiULLjTeWtoksd388/bfb8FeiUwgchxMW6tbwqURVdCf0EMXDkil8EMK7dWoa4K3zUc9/cs=,iv:c6ZdLyArS2st/dWhwU7/jy/pPrNmC2u+SB+6u4Rnem0=,tag:oCQbT0Ip+qo8KawexNM6TQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.1
