jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:06UQWY5Vye3+U6ijRElh4RHcXHMUGBGhFd0nuHt5f/diGlFI7XOn4AJUuI/Ly8HwFQxE,iv:x49bcD94Zu5N/uAukDaryaIuhh2PwXePoToL8aizGfI=,tag:o7ugKfmpdLNge4ibMRbV3Q==,type:str]
        client_secret: ENC[AES256_GCM,data:k5sMMCophhHCN/7WxtnxBfKrsSCE68/ex+B1505/S3qEepsAZBMSB+OBrr8GJ+wmixKgWyHhLFi0HAjqlvdt939N8mC4XeYiDwspBqIEoviulMhfloQ=,iv:FRJJ6ET+3NIaP+7RPHNiEB44livhNojtjTFFu+sjUkg=,tag:vtzCsN4SsQV1cFjKy6mp2g==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-02-24T23:15:32Z'
    enc: CiUA4OM7eKMFeqref5prJvT9A3J/dcZ5FT6wvGSIjrWu1tJRwTRvEkkAPHlbmYKueK1M3K7leFsP9sm5iQDvRTyXW/EDEYXMCXn4GtAAhV69wPAsXapBUMH6N5mTa/mazOAExldYiNK5VWhmYgyjiKXB
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-02-24T23:15:33Z'
  mac: ENC[AES256_GCM,data:pXlKB5vQvbWmC8Paldkfo2MuVVVpvqH7QH82WcxHd+Va7LFtvmXmk423a/x9PmWFZpo0O0EY5YJsLZbi3AtX6gwarw+Ptiiy8Iu+17bEF83X4McBPZyFGC4jPONsb57Cd5BqSnUCKtrKIVJXMNC5ID5BZ20eq4Xq55iQPzccMgY=,iv:8GjSEACaIp8J57EgEWv3GrK/7vBgA4yxCee4DCeEBKU=,tag:1IN4enpEVjXa1l7h11eLyA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
