jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:2VASmAMLTC/vBZ8gvcnYiuXu8rAl0V6K6yhRYPJWH2C/MFObrvMCLkpm/mJvR6hAmPpS,iv:Q+5U3Y6V42ateG5Q5WeJD9ilSIdhOeuNt/8E0L9R2+M=,tag:vkAg5+sSmGybUCwosNi2mg==,type:str]
        client_secret: ENC[AES256_GCM,data:CO7koDPXljbyCLu2HTvnroEODdItwz8WbJ+E9f8ErjbX70baVxsuVgDC5c8VPn1E3U5HpLW3f7MqBJcdm10zKGXMxZtVQKXqZ7Z2aCdemI7WEgcqJG4=,iv:pyp4eOWDIPLhU7iliuRqC8eZgb7I5tj7+VkKT/H8pZU=,tag:UPeoAw7pKAjcph0oDV4Rkw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-08-18T23:32:38Z'
    enc: CiUA4OM7eBvguDtxaxszVnQ0/+UN8PsdRq97lIXrwaFGCwEDFHpkEkkAq2nhVa28w6Zw8tEI/1yZdgVPMAdTQpGc8JmxYd+/yj5pCdJhc4zDP01vMOuGISn5n/sJqi9wGwQq9XtDgXGwM8a4iXYmdzUz
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2023-08-18T23:32:39Z'
  mac: ENC[AES256_GCM,data:bH20Pu40AkyHor4c3smJXMm+CLxzr+6P33PBy+5ytEmi5MkJ99cSMAy5SYNQOuFtEAvutxSAdpk8qxBFXqgPJe84eWbzsYhNuk2qvdUbXEw2/DeP4CGlAHKxc7PvlehuvOmyA577gHlpKuovEI4Jlps9bnCXqVf5yj14IFjgSA4=,iv:cp/ChsAkWpBuzgVtvs2/J0mVkCN8Wzw5FxQObvMxZZ8=,tag:WxTeFSuLtYob36yzbp8CQQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.1
