jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:7sLluvdd19N0t8BkRuWH9BitX2Gqix2g+5KsCbcSgIkVtT6eax3Hhnw7/EGwGFEd2AYU,iv:KVkpmpoCBbPJsQjHdA20As9QKOcbQLkGa2jGY1F2hHY=,tag:fdbrzzwq5/khuFNgJQcxCw==,type:str]
                client_secret: ENC[AES256_GCM,data:xmDWrJHG/qJvtGg35aT3GhhB2l55F7u4BfI9fJ61hg1O5n7dpw+4LTpvuIwlfksZl1NR00YbJy738HAIwtlNJv/UwQPKu4wO3TT2/APN+uqbwm/DJLQ=,iv:hg3R5JDZ/UP/B32OsGFjK74cWtT4O6QOMbDRNxr98qw=,tag:GhwhBJChbbuRHbRXbuTc9A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2025-11-08T17:29:22Z"
          enc: CiUA4OM7ePbxWb8EN0b6j04syVAkkrAfR+uAFd8TvF+fvc2+100VEkkAZoeZpkbTDO5Ega1sNX+c18CI9tocv2Tw/3zwicjBuGrCeOhUt4DwM1mh6iDTVDPU9d5mzDuZpvKN4nhW1nxgRe3zKedCgiLe
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-08T17:29:23Z"
    mac: ENC[AES256_GCM,data:chWIwZBaUcA1HP2sWyAzn4oXfzrHzqXlJCV4+0UFSLpL1G/p7kktKT0Q02AO6z32O/wqv8TsUh2WDwOansjIG8molMKE5kHKuO1SxNo+M0rH8o4iBAl4mNymlHILNbAzZEhFsfqUJVr6doTwZ4yHSEX5gf3RGhYQJODjpHnIcU8=,iv:a/SK8TFl2Da+Qo36exQ9Uk8yuCWjkH9MbUCb5ixW27c=,tag:H+S9Xed2LtNE/mbni53VHQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
