jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:GzWMjhi4scBHXASuShv9nrrvcSc=,iv:kBB/faURJwXsdBV8deNwSKFJbd89HhtccVV0kdQq/OU=,tag:Xf07zkYDFXsRbR+GciRg/g==,type:str]
        client_secret: ENC[AES256_GCM,data:AhlwtPR2O88YoHU7vRVA1jXPzUwwtlf2MKTWRTeaxnyHkXTobetYqA==,iv:UB8sHtTrlmz07KnBv8nmsY+CQl/Z7K0YzQjjBzO7M88=,tag:B31T2bGe7Z8InoBNc4bM/Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-08-29T22:34:14Z'
    enc: CiUA4OM7eCXh837viYJvH7v2bILUUgGMZsMA4QOCg0u+NOdaw8jVEkkAq2nhVXESSJldot8dXekZvrCSv5NkeavnQQuP5jUH8+/WXWfFYii1QZJEd0LlDXbmQydV/82Mo0PzZ5lFiyirc33MQ3jisQlo
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2023-08-29T22:34:15Z'
  mac: ENC[AES256_GCM,data:2b4dAfUIupx2p6iDGjIheABJrnCfaUC1WSQ9kHBoGlmbe7ckZ0ILgE3Upj2tgRnetO9RdC5KHx66ILUc0QcqEBy2Nk4AnOY0Yhufh//8tWr/qJLSei/IvmfgJJprj+ufYQzBOuIjHdwZH+NKVE3RFP9r4R8n7tegPtZcPfwMpro=,iv:39/Rr5TvqTafM0ra3h4Mn4uiN+2GwOp8xAn2hDQwRgE=,tag:ADyw+ptW6JXYl89YhK62aQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.1
