jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:uNByDUFljyw2dAJq8eZRNNlrPLkHFt9956q54OShRhE82aeSSUkM9YSVv+5LY7F/qBxE,iv:DaSMV0OBQ1vrLSMpyFCmg/sXqE844qlEVihea1k+LNQ=,tag:3sA0Jk4dosIGp16SwMNhGw==,type:str]
                client_secret: ENC[AES256_GCM,data:yMCxPV1hGUzt0ZzO8b6YEhYsRCjJ2MVpR24qCDEB2NzRFujNJNswhoJNZPBO9SZrYwgLwi1B3mSBCNDUsV40U6QiqqQqEy2jQNZXCcHUsMo0y3ATnyg=,iv:LHbEGmNRcY+OhGhBKOQ7smotGYH51nPxaAcfRtaO/NE=,tag:b+WR+QXguJRgSHIPl3Ylbw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-02-18T22:12:55Z"
          enc: CiUA4OM7eFT4O3Ud9XCX+51iG/Klv9dEcgT/zyL+XaRumV1d2pyREkkAPHlbmZamo1RsriDlscYNhh7SB6EkkgFtyANtn1YfngLBKN0jlaiYypjyIHqyAHmEVesP6AmGNNdV+ebAh1lhLkz6rch6OxCU
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-18T22:12:55Z"
    mac: ENC[AES256_GCM,data:VhpK5Ieo9efR8uvcGgIV3t8zr2W6/NP6Bl2QOgj2ecVzlPBR1cuYOsMakb4yHWO/5nYF4nzdJqmg/HhOFoc4yv325PV48Rvm5X75dF7yTyAE9ybVvNGkQvuPHFYTeVNS9hcY4G3GbWs8G9WYzqjupYsRw3OfCImL8YoxLHkDEuo=,iv:IPfPNBySymY/eYNRaWf9ISreXDDCl9LPm0a7c5+Bqyc=,tag:imUZWMLN/MZlefhzO+5OKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
