jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:LERPyL06PoGgHtoSWGE1Nm/AtfI=,iv:f1uOVLlkZMlKdwcmM154ITgqumFhrzCRXbyS9e+YPck=,tag:cvdJg8yUKJ6QsUX5BIIQnQ==,type:str]
        client_secret: ENC[AES256_GCM,data:xKl58leLm8vzjnQ55z+fVBJ0GD4QEtNt9HttNsNfQErrt5MfriDZYw==,iv:AwOGeWsznhvE0iXIXh+ipNVXZpmEL2IwSBlo2Hcf7TQ=,tag:r6fOasZQdZNLgn6KeiN88A==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-02-05T21:27:21Z'
    enc: CiUA4OM7ePWBVGNLdEkuVPD1bQGjni8fycRj9sQjB93TTizcIzeyEkkAPHlbmWTOLNI8v5Rg6i3K9F2cS0vXzN4Qg/FWJoQ4a0WBuBhb+KFN0vZV3+BEdY7C9m650Oi2997o+PL35MMyxLOxwS5vaYfG
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-02-05T21:27:22Z'
  mac: ENC[AES256_GCM,data:Zh7h/4ItqTu2L/9Scdrf9CQyZ2VGuH49Xjcv3UB4rTmARmxkWPNTd0UdhYlZR2HpDhDQA90nX9APUcSfzZHHLVqO3riL5nYBZZYg649f96gyVt7vNu46lfNA/d0HtPv1VxsA+50H1+PfK30b+54t4wBMtchMdE0VlR4HfE0FJC8=,iv:BNe3v++JHuojWRrTIAhQkph2qg1M0C5qDyt+e0nqMFw=,tag:9EeWoTpAUPjb0yoypfevwQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
