jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:U5pPy0yt2iWT8ifX3ds8ZKhM3rcVx3QbMtuKZt3KlvWUXICWAdTNMzt6eHAUqmWfTNag,iv:FAd9yBqAzUfSmhip96uAPivy3EFEDUl4F57xaQC6rkE=,tag:QTmWlvR8ljTa2GdBUsSjUA==,type:str]
        client_secret: ENC[AES256_GCM,data:KaC2695gWoiXwNh1fIJjC4Se1fjTBx5BufZwQx6JtiVYkU59hbYfdP3NxYHGwfn4NkmEHh/q2iZwR9SGAJ1idHt7sKpCk3bUEKV594PGwNdhSR8RStQ=,iv:GlVEwKcOFHbzbMjHbZ/mQzYTTezh512J0a8NLP1avHM=,tag:S/WxwC7tp5PexrsRmJwUtw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2022-06-30T21:42:52Z'
    enc: CiQA4OM7eCzoC4vPS6Q8/RPxZ4XjpPaWRRA41PYj5kbUXHeYtogSSQBq6cPrnUan9oNVvo6lyAF+Q6zFg1C6208pIFGKOvdvkCr5Y+UQ7XDhPwBDDS8xiJnIxt9s7G5a300h9rLDSKOuE4UxN7BChrU=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-06-30T21:42:52Z'
  mac: ENC[AES256_GCM,data:JSZB7IWuFdfSEQki4oKPwJZvfpBgWuBDTEtMs0m7KkXgP28jIWrmQ2Wyd3UtEJOcgCwmxAMe9LA15N8w2mq3GyPT/uSevS3tREp5K9lF6CXRDT5hkbNw6voaRDco1jMK/cEm7SbsibGaw/OFNzpa3Pe4SnfmElZ6zLwEOXbvvEQ=,iv:S0oE61OOKliQBgCuvEjQ6YqohxJ0NBUDtTIhiCQys/4=,tag:+Z9p9k9UyKweTBvH4Mm9HA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.1
