jupyterhub:
    hub:
        config:
            CILogonOAuthenticator:
                client_id: ENC[AES256_GCM,data:YtT0e+MHzHTYrTw+UH1SU/LLQyyspjeWLnfqMhb+MYR3gkUy8c3WteCxRWlVNmx1LWY=,iv:m54lMCRZxYEeJeMdlsUnUFf+rZau1eH0UkYPbk8IGZo=,tag:hWqDAnMSx9RQns2Nj4AfdA==,type:str]
                client_secret: ENC[AES256_GCM,data:p4mktmRyIJDeY2TRUi/8MzyQMqobLJJoot2Z6+ys0OobmVbeID6EGvImipQXTKtmHZAUBAXOx1U9q8Imo0jouNX3oUrgl3yZKOg5DmjpOt1h2HXvnBI=,iv:14GIjrrt79XyNAu4CM6aZk41PMSAnp97ZHl/yBlxYK0=,tag:9n8vWiWPPjmre0xIxtIo2g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
          created_at: "2026-01-08T00:04:51Z"
          enc: CiUA4OM7eGvCrNSnmU0NdQ2qpofOzezxxFx2O5uFeCSRUsP69xVmEkkAZoeZpppa4CGoR+k2LTkNubFpCy1n3EQ3Ork9K5VfDNSf+5faWGZEb7eDCneutayrCiZtH5GQps0hP0QTUgHU60dnIiM7pweA
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-08T00:04:52Z"
    mac: ENC[AES256_GCM,data:qMDw0n/ZrD2j5qitLWO2yoPke18OTcBMrUpHuu1LzTiHFEpxRZ2F4o7HacQ+8Fa7Yn83dBXyJix85wYL8YaLSivAXb6M83I1NtoQe70VZcoxmboe4R7dW9mU36yD+fU2Y65UKHMfbThDNgyjyPwA7lKFOUYw2YdlyD6vfLMUypk=,iv:f5R2AZWyWd8T4LCw3w+XsKuP4nqIblBhevMLjYM9RLI=,tag:jlBXJCNZDQL0oHri1YxIuA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
