prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:rdOq7zG9u/sp49MVBHHkfIMjMrl2X/Gu1bxU2xVpXzJNNS3pw1y4kzj1VGo9pIn9aOv5KTD+cnahb49rWlnfl69GkmAiwvkzFc6Gc8V5MTcHQ2Zs/jWw/uc5xQ64+Gi8nrS5j1lXDPD9PoEliY1OcuPR3i7W0e7pE5s73xVGzKEaHC7sJJPU/oIsgpQBTO/D7b/DYF3qtJHRr2rW,iv:Ezx6zjrMrqGy56XIH9iriNwvtpW/TiyShNTro55oiQ8=,tag:WQ4CX50Ay1v35tqiTZMnXA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:zTqtuff7Y6rE3F+kKFG4z4MTZCh2p/hgcYw93v5sr7UKXiQJaw545xWHfZvomvWBrFIc+Bx1g9xm3+DN3ns2Sw==,iv:otL4WhPTSq+bABRBlsIP0utFveGfMMQG4/0LtHkTeTQ=,tag:qNQWzy9A7b7rRih5OdyVHg==,type:str]
    password: ENC[AES256_GCM,data:wfC0B46/1xdVyWh9XSs2oEQi3atkE6H6FMVjsW//x7846z3soyGLGopREC1grHwAFILFBdhZb2DSuVRCSInm7Q==,iv:IQLS6Rnv3p7WZc6fJ6QZR5xwj57T27818J9D2xa4JZA=,tag:5QaWcnXouhHL+m4r5OQrYQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:VsxXHFgd2Krpr8oZ9kWnmAM6dT8=,iv:+ClI4lP8qf5lfbmPezmwHPKt6Yk8LXAgKWjc89BUiw4=,tag:bocd9PwJvL+u05hj4+Myuw==,type:str]
      client_secret: ENC[AES256_GCM,data:obeUnpXxRGbTHAjBPa9rwSAuHgxCkdlERLButhjrAJmSdwY3BJ6VdA==,iv:Xi+FGlIsjdtPf/Epd0qXVh+nzu7MF9P7kpDRMUJeiQU=,tag:2JAcT9BLCmxBaNBxUkccvg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:17Z'
    enc: CiUA4OM7eN7fsB8A9Za8/R30V3OwD8bbx9PJLx+V8psiTE11gTqoEkkAZoeZpr3zsj8jqWLCS1Gx1hv+g1PupCagsJxLwr+ooD+tUc3kVfgJdS9l2P07dKk4udvHQ0DnIlC7uZxzHqMFrwx0vVtx3mlH
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:17Z'
  mac: ENC[AES256_GCM,data:lL8d42fB9WpE4ztPBOIG3GxSmQdpFy+SaF3Nv+9gsb+scgyWwoem03HwBjgmIppOTBVimtbZa6BfDbCsGcWEAPa6NCHzla9JX74AbJ+pNgKnV2HsQzHCCO4dws8170rWE7bJyd0hm1QgA2D7+2jbAwbtq8LtWbxwrRzK4Pudz80=,iv:SQDpAfcrciXKeYUzzfpsqDsK7d3MjDDOIpUJ401d9Gg=,tag:a02NM+HXi7RbBcNl0xaYzg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
