jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:SunP9UpB6KQWnZQsE9qiENeV9avww58AkLU65yLrDRGE5/qnG4RRNrwUzW6mv54zdPnx,iv:kepWOlaslU7vnPyyhvv+yyZZ9LZH3uispmQmSpKzXfQ=,tag:Epstpyhg3uL5FTMwMK8ing==,type:str]
        client_secret: ENC[AES256_GCM,data:ciionyrTcFlNeQQltgsoQtt4e9Ee87ib7gdoUJAWGIdwD/DZiqTvVpoIXuFQofsBv/k7NYjgve1ILZKD1CIMVKx8pSAP6b+UvS8UwKSysp6dWDbBluA=,iv:/zUK37t/nVt5a15tKo9yk5YGJbcxw1txTXWVFSC/bgY=,tag:MSpcTdCmo7LYFGItlFFJvw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-13T23:34:04Z'
    enc: CiUA4OM7eA1LSMcMwnt87VR/Zcx26zj2sa6yYo8yG7DCjZDsTP7wEkkAZoeZpklOamBMJgB/YJALLCAIfLGVrW9paAgNRqgbzsAuhLtMcXzhYrrkFJjFzDFjVr/EXoxUpkz7FGCQlGS/ZIyH6h43SvgL
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-13T23:34:05Z'
  mac: ENC[AES256_GCM,data:6qxsK9Yx0iOk9x3hEjZ9FaQ4KZuCLraEwbw6JR+JCSWwuW10oTmtt++2LL1BuogcSeixBtp1qMF8YRa/kpkAiSVmi3Hi6vv8lW9y5XyWzOcJH1FAQu6PVtXiOo9G6XAxqolieZySTxJCLnAfcmOrsJxRbqAEjtVBQXVLALCyFzY=,iv:LTQcU9BfH1AFqfYAA59rr25D9onrc11kR9g1YXCFgQc=,tag:MdbUDr83vFxM0DbBHdA0ZA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
