jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:bEaH0rvn5mLGUr2/VHoPkQAxvE9hjAFc4yzCysxc22vyeJ0bmSRN2orp0Cp8Uztp5FpN,iv:Ll4Q3OHoT69yxzHSmeNJFRTzDXJBzqhBM0KHuYaiMjc=,tag:+/l23V4GQQDDmaGFYim6NQ==,type:str]
        client_secret: ENC[AES256_GCM,data:OCrJUiBKqFvqnfoRq5Jp8Gb7PjBYTCyiZgnXO9D5kK0e90b/8PkKeutoCu7xsWWjNOJA1G64fmH+U+g9YWo3qIsZ26GFjsbxwoqvYBfoS4h9s7s44RM=,iv:nGy85S8AE+RZWOtBtIpOs834E2sJMD3xh/AOKKzbCro=,tag:BV5nIHCECxmKF2rgQIwAdg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-02-16T20:10:14Z'
    enc: CiUA4OM7eLqJdWkxpJefROJIuNfjBr0IfbjsLH729+uRCcXz1prjEkkAPHlbmZRB0NABmyb0yk3TULpqF2E0xZ5QIC25GHCQNVIHwtwd8oN1XwczgXD0Yksy6lZZn0pZI/46u3rRVPjdLmQNrcplwaoO
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-02-16T20:10:15Z'
  mac: ENC[AES256_GCM,data:eqh5vX5NE/rQ0FecgztrLt++f5MxLGFvIp3IdhwoLgCoub3KEl3T/yB+CsvSL3qcAyV26uYev1eSPVoZZocIgY4cAKXJGNoTBA/4a/qyNwEnXqQ3DgokVyRw/XlOLC5+hxZCm9DN2veH+dxSP8dC6THZKeSnq/lt2RHG2Gb6A1g=,iv:3dyyji53St/F16BPz+m67Ze9A5E4R8SUkBRhoeL3E8w=,tag:I7sJqhZLRxeDO+gRmIszBw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
