prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:tX0aTYwiP77UhSSYZpbfRnNMmb1TJoTVPAEi1op53S3KO3+0OxInx55gILR5/+kJoZU95ruYWv6BV2G/+uIJYA==,iv:wYqGFmGSDCrqW2doGpiFIa8e3gxXlhSVFz/Plwt9Ieo=,tag:vhZMY0Hw8ZmvAAzEVNn/5A==,type:str]
    password: ENC[AES256_GCM,data:tMZS/k+jgXbIUoI0hsilWvj+4wGNttnp9Q/SseZLLmK3b+5mYuBX6ezFOizbUkHlWL4zEHXNKLbb7Rez3P+rZQ==,iv:yaJaz/sE/Rcgp77k6ZsCku8a0U5V8BDBj27mIQPtipk=,tag:Jw9q6ibEJjWx7fsIYp9Oag==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:A0Z4mL0vnPxCEPZQvklghBETbbA=,iv:aSVDud7tegYQkByOyudRqHu9D88KwSCVlcc2x6MicnQ=,tag:IHgiEN3sHqy3rkYpLGgV4Q==,type:str]
      client_secret: ENC[AES256_GCM,data:IXOkdbRoUQACuemHesa2EpX8zH9rZHoA4O9pCIMKWL9W9mrnulGkIQ==,iv:6G7fxCmltC2flZKO8c6lXv57EGN3eMyh0gKevq4r6rw=,tag:NrX9xmsbc6W2EG2Y89wmgw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:11Z'
    enc: CiUA4OM7eIcBGO27JKtAwTINhw8U4JC7y1r1JiwyTEd/Oc/bLWdcEkkAZoeZpjnAuShTkxLJ703cdi04YO+PkhJ4r5q/0ERDZOC78VKsm7hatND20YoNTybwPJV1Sh+0QK0l9HytB3rdMAw08dYbilOv
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:11Z'
  mac: ENC[AES256_GCM,data:Ve8G038a5Xcf8IcxjimmjWqbGmbebMaVg3irZVS7GUPVXiNUm9nCfEPS/OGDv/lSRC6sKjwlo9dX4ugLk0g51WhX0TZyV6Ys47v5SJgnO1f7tPKp8c1oK004tofi0dK6C/AnyzRuFEPs0zKQjVU5B1bPEjx8vSKBvSAB20zCTX8=,iv:hyx+3SbbgG2zN11RaWyBIgNAx0+44rofDa4Dvrbgy/E=,tag:WmB0LnFosqLGNrXYF4nabQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
