jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:Fs6EOrDq6BfyAaYFns+/ijIljm5Fpsklr9cXB6txUFNBPsKPXXISgtfD2bPotzdFNK1J,iv:84L6VKIxE39uJBkP1eyI3kNTxiVJSJYwY1X+yzOyTPQ=,tag:gwNRmJFgLcM7PhfuDOg1Fw==,type:str]
        client_secret: ENC[AES256_GCM,data:+PX+pfvtys6M3uYifcpDWxRmysPiIlbYfhetYV1+2VST0j1Y65gJPt0TOqObec2+NF+cpKkqQLYoHW85JaBk/ScQ0L7ZiK1OGBUfgUwTgtZcxzF475k=,iv:8dapaHzdbQlS8tlPs30oB/BBTDLCoJET9Ru3tfrkd18=,tag:jrQpQMRCPO59aW7uOLsY6Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2022-09-21T01:46:01Z'
    enc: CiQA4OM7eJafRlSiv8jeKg4O6XRpSJxCfDsPls6KBgX3br5lmikSSQDuy/p8gRrBm1bQVyBQ9eNEcCWlSn0sk3f+gQctea45XVAJBarkmLrmZv7ANQ65bMc2OQsFTZQRlOvlMIttKqYoY07Kky7PgI0=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-09-21T01:46:02Z'
  mac: ENC[AES256_GCM,data:EuwADE8cct7HlVipJDqDez25f+Fw2qlsB0jZQZxmVPET2qryzGbzs1dCLUGbTwxDBbwzkKbh6cJqcdLrBoB1rHGTUfafw8Qu/xOOa44P1D4URiQWirRhIX5x6ug6tdsETHLvdua2eXAM+RPhncE+js0UnLtDs5rrkUJjNWrMqho=,iv:69dMeOlq/GwfVn9vUEzBgeqQ+TIuTRUsO9tOvWc6kl4=,tag:AcY7z7p0xHuCCDnRVGBMDA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.1
