jupyterhub:
  ingress:
    hosts: [evc.cloudbank.2i2c.cloud]
    tls:
    - hosts: [evc.cloudbank.2i2c.cloud]
      secretName: https-auto-tls
  singleuser:
    memory:
      # Increased to help deal with possible kernel restarts
      # https://2i2c.freshdesk.com/a/tickets/567
      guarantee: 384M
      limit: 1.5G
    image:
      name: quay.io/2i2c/cloudbank-data8-image
      tag: e0390051a2d9
  custom:
    2i2c:
      add_staff_user_ids_of_type: google
      add_staff_user_ids_to_admin_users: true
    homepage:
      templateVars:
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        org:
          logo_url: https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Evergreen_Valley_College_logo.png/799px-Evergreen_Valley_College_logo.png?20210323212539
          name: Evergreen Valley College
          url: https://www.evc.edu/
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        oauth_callback_url: https://evc.cloudbank.2i2c.cloud/hub/oauth_callback
        allowed_idps:
          http://login.microsoftonline.com/common/oauth2/v2.0/authorize:
            default: true
            username_derivation:
              username_claim: email
            allowed_domains:
            - sjcc.edu
            - stu.sjcc.edu
            - stu.evc.edu
            - evc.edu
            - student.sdccd.edu
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: email
      Authenticator:
        admin_users:
        - ericvd@berkeley.edu
        - sean.smorris@berkeley.edu
        - Henry.Estrada@evc.edu
        - hestrada@evc.edu
        - David.Eisenberg@evc.edu
        - Kathy.Jensen@evc.edu
jupyterhub-home-nfs:
  gke:
    volumeId: projects/cb-1003-1696/zones/us-central1-b/disks/hub-nfs-homedirs-evc
  persistentVolume:
    size: 10Gi
