jupyterhub:
  ingress:
    hosts: [gwu.cloudbank.2i2c.cloud]
    tls:
    - hosts: [gwu.cloudbank.2i2c.cloud]
      secretName: https-auto-tls
  singleuser:
    memory:
      # Increased to help deal with possible kernel restarts
      # https://2i2c.freshdesk.com/a/tickets/567
      guarantee: 384M
      limit: 1.5G
    defaultUrl: /lab
  custom:
    2i2c:
      add_staff_user_ids_of_type: google
      add_staff_user_ids_to_admin_users: true
    homepage:
      templateVars:
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: CloudBank
          url: http://cloudbank.org/
        operated_by:
          name: CloudBank
          url: http://cloudbank.org/
        org:
          logo_url: https://www.gwu.edu/sites/g/files/zaxdzs5066/files/header_block/Monogram_250x186.png
          name: George Washington University
          url: https://www.gwu.edu/
  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        oauth_callback_url: https://gwu.cloudbank.2i2c.cloud/hub/oauth_callback
        allowed_idps:
          https://singlesignon.gwu.edu/idp/shibboleth:
            default: true
            username_derivation:
              username_claim: email
            allowed_domains:
            - gwu.edu
            - gwmail.gwu.edu
            - email.gwu.edu
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: email
      Authenticator:
        admin_users:
        - ericvd@berkeley.edu
        - sean.smorris@berkeley.edu
        - sarah.burnett@gwu.edu
jupyterhub-home-nfs:
  gke:
    volumeId: projects/cb-1003-1696/zones/us-central1-b/disks/hub-nfs-homedirs-gwu
nfs:
  pv:
    serverIP: storage-quota-home-nfs.gwu.svc.cluster.local
