prometheusIngressAuthSecret:
  enabled: true

prometheus:
  server:
    ingress:
      enabled: true
      hosts:
        - prometheus.cloudbank.2i2c.cloud
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.cloudbank.2i2c.cloud

grafana:
  grafana.ini:
    server:
      root_url: https://grafana.cloudbank.2i2c.cloud/
    auth.github:
      enabled: true
      allowed_organizations: 2i2c-org
  ingress:
    hosts:
      - grafana.cloudbank.2i2c.cloud
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.cloudbank.2i2c.cloud
