prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:iVcIpC9cd54y6ieK04IawxOEnmrrnFuSL35RmJ7ZlCEgTwjJ+39kWZmwhti9q7FG1P9OLKCo9nzjkl214JVcyZDjV1ofRtrMcqfc87+HghUxyLJQlPqizSbEDEnxt4VLDVM89BafcoFg1lOKKAP4LAqKxBi7cnXjXxfrjRyNZhDSwofmACKJooFtNKip4dn7Lij3sclgtvfcPPGo,iv:GDvySinfqdXbM5zPTjIAS4/S/uK2TKgXUuqe/RJ515A=,tag:4ZqpLsuV9Oae9Q9V2P308w==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:3eD2Lfyk82nJXaoCRNtYGzeW1Pqd/R06ieyMaOz4jIt/CpPwE2hEKe8wrcWnqOblMnVhpHgOcjGthaHeSYBmHg==,iv:4tsBw2ifNyGJ/zh2mkffAgfsE5+z4S/oiPLu/b5UIfc=,tag:hlSs6W4xmg7zGZYcn1TScw==,type:str]
    password: ENC[AES256_GCM,data:P9MP4Hk7t1jDPMGCgBS0xlbZEakt2vKKcgiNd0Epa5z1MAJVMhoUxJS1wNhgvEYVkwdDD5IvjMMYE6s82YMNfg==,iv:k5CWX/3TgHC1XrKUekl54sfQm4EcDpFGLiQztzwsrGA=,tag:on0/vh5dvnDnT7GMf987Mg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:13Z'
    enc: CiUA4OM7eO6vjF+DHf1y/ieS0SCtY/ZnVzu3MDZPb5kJ73ePZ5WQEkgAZoeZprawzMfanxnH7LJ2a59bfz+rNjIKFxhtdYzDYTMq1N1xIgYfN0ToL3Itd8K1cvIJT0gQXZzOnQxVa9xqALJ2gkkP6e0=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:13Z'
  mac: ENC[AES256_GCM,data:Ll0jRTS1RDg8oj1JfY9wwkMjTrhvDBuBsihv9GfE3sw/6xGQqclEJGkURBe0um6qkfODIZBkzdUijtS/7CTk7wDpQqt/GVEc36KVuAWIb8mhS46ZMOyeduU8g5cHzCiTpYyfRN2YBtJyLTkB+6X3+hwVNnRYRpntrGkUImCEBu8=,iv:xLH2JyP/xAP/2OQvgBNEjmGXrYrIVG26JCjjTgE9oRU=,tag:qjV/KSo4SYofRQ5dgP1DsA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
