prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:t8OIZAc/tfKMunruBw1Keqw68bm4eT6uGG3reUZ89H+UcfWqa7dqme9TSQb0n65YXzZejvxCvkNgPXoh5bzzCg==,iv:NyTOjmbmJlaabGwQ8m3Jv7VRJ4uLw8qx8j45YxpLCDk=,tag:ieQAlOtasoD7huw+wAX5vA==,type:str]
    password: ENC[AES256_GCM,data:7H5o7XjT7vqHGcgPcxUg5u1msEDyB0OjXJTeu0+M2rg6+fqJVJfnIVCeXbsz8vCAysUdGf9PFv6ED0EXkKZPEA==,iv:Qkbp62e/iO3bYdCYMoiBtPQ0WlwGD1ioama3jnb4e88=,tag:cIWhT34h3MA6h/sLzuBCpQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:07Z'
    enc: CiUA4OM7eHeLyw3TYKDJJbDqxhReKLBlPLoUG4lYT5lGDLZWKkj8EkkAZoeZpkZV3hZQLnSlIYDYM32aobb4y0127+w0t7E9JdKR9xpDTrizCD5iAHjVBg/eAk054ClZhvm0wLiVSE1bytD4JW3BAAr4
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:07Z'
  mac: ENC[AES256_GCM,data:xjMZeSqfzA3/IOpjYvF/ICAeeiOCq0B1iWjELnVRw+/sjF7CitwaQKqPWIFCQVjdzwnzIdz3JXzDKSS/fSrAKR6AK651fQI4Pw+ADJbzVGsK+hyEtd4HY5TFDSH5z1UFw3efzAU2RN37Gf3t3t4UqLOrMwfXrk0ZCqdObh+uaeM=,iv:cWSNny4DPQyZNJKMRAu8R4AedHU4SRDFDATN0le7Dvs=,tag:obmsokoOwClJ/8lNSZ0+lg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
