prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:LiET0MbYKeaGaO8/by9tbaaTRNJpmpve5/98reZMgDzrnh+RHTSSgrNA9bMVtH33Jdo1isYXzRACb5PntaXSuw==,iv:CnDFUDEtUVCQJocuKCLPebqZH3vw9tLRTEF9sWdt+8w=,tag:Q3STPzhAK1gBwQQfybeavw==,type:str]
    password: ENC[AES256_GCM,data:wdJ4yjNhyc2b9Zd6Gy5Sebg65mozAFQXroetLheJrMxF/YzaLHaA8/m4e14/l+sZ9HHp/b6BbobtQbEdp8paEg==,iv:DirFbWHqHNgux6pCZkMJi7Pl1ss/kgUtl7tOw+H0rJw=,tag:lU7FEC+wO5HP1NDQoJS5Jw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:01Z'
    enc: CiUA4OM7eN9L+ggXlSdtlyneRWev/HSJucyitgMPKLOYjnJFm8vsEkkAZoeZpgmYO8VvNd3ybHdrPdJmFYFOzqfWeQjQ6745kR4SjKK2p6pxyBQ19XrDsOw1McynYHm+RWIsD4vYzFxeFr3kKPrgwoXH
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:01Z'
  mac: ENC[AES256_GCM,data:IAgP5YMcK9pgOC4asQjD6dQ5m4xhTYsJ4pxFyOJn9PPxOQvzbbbNAzGNzaOjLRhLTrhyPRMOipHsu0Ey8XmAURnixVsNPSid0rj6G3p5Bl29i3Fv5R1o5o8RU/lCpU5F22/tE/8AXRZZtzUttdbCMirL8g0ARBHwF/BiBNhqui4=,iv:gyhOcIEhlHuOFcpBirA/pFhAeOE4m0LeUiml3r2Ug3c=,tag:IDV9c7gx+b4xR41+V5R8JA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
