prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:jGd99/mCF2XXLSJBp7EbIFYgMXtkTImU4yn7TsCmW/R+xlRVq/PuZEg3aXdE2gOZvWYlDozhkE6tbVZUBZMCELvJJ1GJnj0JQnMNqvpBk/k3E0BItf/bvW5Nm1VTiSiFsxpyPKfRJHrUpS7WRJM6dHbvWwvXQBCMn+cAsOD38wwyGUCBvKYp/7RIaGy0AeayP4tTr/tV4zYgd7zR,iv:DbIQmO2p2UTYhgGARH95luql0YsTaTyy3aScsfmNe7s=,tag:H4EPsDMxEZftOHJe+N22WA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:Zl4buHJ0dziTV83EldaU9oyGajvQyKUfDrefERq/xUKqrA2D7XZ1fZ1RzkbA3sL1WTQgDgZXGX1o2viN4Zqmqw==,iv:V8IBvuFfZ1wDCdZ6IkrETij0d2F+ZnV2Qj3oG/jQQno=,tag:WmzpGAgvK/CVYa6IWkRQ/A==,type:str]
    password: ENC[AES256_GCM,data:AZ6hsRBCCkmaGPWDrSseAd4xOqh2QygRE1U2G2BJRDd6Tg8i2+6iyUS/7QRiIJ3Tr66Z7uVo8NOJFakDGOsy3Q==,iv:m0oV/iFrQuXJAhAr/kCrVJUu4lZUSLTh7IXe+rmxMtI=,tag:U2AYVr8j8NB2GM8tMRzW/Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:07Z'
    enc: CiUA4OM7eDNHlLejRn8K6AIw8j0xUYIOOBQmPNXc5oBPaX/6BLJCEkgAZoeZpvWT0idzKVdTACfmACMGtOWVTFCwwi80awWFFU6Yy1+/XdGiNEgTnnyG7TVyL7WCwkYx9LxpcQktdsVgkz1hjfVkwfU=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:07Z'
  mac: ENC[AES256_GCM,data:46033oVAh+qB4cJniVtXaszmqVQk1E77+r/NtThPAcTmYFwi5mCirhWc7tDMUEi5aRVnxyt+wrvnGfdFWkF2hmaVJ739PlX4jMtW8O6D9cMHmf/xtWZ6D10tOSTJ17dVpEpu2iDWfgrW/xhAYIeXhvMgQmi4gRMz3E+e2OBv0Y8=,iv:BOVPU/cIswvqq9Fpl0cEoqyZaoYfGh4P4U4/MDizui0=,tag:c6Ntu2YXxYFhdlsr74HrMQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
