prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:UMEL3B9iA6rn6t7hqZT8YfWvdOr3PlDh3dm7IcuMX/5XnFVT1/Bz/ScSFQvKiYzFiiNaxYXCNJmpe4qOdqG0cQ==,iv:gJtFNj6BH34t067YcPHJk5qEYAytBtefXyFSv1Qh6e4=,tag:kKxd3VxgIunq2K+Qn2Se+w==,type:str]
    password: ENC[AES256_GCM,data:JpXLKipjkmuTA1jrk0yWwRoslcf70/lT/U9QdP71ZKRVCOOOyR5MVgGIRXTVeY00syLKBrL5FG962C246dzxug==,iv:2cSkLY1BupFYqrVRvfqN+A6cYCP72T8ANbNtAQTwags=,tag:e7XsQWETUEuskUUUW6aXoQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:0YpsZvyxgk+GqCj2JYuTz8p/hno=,iv:l5MLzuWZvBj5o7dJd8utyjwrDqbCad5wh0JBmio/5E0=,tag:bbgpO/BmwZKRZ7suKNTH/Q==,type:str]
      client_secret: ENC[AES256_GCM,data:Q6RFr+Dxn7I/WPb8NcDPqeugto9ERH0a0kTD9sfGBzTPyzj9xRKaOg==,iv:JNQIy0GCUUbxC9CfIrjHn3PUEJ2M8Q88nodNRYdCWoM=,tag:1kWleMX9OvNH4MHwzdQlKw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:40:58Z'
    enc: CiUA4OM7eApVTF/U5EbrotE5ZxfwzhSTWCUzt0AX6fpyIwHU2Cl+EkkAZoeZpt5AphO6jM87493BSU5t7YDJl4MA4oBVTgIX6vO2sMiJTEK7kNq5CrRdXAk/GXgYBkTZ8NOziFRvMpoL1nWsGFW7w4L5
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:40:58Z'
  mac: ENC[AES256_GCM,data:zp5Hpu51TuAL2fQbWUB7UkKKt/m3jNUCy0oUlyasJjP+p6bwTVdlskXqaKfy8aSG0HMIwlvGODoJ+eWGLFTdv1M++uTKp8wlNDshX3GBBmVLOip/GIH9d/eDIJslsZVAYyyoMs4q3Oj/WgsKooQuNfkAuM0PfErkhONdoI4PD5s=,iv:C5yfCIjciuBpuim6snjmIKVR1Q6nW8d128vpFiEU5kk=,tag:aiScwHhbvT/pI6VvH4qMgA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
