prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:YN2ASPRbs+fQ7KwCwZIixYv41D0/s0kDJM5wkuqNXvPQVVTR1pUWYss1v9jouyWPcWSy8TdOsPA6Ym5J2RTudsoxBp6vN8esNVwNk0siyDjCgwE1LK+TKFYyrlH9MKPJtZZ9UNbnn/Gw11i6jvnLfHAkMss25abToE77FTHbTsWy4/rNLs8dWgs41IWqXCUIIPMyrpugie3qui/J,iv:DtYw3V3hC+eBInpkWH2MkTYaDEg3D6wRvX8okWkJSx8=,tag:lcDhlRyeEZQDCel5dQMOfw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:Xw5kLS5Ku+VMiF2GznHyCvxiXdnP4WTRprSJyc+gzEcNDWIV+rjuXjwZIzKcEESKLQ1M4XYCkviaBnVm8HMFWg==,iv:dS06Pm6TCWazjyCjKPxagKusm0Bm7NvnNcK+hA4Qs0M=,tag:+lzq1Pa8NbUea4dT34x+hg==,type:str]
    password: ENC[AES256_GCM,data:COCpLxMK9PjPbgNZfBaqQyvOA6ToGr0QNFAgrHNoSquiO58X0KITPeKvrzkrYBOp/NXUFHSGn97/iIONKRy2rQ==,iv:i236bB8KBSW9gwqlYDR8+pyrKpN/tSyfBK1P5lV3j8c=,tag:N5nl00qSdhRIVdFkZZvwrQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:CKjCk+e1vdP6fRbje5W7tE/jn8A=,iv:Q6WrubeWQBCgLlTIMgaJzF0meqYXotN38oVcX5PbxTo=,tag:KKKOqTOLuZeUtxI9ZbwSCg==,type:str]
      client_secret: ENC[AES256_GCM,data:3UPAWiB+TRiBeNspz2lBmg4WjnHz39koDugXvBj/JJ4XgSFy6Y4++Q==,iv://wOa3sSVp+ZgalNmC9ediBDJZLunZooCQHmR/w4uLo=,tag:fu5ZziVTF0TYUjPKyCBKYA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:03Z'
    enc: CiUA4OM7eL57D/ZS2AKqj3tNYAPn/9n1o0PoN+0BJ1junsB54bkBEkkAZoeZpvZjJRmAiQMbTv7DhDX4YQesnBDXB4DOcqxxZskxlq6T65hIvFKV6Y352hZzXFY36+9cYbw61hI2yBdgfV5zfnuzLs+V
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:04Z'
  mac: ENC[AES256_GCM,data:4wgpP/OOc47ni9NGAgk/WCmLL6HH1T7npEeIcNiYzzqvrnHD7RwcM18oE6aRJPgRDuJQoSVM1RmnaRc8tljg5SYyunD9y81rLUyJ/QjDmL8qiKvAjultiU8j4IBdNj4OuFt+3eFqtNCGS9zn2pt+shiRDKrBHppaqO5C2wn8ryg=,iv:e1xAN30ZHWpCdmnSQh4AXRG89G2XhVo2zVzdBTMmPMQ=,tag:a9Yt1gv87ZL0ZOm7mfdk8Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
