jupyterhub:
  ingress:
    hosts: [bon.af.catalystproject.2i2c.cloud]
    tls:
    - hosts: [bon.af.catalystproject.2i2c.cloud]
      secretName: https-auto-tls
  custom:
    homepage:
      templateVars:
        org:
          name: Catalyst Project, Africa - Bioinformatics Outreach Nigeria
  hub:
    config:
      JupyterHub:
        authenticator_class: github
      GitHubOAuthenticator:
        oauth_callback_url: https://bon.af.catalystproject.2i2c.cloud/hub/oauth_callback
        allowed_organizations:
        - CatalystProject-Hubs:bon
      Authenticator:
        admin_users:
        - Seunolufemi123
        - Emmanuel19-ada
  singleuser:
    nodeSelector:
      2i2c/hub-name: bon
jupyterhub-home-nfs:
  quotaEnforcer:
    config:
      QuotaManager:
        hardQuota: '1' # in GB
  eks:
    volumeId: vol-09dc8201c516e2e70
  persistentVolume:
    size: 10Gi
nfs:
  pv:
    serverIP: 10.100.204.80
