prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:kWBfMX3qU2AKfPPiCzg5KmaSAy7fGUUgwnz8awGnVQosVxQKGBn0Vjq9W2i8ol5oERGfKDub9XCUesK3J0LnyhHjWc85E68wpHLGYnl0QTkhWGvUQCabhZUHW6yioKF05m4gNcbh7QZrCKRfYrdBakuUtWnV7mBxP979T7pVGsfrsQpX+Co0pnoKoTa7LJewaWwNEpcJ59pFyrIX,iv:EOfJZtq1kvy83LOJhkAYg9J13L9EU0SDr9tXgEhb1mo=,tag:yIy6ii86aqw7IEOXsXGmFg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:ucdVKw82iQHf4L6zAD3FdCLrYAepVoxlhizNNpW9e+TFGE59VwC2Z0ZPXwOmJpPLCfzvFZ1rkx4M75oGA2cO5Q==,iv:cduLFfuAGsjrK0X1RdA7S2vxNPiGZqXVud+2KiUIy8A=,tag:blIP4HWIbuCjkezyWiJV5w==,type:str]
    password: ENC[AES256_GCM,data:7ZJ851VPYgjtOahE8xZf3LCd2B0W5m7170mijfNUY3+SscwujV0hmC6jbAYdBYSGyB4NyFca8cuZ2gKqP8jzBw==,iv:sFS4dw0HRKxlj/fCP5DfTsReIxg5wRRQ8gzaaGLGUQY=,tag:mQeXJrl+13mwkNf876rklA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:06Z'
    enc: CiUA4OM7eBfCdW3lB0Vfi1CwcnZz4RK0+baLbfR/MEn0yJ4vieixEkkAZoeZpscbWzYAFGjeO8Plea5h00p1oI5z49ENcNBViNmwn53HueO+xFHB8ZNp0IP/If+xyDKl607NZm9rEotJqncL9NJpQjb/
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:06Z'
  mac: ENC[AES256_GCM,data:zURfsN8jnN7uE7N6zVl7QmWAFqHUfpzU9Dar9gZYMPWMPqmq2MYf55LEfBelBQyi5bDA175jB5PkyfaXaCfd9q+C6nGTQJhJ0Nb8EcQoWAQcSF7/TPG0x/EAjNrIuL5Jlh86MeSzMRNUFaLxjZE1jioLpNAVtHEIdyORVMAQjXM=,iv:TuHRE3dEE2gsTbGq9cKB6X7z0bnLcWOFDLFTaPvZhDQ=,tag:yQU+xrTLo55dnbbUqm0L6Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
