prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:AXfn75PUfRuPEsRzR9mxPTXqHQAwlGLkFEpV/GoKlydaS4S5K651+RAreQIKv9ntR8G+FK5ysxSAi4JlYiR8Ug==,iv:SkAPqmX4oDDUmQQA+BdME/IM0VgIR88EGU994QiJ2I0=,tag:M7pMHGYWMOcou2mSkBFDWw==,type:str]
    password: ENC[AES256_GCM,data:V5/hGypI63Eg6MYKCL41/OiXcZ4iB2zeL8x4kBdBIHBTsGWAJE7vhpYDtjcGTfujLBoSA4zBY2rpHB/q84qeOA==,iv:1xQzdsBMapZ1TBTWY+jgBdUEULjshTE0r6WkVSCfHcs=,tag:T+11KlMELt/ELZTvK+zuAQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:00Z'
    enc: CiUA4OM7eHovivzBug48AYfSPUKmjIIH+tOOP+xZa7BUstYwF48fEkkAZoeZppnDgDDW2998dTyGfbEXs/q7XsjUqwy45c9hss1dWOsJB/mBJbXSBM9rvi/nyI7uTgz7YM3XefSER13p1hqtEAyN6x5C
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:00Z'
  mac: ENC[AES256_GCM,data:4OPXjCVBERX6Pwq3HnwQTY90R64quYkWzbXWdpPLV/c4clIqVIT4Ib6yS4UIzKCJF+xCl7omAEE9fgPXr4PbSYEFJQefch6lUuH2QTKSt88u6SQSVhc9pH8K+gWauB9k6b+/xF6cP1VP3uSXgVcN9MFEJbMqq9vnfl2pY54Gwyw=,iv:t1LZNJ37Ey9stpmJjli6hO65YIqcycRQRsMAb8kkEMU=,tag:Cz6WcwNjhubNfgMHVXWUXw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
