jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:eg4yo+7kobztYqLXpeR3vcQtXIU=,iv:v7u+Soe3C+cj5sAhTP7Cv6HwMpNhJ2T7PsER0Hrr//M=,tag:Q9y22FgQlEIlzFiQLxXFFw==,type:str]
        client_secret: ENC[AES256_GCM,data:BA4HqDHaWCgRqWuKikUasKh+aqTBm+Q7j4D1U0OfbOwxIx6kHKc8gQ==,iv:ZVw7RFLm4s0iSPEAiibFxOjfRxlcqNwnv18peDq/Lgk=,tag:j5fKtwvvuF3K2LdAE3LMsQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2024-01-19T19:50:33Z'
    enc: CiUA4OM7eMb0zTHlzhLypRrf0SjUiVx7JlJThSHKlNYroiPeRR11EkkAjTWv+k7KcyKwMMfp+QIGzPoWp+4CkmNl9pz/mAB3v8/6xFjimprYziUq99t9NrH+sdGtWua+AEgL808qn9Y6khAJ/uH4zJuN
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2024-01-19T19:50:34Z'
  mac: ENC[AES256_GCM,data:0V0DG6N5cQ8Wgr2wuZjEDqWIk5gAgbxJj2aG6CF+Ct3nEMz1hG9kK+2QeSJTBt8Yclkb08pw62DUhGxD9MXOM0jDv8PRck7w02179sRzLZPX9tqlk61IuywINmsD5B0qozwRBiBIyGXCCQYI7FngxYPsqCrYZTKp0El6P9CXXy8=,iv:tuEYh5OWhK6YlcEh/uph0pVIzWC1SgyrwjMLUC0Rj04=,tag:CQubFcxH6Jh9Ceilq4GSqg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.8.1
