jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:CF64J0Sv0ScCZZFMmJBrFcYFh6HxvTLPlZRiF3zAUJmEYcYNsK6fp0U2E+02FfsCFyF8,iv:RbTYszndZq4LmjOUflp7sx77k3a4wONbZsab/g+R/+M=,tag:VL8Uozmm/oHnYUt8mvXgHg==,type:str]
        client_secret: ENC[AES256_GCM,data:kvgKMZ4THqZBZTEtm4OVEnabFrtFPmQGlq4Xy02/fFfmS6AygdY5SEAP0Blcrh1wsdOiXUSyYlWEDu2KPOjoi20FygxKOGJAg0deryOfUb5hONhw9D0=,iv:RhBbuagExa2NFBur/3D54tqKNJCFxCuW2k9z5SGF2/M=,tag:WRPcwOfDR3VsUjbbAc4ThA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-10-16T12:22:02Z'
    enc: CiUA4OM7eJkpartzmHc3egRINHzuNJ5HoQC5npPwdHbco9oBYa9EEkkAq2nhVf97mFKb5TjlEzurcsdHdyvXqg4j0SioCU+IFKBrKL3zOuGy4aVFJll5DeRtC9vP5HPeN8fdaS4pPsLA3J5MQHdxKzQN
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2023-10-16T12:22:02Z'
  mac: ENC[AES256_GCM,data:/VrfzTI10JjRaAbgc3rcUi5807KltwiKuXx+U6teAoQcDbsKnSZ7VE/gZEFErhlnINzlhjO5p/MkpBoVBjZP/U1MefbYy8tkjiWqv8Qbm2zI4YcDm4kTpTKgeCuwrn7bE15hoQvFLNTeNzhoHPgsuRiRcmhIBy6AUn+ZkNWIqrM=,iv:iQ+sSNoULEhDt24uLwyN5Nk0KQFyxRla7eyhSHqo1h4=,tag:P2mx99Sz0UD/4DdpHMtRLw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
