jupyterhub:
  ingress:
    hosts: [uvri.af.catalystproject.2i2c.cloud]
    tls:
    - hosts: [uvri.af.catalystproject.2i2c.cloud]
      secretName: https-auto-tls
  custom:
    homepage:
      templateVars:
        org:
          name: Catalyst Project, Africa - UVRI
          url: https://2i2c.org
          logo_url: https://2i2c.org/media/logo.png
  hub:
    config:
      JupyterHub:
        authenticator_class: github
      GitHubOAuthenticator:
        oauth_callback_url: https://uvri.af.catalystproject.2i2c.cloud/hub/oauth_callback
        allowed_organizations:
        - CatalystProject-Hubs:uvri
      Authenticator:
        admin_users:
        - eddUG
  singleuser:
    nodeSelector:
      2i2c/hub-name: uvri
jupyterhub-home-nfs:
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 1
  eks:
    volumeId: vol-048173ffd8e87f1d3
nfs:
  pv:
    serverIP: 10.100.30.88
