name: temple
provider: aws # https://2i2c.awsapps.com/start#/
aws:
  account: 324830304144
  key: enc-deployer-credentials.secret.json
  clusterType: eks
  clusterName: temple
  region: us-west-2
  billing:
    paid_by_us: true
support:
  helm_chart_values_files:
  - support.values.yaml
  - enc-support.secret.values.yaml
hubs:
- name: staging
      # Tip: consider changing this to something more human friendly
  display_name: temple - staging
  domain: staging.temple.2i2c.cloud
  helm_chart: basehub
  helm_chart_values_files:
  - common.values.yaml
  - enc-common.secret.values.yaml
  - staging.values.yaml
  - enc-staging.secret.values.yaml

- name: prod
      # Tip: consider changing this to something more human friendly
  display_name: Temple University
  domain: temple.2i2c.cloud
  helm_chart: basehub
  helm_chart_values_files:
  - common.values.yaml
  - enc-common.secret.values.yaml
  - prod.values.yaml
  - enc-prod.secret.values.yaml
