prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:VZ5yGY34U44So0I+gGj+0NVo31bGCiXuHbj0fMq7NKX3OGiGGSof2s6jfCFRI2Lo/pin+kyWCEADvLtijqnKSA==,iv:VjePBLY49bvt5T1TLH4tq0S+AwquotNppB6XeZo9fBY=,tag:HGXh2CDFv4VT8aIJGYV9bA==,type:str]
    password: ENC[AES256_GCM,data:zCy/LDFGpEYWRY1A5IqixRQ7DQyL1N7poVHqAPoEoEP27cMoLDDymzYRLZR0KH81id7A/je5yx3N4qvt6ssT5w==,iv:UolO9JuAqV7DXW7OSH4oPMj839epMmxRJabE8A1f9ok=,tag:iL5emH2zsbTW0sgVcHZ0VA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:15Z'
    enc: CiUA4OM7eJgq6HwXSlNXvWLssfR0lT0rtc5BAi3Zu+FAyaWa0P2sEkkAZoeZpl0E6Rnm6P2buJj8iTTgRApQeDcJhPhqX3xK7QOABKpD6I7Jbv2TxLhhTKru7paZ5uZEf7Pdi/nvyPthPx4kAW07sL7o
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:15Z'
  mac: ENC[AES256_GCM,data:yM7WGidXnppdyUA/x1rVmyDUHVm0BXp1VSFVJXyet3toUmLnyZXDXb2kbWvdmAfdN9m87Ls5gH3SrU6HqDh8k44frkGhTY8I8nj9FAD7WFYpZJ4teQq3TECXpZF7evr5ZBq/3apM0J4JB0tOpFy8a4DKh+rLZEdvorR+NesoDdQ=,iv:PbHcavOKIU/p26G7DZ5s0vuJAnHOcr/LgN17KNHIv/8=,tag:wllOaMIwWm++Xrc/KMAbXQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
