jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:YG8dMcdhs0xGVpKQrOLGH+MYx4hpnoPT2to/U6kjuEEZI/MnPD+ewOlGQd3EOSU2J8gv,iv:AWi+oImq/dAKa0BAAXctuII2DZlluM437OCoGAdPZP8=,tag:j+v9sfc+jEosXCc1eMAMpw==,type:str]
        client_secret: ENC[AES256_GCM,data:wbotT8c7pyfc345s85idVGoupPiTECwT4lLf8IA40/KummzpIcawR82ZZuZmeCOsaYQ4InX95wi4WV11/VxHodWJqXrRO6gb29zazERP1J6dHr5SnG4=,iv:Y492YqhIihZF9Px0EZGfKm4uRcXOcL3PVzipJZ34yZI=,tag:eBev95btt2VLHC6j000RKg==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:O6qT1VOCqWL/kJN6GWGzP1MADxN6jOTR7gA5WFg81KpTSGBAsgfGk5JpRVNz1I0yXftAhAAy,iv:IsNz7wXZq5UoJMnDlFDNyCNpU1wWJIQEvwXgI3eBgjY=,tag:Bhtq1toYAUY/Ej2lJuhOQg==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-11-24T12:57:13Z'
    enc: CiUA4OM7eFwBAnVGsAP7LHN57SxQGCwug6LPuZwe0y2y78049NcLEkkAZoeZpmSEkuTMPiJ5TTVTZCdQdWcPB6hS5wxAmGuBWT0ZTmGqRnXXSQe2jdjv8gv3WdTGn1l1TFVDxrsyppZweWPjLTHzPVVH
  lastmodified: '2025-11-24T12:57:13Z'
  mac: ENC[AES256_GCM,data:gKPGJsu+OZndNwqjwa1YvcLtOiYY0IXD9VvFo9W8D61+bX5CweNQs01fbu3Yl7ITy+rSj/LKHE6mKBZ1Pm5JqCqrnjPOthWAMWG0+HgUC1NmaMWjKkL9w9S1ZsoJsUaDmVNmuIwEsgy5ZCThtcKsFy8A70eIf6+B/HiBucvKMSM=,iv:GSuCTYOYrDmnYN5UW+AvZyoCtgONZUiwZrY2EpGM/Ys=,tag:QRqEC//kdC47Gpw/u8CLGA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
