jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:+ObijsYXL+mozUHt7hqX1ONejMx4lzUy7nrUVTN44/2lFPs49uw21iV0/wcTvawZwyxE,iv:h3jY/XKc5eQFVFXWu9eY5ft8HMWTOmvx77Z33v2IEvQ=,tag:b1eIBO013i+h8Y/alWMAuw==,type:str]
        client_secret: ENC[AES256_GCM,data:P3ldNIA3m/dXdK63l0oqKy4j6eSAtXmXUvLRt0ekDsWHHDt7JYZHxJCx/kncxny29t3mThJaBdZ7PAeMXH/iCH8+WOGknmKY4UHhwUdGEamEuGZgdu4=,iv:NQC8cUgGiKzfZu3OYJspGU4LBPePcuX/9lNOmQX0TrQ=,tag:h/zK93MQQ5WyP91puNmGOQ==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:WG8iqMkBefF59ykhHaZaI3V6N+Nqgli5lglHSypubQ4p1ULxX+AGTRk51fTkKY/IcpoA2GSW,iv:u0zjqgIOhklLmpADwWLcZCpIayDURptFaHpv7SOkiag=,tag:dptXASirvAZ0gMig9M5oHw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-11-18T14:37:36Z'
    enc: CiUA4OM7eNyGllJ+iM5YmEVkZ5NAlpJt5JwUIomt1rj6l+O9VaBqEkkAZoeZplKlA9MYD1WW+eUhgNMexhOD8QrrRL2YkIeoLiliJoWEu1xnMktDysTr88ysPeB/WKEpnJMtZiS0b2JpGONxxK1wK1Dy
  lastmodified: '2025-11-18T14:37:36Z'
  mac: ENC[AES256_GCM,data:HOr+TYGOkvTMT+QRvEGBfU0IWGkvw3eoHNYAUtBCvhmxHgGGFZIYm02ZLMinvDCQkiD53vygjk9GK1/nVEV/qyi+07+ImugCEQdBMe0a71BNXM/r36uDmID5BRcVJ9rPxH4kclh5vneKpOH8hPrQOOZOJeaeiQHEpMNROCnH6oY=,iv:TjqRjz7lotOvTadOxXsXvw2U8bN6I8TwdM/rLYALmNM=,tag:GoUsE2SnZCF6+Vld6lcA+A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
