jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:QLHfGqsfiYXNYE1kN+M6BHWA56MtoYjfRFzSrCFCmnCXsEY5oylqGquBPwj1nEvgipC/,iv:eIcJkNjzUJhT84qYcO7u+/urhzcvIA7vzd1uBVVVsyA=,tag:vwvLNRzW3gEYo117AV7WiA==,type:str]
        client_secret: ENC[AES256_GCM,data:b0q+TIghWKDSVrctFpQuhRzPZfawfI/Q9KEeio4x6OqFH/iWvB9tmnaQc9aBFVovAJEuTNpji+1uoRFBwxLN0s/aKNEA6win/9M/FKUSDKFvfjZjbeY=,iv:6bGBvpQ/cffZSSP8Ay2ltmyG5tB6yI8Co3h4r7zo67I=,tag:J1kAMV4gu5TSowpZBYh5bA==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:4oYpjDEFZ+XchWcwGMJNCHomSKIciTDlUCS7uoLPGTq2ZXmrSc0d75JIcLYkoJQldlTNK8Il+w==,iv:m/q8Vcotz7ik6oFkSkhoxkv6s0ca+dJAbLuXfiZ4V5M=,tag:grUz0GtzbTVDU+4o6rl50w==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-11-24T12:58:01Z'
    enc: CiUA4OM7eBxqftkBWE/moPT8gQxgQLALCGKI2BHGvbtpp6kLIh7NEkkAZoeZpmSfVbNyrl/oRjb8DvhttZKZKltIixCIq+0q+4qZ/bkMJHOd1y3Ndmn4DQ7f4jlWtD9GnH8DhCI1K59NqUkZZ45MlEyT
  lastmodified: '2025-11-24T12:58:01Z'
  mac: ENC[AES256_GCM,data:KE+LURCZ7hfTGpZRpRYaqAB3JXcYwE6B24NTnDwiwAQGmJ5bgZAKAa6LoxYtMwjUEUYXQfdhaEajieLx4y2fFw+5g7ODJPMO+T25oZRfeb+0G02mGoO6fugoSzxdAG78WnPKJh1xtSlUpU3n5G5ReS8hviKS6xM3o+6naPZMd1E=,iv:iA5RPUA5asicNHoI/RsHZDFMEm5NIDgY8/l7b05Y0B4=,tag:hSsgulVV1K4hUnrVskq86g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
