prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:/WgI7oj5ZP3rF+3Ft54Q8T0ZJ0TXrjYl4mva8bGgbyc5ohpLsYoTK2OPd9Chc7SS+Ntwc/d0gBQ3VlUYuLPywbiXPp3C2lxsOz9Y5nlDwp29vuITLc9ykY3ldOM1OyCLRdW970YYITOOc1ahNCjqw37Vb6rhII20zjfYMdwkmAD4CGnRVCjFZ6uSyYazszAbkEX0QXmFxFUPGkzn,iv:A0d2TKaGHIAli5ymX7LIuOHAfR0l5fgmrZQ3J9SN4/c=,tag:8YLK4eNQhxV5iK9fNLW9Pg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:2UAyBjFhTmKx3sxv4oTdGigw8Inebio5Q72f3NNZHxyKl21uBNhK7faUvFjR4Z9F1R7SnzlFQan63xU6jfHsrQ==,iv:lEds3GU3pYYrpljYjzsPzEBXwoODfrtkZVqSReHCNJU=,tag:8vnBptumdzOc5nDAWqmcww==,type:str]
    password: ENC[AES256_GCM,data:W0bS2sguDljf1kchIhhkX3M6Ztw23eUwZHa4F/m7VZV1OX4dIkbqd3zUByO41jo5WsxrfgPl5k/SC1BjB5ghHA==,iv:2dWX+QLgx3TLBYTwPzkoFIbMVwfOiBa/bCHwrgt3Fv4=,tag:Q+/UREkmngHgA7LPkS5bgQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:21Z'
    enc: CiUA4OM7eB3rPuwlVoLBTlkoUfmY9tV8+1ekOI0PRZoHKV0U2I0UEkkAZoeZpgboa3d22t+KDSkbJWz1bkhhTLMuP6uzUdJCEhp61wyCfjbpRrQmAPoInGMMZC2HcTnGl2Df2z6Ms7ePYQ1zh1BlPeKe
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:21Z'
  mac: ENC[AES256_GCM,data:3VmYfzuVz2mHuUoOMBmBc4BFM5/AA/MigNNMQuSVg6Y9Ynj63fTmesPVP0SQ0ivrlJaNdQQVf0Av1QjwIqO24Bgcaol1gCRe7scAKKvDfOwe3x9tIxKTtYQnmsAXw5SzPNSn3zTUuY98AexC13hL01WgU+rbxEotDYQEGgwEUxM=,iv:QdbUwx1ricqjLHbPEuC1KmN35pCLBSKNPNGKUTymtNc=,tag:cpnTFWWVZeWzB1s94x4XsA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
