prometheusIngressAuthSecret:
  enabled: true



prometheus:
  server:
    persistentVolume:
      size: 100Gi
    ingress:
      enabled: true
      hosts:
      - prometheus.temple.2i2c.cloud
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.temple.2i2c.cloud

grafana:
  grafana.ini:
    server:
      root_url: https://grafana.temple.2i2c.cloud/
  auth.github:
    enabled: true
    allowed_organizations: 2i2c-org
  ingress:
    hosts:
    - grafana.temple.2i2c.cloud
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.temple.2i2c.cloud

jupyterhub-cost-monitoring:
  enabled: false

cluster-autoscaler:
  enabled: true
  autoDiscovery:
    clusterName: temple
  awsRegion: us-west-2

calico:
  enabled: true
