basehub:
  nfs:
    enabled: true
    pv:
      enabled: true
      mountOptions:
        - soft
        - noatime
      # Google FileStore IP
      serverIP: 10.104.103.242
      # Name of Google Filestore share
      baseShareName: /homes/
  dask-gateway:
    enabled: true
    gateway:
      backend:
        scheduler:
          cores:
            request: 1
            limit: 2
          memory:
            request: 4G
            limit: 4G
  jupyterhub:
    custom:
      daskhubSetup:
        enabled: true
      # Extra mount point for admins to access to all users' home dirs
      # Ref https://github.com/2i2c-org/infrastructure/issues/2105
      singleuserAdmin:
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/allusers
            readOnly: true
          # mounts below are copied from basehub's values that we override by
          # specifying extraVolumeMounts (lists get overridden when helm values
          # are combined)
          - name: home
            mountPath: /home/jovyan/shared-readwrite
            subPath: _shared
          - name: home
            mountPath: /home/rstudio/shared-readwrite
            subPath: _shared
      2i2c:
        add_staff_user_ids_to_admin_users: true
        add_staff_user_ids_of_type: "github"
      jupyterhubConfigurator:
        enabled: false
      homepage:
        templateVars:
          org:
            name: LEAP
            url: https://leap-stc.github.io
            logo_url: https://leap-stc.github.io/_static/LEAP_logo.png
          designed_by:
            name: 2i2c
            url: https://2i2c.org
          operated_by:
            name: 2i2c
            url: https://2i2c.org
          funded_by:
            name: LEAP
            url: https://leap-stc.github.io
    hub:
      annotations:
        # Prevents the core node on which this pod is present from being drained
        # See https://github.com/2i2c-org/infrastructure/issues/3461
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      allowNamedServers: true
      config:
        JupyterHub:
          authenticator_class: github
          # Announcement is a JupyterHub feature to present messages to users in
          # web pages under the /hub path (JupyterHub responds), but not via the
          # /user path (single-user server responds).
          #
          # ref: https://github.com/2i2c-org/infrastructure/issues/1501
          # ref: https://jupyterhub.readthedocs.io/en/stable/reference/templates.html#announcement-configuration-variables
          #
          # template_vars:
          #   announcement: >-
          #     <strong>
          #     Service maintenance is scheduled Sunday March 12, to Monday 8AM
          #     EST.
          #     </strong>
          #     <br/>
          #     Running servers may be forcefully stopped and service disruption
          #     is expected.
        GitHubOAuthenticator:
          populate_teams_in_auth_state: true
          allowed_organizations:
            - leap-stc:leap-pangeo-base-access
            - leap-stc:leap-pangeo-full-access
            - leap-stc:data-and-compute
          scope:
            - read:org
        Authenticator:
          enable_auth_state: true
          admin_users:
            - rabernat
            - jbusecke
    singleuser:
      cloudMetadata:
        blockWithIptables: false
      extraEnv:
        GH_SCOPED_CREDS_CLIENT_ID: "Iv1.0c7df3d4b3191b2f"
        GH_SCOPED_CREDS_APP_URL: https://github.com/apps/leap-hub-push-access
      profileList:
        # NOTE: About node sharing
        #
        #       CPU/Memory requests/limits are actively considered still. This
        #       profile list is setup to involve node sharing as considered in
        #       https://github.com/2i2c-org/infrastructure/issues/2121.
        #
        #       - Memory requests are different from the description, based on:
        #         what's found to remain allocate in k8s, subtracting 1GiB
        #         overhead for misc system pods, and transitioning from GB in
        #         description to GiB in mem_guarantee.
        #       - CPU requests are lower than the description, with a factor of
        #         10%.
        #
        # NOTE: This is not a standard node sharing setup, don't copy it!
        #
        #       LEAP has explicitly requested the following adjustments from the
        #       standardized "medium" instance.
        #
        #       - The standardized "medium" instance is declared twice, once for
        #         a github team with base access, and once for a github team with
        #         full access.
        #       - Limits for CPU and Memory are set to match the node share
        #         description. Expected consequences of this is: significant CPU
        #         under-utilization, OOMKilled processes when limit is reached, no
        #         pod evictions due to node memory pressure.
        #
        # FIXME: Erik advocates putting a CPU limit is reconsidered, as its seen
        #        as almost as a pure loss:
        #
        #        - The only win I think of is an possible edge case related to
        #          inefficient spread CPU workload of workload across CPU cores
        #          that can only be partially used.
        #        - The losses I think of are: less performance for users overall,
        #          fewer users per node without being constrained by the node's
        #          actual capacity, more frequent need to startup new nodes which
        #          causes more frequent need to wait on startups, increased cost,
        #          wasted energy.
        #
        - display_name: "Devs Only"
          description: "Start a container limited to a chosen share of capacity on a node of this type"
          allowed_groups:
            - 2i2c-org:hub-access-for-2i2c-staff
            - leap-stc:leap-pangeo-dev-access
            - leap-stc:data-and-compute
          profile_options:
            requests:
              # NOTE: Node share choices are in active development, see comment
              #       next to profileList: above.
              #
              #       This specific setup is not a standard node sharing setup,
              #       don't copy it!
              #
              display_name: Node share
              choices:
                mem_512:
                  display_name: ~512 GB, ~64.0 CPU
                  kubespawner_override:
                    mem_guarantee: 462.196G
                    cpu_guarantee: 46.4
                    mem_limit: 512G
                    cpu_limit: 64
            image: &profile_list_profile_options_image
              display_name: Image
              dynamic_image_building:
                enabled: True
              unlisted_choice: &profile_list_unlisted_choice
                enabled: True
                display_name: "Custom image"
                validation_regex: "^.+:.+$"
                validation_message: "Must be a publicly available docker image, of form <image-name>:<tag>"
                kubespawner_override:
                  image: "{value}"
              choices:
                pangeo:
                  display_name: Base Pangeo Notebook (2024.10.26)
                  default: true
                  slug: "pangeo"
                  kubespawner_override:
                    image: "pangeo/pangeo-notebook:2024.10.26"
                tensorflow:
                  display_name: Pangeo Tensorflow ML Notebook (2024.10.26)
                  slug: "tensorflow"
                  kubespawner_override:
                    image: "pangeo/ml-notebook:2024.10.26"
                pytorch:
                  display_name: Pangeo PyTorch ML Notebook (2024.10.26)
                  slug: "pytorch"
                  kubespawner_override:
                    image: "pangeo/pytorch-notebook:2024.10.26"
                leap-pangeo-edu:
                  display_name: LEAP Education Notebook (Testing Prototype)
                  slug: "leap_edu"
                  kubespawner_override:
                    image: "quay.io/jbusecke/leap-edu-image:fa442ab4851c"
          kubespawner_override:
            cpu_limit: null
            mem_limit: null
            node_selector:
              node.kubernetes.io/instance-type: n2-highmem-64

        - display_name: "CPU only"
          description: &profile_list_description "Start a container limited to a chosen share of capacity on a node of this type"
          slug: medium-full
          default: true
          allowed_groups:
            - 2i2c-org:hub-access-for-2i2c-staff
            - leap-stc:leap-pangeo-full-access
            - leap-stc:data-and-compute
          profile_options:
            requests:
              # NOTE: Node share choices are in active development, see comment
              #       next to profileList: above.
              #
              #       This specific setup is not a standard node sharing setup,
              #       don't copy it!
              #
              display_name: Node share
              choices:
                # mem_1:
                #   display_name: ~1 GB, ~0.125 CPU
                #   kubespawner_override:
                #     mem_guarantee: 0.903G
                #     cpu_guarantee: 0.013
                # mem_2:
                #   display_name: ~2 GB, ~0.25 CPU
                #   kubespawner_override:
                #     mem_guarantee: 1.805G
                #     cpu_guarantee: 0.025
                # mem_4:
                #   display_name: ~4 GB, ~0.5 CPU
                #   kubespawner_override:
                #     mem_guarantee: 3.611G
                #     cpu_guarantee: 0.05
                mem_8: &medium_mem_8
                  display_name: ~8 GB, ~1.0 CPU
                  default: true
                  kubespawner_override:
                    mem_guarantee: 7.222G
                    cpu_guarantee: 0.1
                    mem_limit: 8G
                    cpu_limit: 1
                mem_16: &medium_mem_16
                  display_name: ~16 GB, ~2.0 CPU
                  kubespawner_override:
                    mem_guarantee: 14.444G
                    cpu_guarantee: 0.2
                    mem_limit: 16G
                    cpu_limit: 2
                mem_32: &medium_mem_32
                  display_name: ~32 GB, ~4.0 CPU
                  kubespawner_override:
                    mem_guarantee: 28.887G
                    cpu_guarantee: 0.4
                    mem_limit: 32G
                    cpu_limit: 4
                mem_64:
                  display_name: ~64 GB, ~8.0 CPU
                  kubespawner_override:
                    mem_guarantee: 57.775G
                    cpu_guarantee: 0.8
                    mem_limit: 64G
                    cpu_limit: 8
                mem_128:
                  display_name: ~128 GB, ~16.0 CPU
                  kubespawner_override:
                    mem_guarantee: 115.549G
                    cpu_guarantee: 1.6
                    mem_limit: 128G
                    cpu_limit: 16
            image:
              display_name: Image
              unlisted_choice:
                enabled: True
                display_name: "Custom image"
                validation_regex: "^.+:.+$"
                validation_message: "Must be a publicly available docker image, of form <image-name>:<tag>"
                kubespawner_override:
                  image: "{value}"
              choices:
                pangeo:
                  display_name: Base Pangeo Notebook (2024.10.26)
                  default: true
                  slug: "pangeo"
                  kubespawner_override:
                    image: "pangeo/pangeo-notebook:2024.10.26"
                tensorflow:
                  display_name: Pangeo Tensorflow ML Notebook (2024.10.26)
                  slug: "tensorflow"
                  kubespawner_override:
                    image: "pangeo/ml-notebook:2024.10.26"
                pytorch:
                  display_name: Pangeo PyTorch ML Notebook (2024.10.26)
                  slug: "pytorch"
                  kubespawner_override:
                    image: "pangeo/pytorch-notebook:2024.10.26"
                leap-pangeo-edu:
                  display_name: LEAP Education Notebook (Testing Prototype)
                  slug: "leap_edu"
                  kubespawner_override:
                    image: "quay.io/jbusecke/leap-edu-image:fa442ab4851c"
          kubespawner_override: &medium_kubespawner_override
            cpu_limit: null
            mem_limit: null
            node_selector:
              node.kubernetes.io/instance-type: n2-highmem-16

        # NOTE: This is the second medium profile list entry, with less node
        #       share options for a different subset of users via the basehub
        #       specific allowed_groups configuration.
        #
        - display_name: "CPU only"
          description: *profile_list_description
          slug: medium-base
          allowed_groups:
            - leap-stc:leap-pangeo-base-access
          profile_options:
            requests:
              # NOTE: Node share choices are in active development, see comment
              #       next to profileList: above.
              #
              #       This specific setup is not a standard node sharing setup,
              #       don't copy it!
              #
              display_name: Node share
              choices:
                mem_8: *medium_mem_8
                mem_16: *medium_mem_16
                mem_32: *medium_mem_32
            image: *profile_list_profile_options_image
          kubespawner_override: *medium_kubespawner_override

        - display_name: GPU
          slug: gpu
          description: NVIDIA Tesla T4, 24GB RAM, 8 CPUs
          allowed_groups:
            - 2i2c-org:hub-access-for-2i2c-staff
            - leap-stc:leap-pangeo-full-access
            - leap-stc:data-and-compute
          profile_options:
            image:
              display_name: Image
              unlisted_choice: *profile_list_unlisted_choice
              choices:
                tensorflow:
                  display_name: Pangeo Tensorflow ML Notebook (2024.10.26)
                  slug: "tensorflow"
                  kubespawner_override:
                    image: "pangeo/ml-notebook:2024.10.26"
                pytorch:
                  display_name: Pangeo PyTorch ML Notebook (2024.10.26)
                  slug: "pytorch"
                  kubespawner_override:
                    image: "pangeo/pytorch-notebook:2024.10.26"
          kubespawner_override:
            environment:
              NVIDIA_DRIVER_CAPABILITIES: compute,utility
            node_selector:
              node.kubernetes.io/instance-type: n1-standard-8
              cloud.google.com/gke-accelerator: nvidia-tesla-t4
            mem_limit: 30G
            mem_guarantee: 24G
            extra_resource_limits:
              nvidia.com/gpu: "1"
  binderhub-service:
    enabled: true
    config:
      BinderHub:
        image_prefix: us-central1-docker.pkg.dev/leap-pangeo/imagebuilding-registry/
    buildPodsRegistryCredentials:
      server: https://us-central1-docker.pkg.dev
      username: "_json_key"
