prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:TmCWc2q4Z7+/YxhOy4ajDH/GSXtjFO9DlGPXaB2ILe6mRaYz2nPeWMZ1GYZe/rrIn0mBVF0JuHyMGOyHxHz82jEr4YnZ76jmZIwMyX2uYIIeu5+lbv0t9YB7vhCurMPQc1SuWbHTYtFPY6VVEGT13sDHEphjXmVHYOwHDtjsFmYqAOQaPH7Oj9iu6s2WduaydkbIcGhG26JZoVW6,iv:0oVGojQplLf44dDdAxC8dsGyBhxqoxKV0qAj7FUFVRE=,tag:dk4jFf9XK82VG+i/HGc7zw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:HLhvGdB4kxCS5rVD3OFUqVwv7yRHdceIGVC64bS+HCB252u3ZgGgEUahH4O+REEyXO6OFh3lEjHLzNHTADvXuQ==,iv:kEnftlG1LGe/egTxYw8fulleRrWxrqb0cyiotg0j97M=,tag:f1jI1re8Mm52OHHtCtzCNQ==,type:str]
    password: ENC[AES256_GCM,data:ViQgTVxUGwf1e3/kHEu5+82IxlkCjzSGN1F4Af0hNlXeGwIMtXFjH4Yp0C4W0LgMnWWOFEzbxi1fh2K/NyuwWw==,iv:0TfsU34CeU/YJocYkNHgL/uLdDH3fcGCCRdtHxScXeQ=,tag:mHNPalI3R2K3Jte2N2h3yg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:Q7qmORWnROmEojAbGR23THNL7aw=,iv:Ao0/w6zNVRUFyD8ziP/LJ8CNa34o7mY7G7X5OoZ0yWA=,tag:RjeuZKiU5hMbHr8N5pcRWQ==,type:str]
      client_secret: ENC[AES256_GCM,data:8b9aAjQ7dyyaNGJ73/Xiov/dmfkgk1xsNvlzwB8BbkWsBaw+8ALBfw==,iv:QndpBg+u+vvjiJaEiP5PU58A9KTi/UurH0h2yJnFiRs=,tag:SQ/HVv5JhTZ002wII+2K6Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:14Z'
    enc: CiUA4OM7eJBFzcyJSvK6w1cybX/kUh5Au83nJalB0vD7PjqFbgBDEkkAZoeZpglOmDWPE2I+rgrTj5k1gHncwAVGp6HLLIgko5/z/ln5xWtLPcxPsA+6T0HvK8ByJtm2AhQKIW9tNxV2f+kF0q84uyPW
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:14Z'
  mac: ENC[AES256_GCM,data:qAOOeVG8fkH78Stl5RFviGGgu6SfWuYC22rkbE4XSk76VSkSSkCQuZQi9sqw1wsa9D63h8MxnfxvV5OVecztS0EUtarKcN86B87Gapt7sg9ckmPmzosdYwRnn340R/v9rUPRAkJxsrwG1/iXg4h/4uMaLG/dYAflMfMVmF6ux4A=,iv:uHyZh/Hcixmz36ETNFQ9OO1AuTSAN5K84V2YXEGM5rs=,tag:pNMqpCQMJZ7sW7W98YpDQg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
