prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:4asEKcAwieW1QUUURVvwcgaiPpA0X4gCpgYzzRioZjSr8I9+jgkyiTNnDSX9mtSUQLD0USM2otdCP+9w1fmUrw==,iv:FbyJFwdbfFuj4xwXxvtL9fQqmZ6IOki5GBD3mmPCMwk=,tag:1NYYwu/n6WNNEEQKLQ5SXg==,type:str]
    password: ENC[AES256_GCM,data:Tg+oklTplnnrZoFhMbbHWNMK3w8rH6hICcMvhsZsE1Uy8s/SlcoHj4EOhlsNwWrrjshaVS/9izYhZ4lnwoioyA==,iv:5xAg54ecK3Sn+rGm02JPArrqBWmND0XdQttt4Blmpa4=,tag:k063uBHJcPahG/EyTxQQNw==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:0cvqbDPt9TrVHW/NcGOYCdDOfNQ=,iv:sW+rcdGMd8oWoap+emkXp96lqMny3gDBAA+XvG87Lrk=,tag:EQlquv5bpRuIRMj79sK6jA==,type:str]
      client_secret: ENC[AES256_GCM,data:IWElZ1c4upZ/WIbo8EG4koSTRdCNnuIc8EmcYsHdBMsVAr35x1/2qA==,iv:TEvjyTJ3EL/BsDZO/PUjKof2DMADOHlH6j3TSeJOvUQ=,tag:TsYBfj7rZUq41ZMntA7vKQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:08Z'
    enc: CiUA4OM7eLFbAtUqRWOeGvQOgY95tFvugQTm2K4njjDSK+uhrOVJEkkAZoeZpunflZel0RLGOUymcAwjeD25tMns988hlFoA3qulVSXA/rKwpPfH2Uex9OyPbpShDvzLHESfmcIkX8NiB6itrhutn1zf
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:08Z'
  mac: ENC[AES256_GCM,data:SXQC5IvU3x2brJfsTRKxTCOdYU1Lwe16b+FM3IBDL4Q/8JEQUMNEWmj7FgrKgab3ikfMeI0qnbw9raLACK3Bmhv9gLFSx/lIp/re2azRD4cYDrh1zgBrJjGIWc5PlGI++3Z08gjnOyMojBmwxVR1nNAFF6mSpHbnvbZWfpBK42A=,iv:/TcA8zP7WJHFnTtLKfxie6caaoNj23oxJoq7wezaEsg=,tag:AwJc7Uf16OKHle8iVo9oLg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
