name: ubc-eoas
provider: aws # https://2i2c.awsapps.com/start#/
aws:
  key: enc-deployer-credentials.secret.json
  clusterType: eks
  clusterName: ubc-eoas
  region: ca-central-1
support:
  helm_chart_values_files:
    - support.values.yaml
    - enc-support.secret.values.yaml
hubs:
  - name: staging
    display_name: UBC EOAS (staging)
    domain: staging.ubc-eoas.2i2c.cloud
    helm_chart: basehub
    auth0:
      enabled: false
    helm_chart_values_files:
      - common.values.yaml
      - staging.values.yaml
      - enc-staging.secret.values.yaml
  - name: prod
    display_name: UBC EOAS
    domain: ubc-eoas.2i2c.cloud
    helm_chart: basehub
    auth0:
      enabled: false
    helm_chart_values_files:
      - common.values.yaml
      - prod.values.yaml
      - enc-prod.secret.values.yaml
