prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:zFsV7VKh0Olzfu2M4457MtdbTDP2eLiMwM8RSCQF2T91rgWR+9wSj6ZClfL6Ii8yZj2WNUoFatvr/djpnqc81g==,iv:HkGDRbSWH56FtZ7eU8FxqZlgaeKPm0ddjX4EnmZxrnw=,tag:qsurF0XhfLNhrqw1U4MeEg==,type:str]
    password: ENC[AES256_GCM,data:aDYsmDZy/3VEYAPQHLVh9jvQRG/anWDfrHjgXg62QFGl6Kw8t5UUAzbUWDuIc5fczEDGXh4iIipY0ACTSWvn/Q==,iv:MKZu9+MQxMJ+cHfUZ6UbDflewiyseHQ32a5pJCzBoIw=,tag:2ceQ5t3p99yUTwB0sLlNLg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:XaHIr7U9vmmIfv0n3s4AQ5aYaHA=,iv:wVJYV4F971vWzz3WU9u4p/v8feiu1m/I+FekyfV3ZNI=,tag:uy7PjidyPF9SIUBiPCBz2Q==,type:str]
      client_secret: ENC[AES256_GCM,data:YYYR6xl8sJ/kpaoKOrKAW+HkFohsfVbkrCi9iDQr0Z1WsqJ/KsLSgw==,iv:B+BgaiBqOMZ5tRBvMKP8ID5VNSoz+5d/p7QvxLByxqI=,tag:tfRdFRu95Cb1NuKDJwc8tw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:13Z'
    enc: CiUA4OM7eMm9MD5wtbJZn+S1LpMBGKdwXVMllxLhhLtFyKXBc0jHEkkAZoeZprk5zXXCCuEXSKaSOkqd7uPtovj8weO3TJZix4Q+I0JZOVmsrcNACHOXmib7zii5dbXzWPcMrdCmk7E/W5QtMuH2vPOm
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:13Z'
  mac: ENC[AES256_GCM,data:JDJC+AytXCJZDYNY3q/Bzh0cXqRKb5yEVxdQ344xG77/B9dxz/qFDmp36FDrvfjdopfcfZESf/LnbjBjEmzGhrTe72cLZ9U4hEehx3YltOnLdKgJ3M16pOU2x5PwMI0CLUIaBkEtZAXb+aILItI/fGCTSPKvwpPxrw7cpjxw4tQ=,iv:1YCtvVjYD7GPB7/k82j6t3R52TCFsoUXn7KacHI7PsI=,tag:PQHv4OHTLGt9l3ZQxEmsqA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
