prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:2RrdDJou65+HpFL7LpMTotCFsGxXzKOG6x/uWjsjovGJG6R/Jx7wgRfyXOnZe6jDf/46fyv494cvhC/U6qLnA4CpGMmg2nGz3//oWu8zfIaHMU1lLl9hkRbqoSJwhVQf4BtIfwbhOSTuEbVNkex36vATY2ZqfQ7psjGHJM2hrhxsB2IQCRy2iHuKCfsW9T31ynzMa554SlwD3/11,iv:RRQWD1+5cfI0Zy7J3pNah1SjUW4u3835Dg3LcK4ZuKA=,tag:QK4g75MnyEizwZ1Mu6Eqig==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:I1raPgF6uPNp/w5OZpWtVQ8qgBKMdcUEnXmWrKMmac844ybGbqkf5FsyOpKv1ZGg/GqPqbyglMw/8eQ7RILv0Q==,iv:LgRUp0F6W+DrOyuoIw6czbSgzf/xnIeFZ97STOPSLjQ=,tag:QMhIfWcD2YpA+1Z9CfWBAA==,type:str]
    password: ENC[AES256_GCM,data:F4cGR/JEGmC93HJLOG1v276HxQetRLUKR6I6YoHigw9eiZkVhy/yZ/T3bxG2QUtUDeBgJz0a6UiVWZ8fYlC8pg==,iv:0+LMLf50KSR/cI2xm2kd4Xyyn0beJMpQBgO4zaYflM4=,tag:s9WjpOqmTQalIyNX1ABUbA==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:ZvkBXTw5ymAxj1DoOZWIOpz9mdk=,iv:itKYy73jdxIiKQgJ43Z402rGwjd5JojYYkoUEPRb2bg=,tag:oATgFOhH5uO/a6a+cikOhw==,type:str]
      client_secret: ENC[AES256_GCM,data:iS0mnAH3yh+4HET2fBAWirmX+I7OF+t51N/TMTEZbc5cbLgJ5tCZrw==,iv:Dk79KlCItm1IK94w/XVy0S+CvdfRiHwk0uESQ7VJLt8=,tag:SX0tcxPDhQKX+QpIiqIN5A==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:19Z'
    enc: CiUA4OM7eMSlKIslN/28tLgxTkawVcEMUEk/c/NmtkWMhXpUmFI8EkkAZoeZpmT6qtO9nKT4ZYdv8EHfuunFuFgl9KJ0JyWPZvI/RZp5NY6qjZ3r0noUGBADe0DD0m/uROaJWz2N9yyxbCq3YmJgS6B+
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:19Z'
  mac: ENC[AES256_GCM,data:AFWEnMxiZX+wchmnnkngB2ex4RHhebtSsChjSQ7rL1bWSAMWgUYdb/pLpzGFbmhaT2j1jjU0R27iS52cLu5CJy9CbDwOM0CjjwbYpuzvunoBl+PjDY8c3kBQ9/1LT2Yn/N0V2txrag5VswvDG9WcTNoOxSt/ZqSWnEeT54sYn24=,iv:Sw8s8xOacRcnjOBusCRO1ypKapdlTG12h9AIerE0U+E=,tag:YxnfO19ANEjgoQLmk9uudg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
