jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:jSYPHNfO4E3S9ZIyfzO3+F2tTVnNGkJLG7roFJ73R9DZ1x8XmSOyA69DDzZC532u8k1s/X93v7VbmOwKXw==,iv:9yjcmNBnd5jICiAU1iRqvBIm+ecEkqYIMDJlw1LKWcY=,tag:kxojXN++TpKQPupOtozRjw==,type:str]
jupyterhub:
  hub:
    config:
      DummyAuthenticator:
        password: ENC[AES256_GCM,data:PjQDNdF3ldDZ+gHzowq6og==,iv:Rklx3rjpK/+m+0G6RIibTxC16iQR6m4uqXdwr1OPI9M=,tag:o4e5M61OL+iHxm/7LuKrsQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-01-09T15:19:55Z'
    enc: CiUA4OM7eGez8KDuQZXma3aE2ZS9b3HenoeE9zJDAt9k+DMfqFVMEkkAnGhyNvSoFbF+zxcX/4id6Slvrld7haauv8LWoKhnKNroAKcT7U9aEqy80YJrXAMKJeuaWBgcTZUtpulxNqhb5FltsbNX8eY1
  lastmodified: '2026-01-16T17:23:24Z'
  mac: ENC[AES256_GCM,data:i2TIv7No+2Xdump2qXxF4/0DxclZc+zLjwRDY0Mg/LnWDFWokLcJyxJ8FVUu5W0Hy9ghy/R9kVhK+oXsjpZ1M5ENtDlT+hG9NPq9VkfcCydQ3FtycbOezNBAl30le9iH6jdPV4ptelEAAjet2gpvwWbRD+FKAT+9PEPQlqH8MqM=,iv:hNqMk/2uNCO4E7fILH9mXYIQZarof8J9g93RDR/zm0I=,tag:P6dQbUhu2t/ZDR7fNcSaxQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
