jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:RSQI+M1M/yjnLp7czEx8UGoPraxMnliRaqdZ/ALrSrWlQBIem+KRWyAfe4O0u9okQLWclPOI1TNsP6Z+Shfw5bWve9cJNUlEtJ+HWz2+wgT0Z1kOWPfRv6W1X1WEhVRBT1J3XzFT5OFERc9yV9Z1/KDFR1uscDrPol/u7cwioQPEz9mzpKayxvZKw1zfS1EAuw==,iv:edMLW5+rtLiy+uCZ+fnyYBxLIehQAMPqIwM4CUZkHho=,tag:Q47xJF2YshoXMPSfP99hGA==,type:str]
jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: ENC[AES256_GCM,data:/kx3ZC05GIXwvPngSXU5bTZlW88=,iv:SysDo0MWDX8L9nJJm9iK0bC6L3sY6rVOruhvWXxxc/U=,tag:wHnei2oDrTs4FYEfUPsrlg==,type:str]
        client_secret: ENC[AES256_GCM,data:k1/UQcpZy1bqGxNN4GCDfK2Sxi2gOWevayLgc7lVaeQxbAuXlEuBRQ==,iv:KFgWlOqHoYAcNg8CT01euin76bSFQTbE5jFt3pi/VFY=,tag:RvDWgDYxlb47Bmo6IiDJSw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2024-09-10T10:21:22Z'
    enc: CiUA4OM7eIftbT461fRG4hTcQaNbGW6CXYmRwcmigijBFNx9Qfc0EkkA5dG1Q1Xe5O/suc94v4uBQ7b+F2ZsYZiI8HuR0qpZaY1P1MRUxKQ9YmXcX5AjCg0bEJ52XWnQHq5QV5zn+RvR13sk6yzdAvO+
  lastmodified: '2025-11-13T17:18:48Z'
  mac: ENC[AES256_GCM,data:6neZ0Ri262sFF+23R5gbstGKSJLVT+540jRwpa25iuiloRvDYy/ToUAZES+63ldfJQhD+pgBreptrUDJOvip9i73b5cZ1yelGtf8YWm2i37v8klC2R24J0k0mu+2e5Bfyw2DotE4hm8vofzGr0oDe2fUreeu6JYwvZ9xDLFdqEE=,iv:jgmPyeefUhei64xmR+UDZJfzWilP3e1KYq3k+0VVCYQ=,tag:21pmQZh6Mc07Hz7wbqkRuw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
