prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:VeSADMUApDWMBq41X22og4m1AdNgMDpoxTA25mU+2t2xGi02+GoOnHYxqB+EFVtx7jIER2ZR0tUXt0wZoaRqcA==,iv:XSJiVJ2Wd6ghg+/lpMhVuLr/UK2u8DdiEsF867Bvq78=,tag:3ypmFOUo82D8aog3U50oWQ==,type:str]
    password: ENC[AES256_GCM,data:JDYJxhzmyegMJvzn+feKCfvtx165u8cCY1CKOWgQJhKjSR7iMMaJaaJYSIb8s6VknPA7tWq9Gj2jTRdY/APOXA==,iv:B4CyGG4arT0as+nP2w3pJisV3aghV/rynnFHvl9t0ag=,tag:vX0hQ5CM5rxpAlnWHYIpuQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:d4OA1lqe9rll7JNVpFHA9vYH0wA=,iv:m/R65P8e6UkSan7AVgG/QFuD/Ncc+e2JMq4C0Mt0qPU=,tag:rInI6wavcodlWmK/APcjGA==,type:str]
      client_secret: ENC[AES256_GCM,data:/DUNGWiTavGcY8wgf62eQPpqsbXC2Nn2MFTXB8LZDc28taOWrtWjVg==,iv:uWbsdzvJ/SmRMnciPlntRmIuemxqdGqogEdYSLf6Qx0=,tag:bAw8txqakB0rQLhbqATDKw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:01Z'
    enc: CiUA4OM7eCYA1eewr8g+zANAxt1aD8ZYYsgadAWCTILlAn6o0bWGEkkAZoeZplBAhTQ10Sos0f1yZ7J3+eeur8UymPznbtewKrzoNl7uhDb3IxP41GKF3R6y2P8w9Hy0PgyxlWLtLOpsUpkwV3LtKeuf
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:02Z'
  mac: ENC[AES256_GCM,data:C7Oex4KAhwIFm4L8MrMnTdqdWBv/6t+mA9v+0XZ/SLl8NJAvbW8MYIuHBFk3DTrkV+JAwNkl9bUTg1Ft7KliT9Lne7gISw4Gtb4ZF7kE6nYPzByNnOHYylA7/KI4uRiAnJt6JIjA1KmBJ4ipaYfx6iSCquFlqRwlQM/UixbyNds=,iv:ch8iYcHozFTQri/9+E9b3jr2ICTxnyB0WIT7I7Gxxzk=,tag:IVwcnGDg+6mzjZSBPmOOIg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
