jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:jSYPHNfO4E3S9ZIyfzO3+F2tTVnNGkJLG7roFJ73R9DZ1x8XmSOyA69DDzZC532u8k1s/X93v7VbmOwKXw==,iv:9yjcmNBnd5jICiAU1iRqvBIm+ecEkqYIMDJlw1LKWcY=,tag:kxojXN++TpKQPupOtozRjw==,type:str]
jupyterhub:
  hub:
    config:
      DummyAuthenticator:
        password: ENC[AES256_GCM,data:JUaPwFr/3A==,iv:qYX7ooj8M7Ssp7CH5el1yXSoOD99yqLfcZD8frDWImw=,tag:NWNIu6axD8FPDiEs2o56bw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-01-09T15:19:55Z'
    enc: CiUA4OM7eGez8KDuQZXma3aE2ZS9b3HenoeE9zJDAt9k+DMfqFVMEkkAnGhyNvSoFbF+zxcX/4id6Slvrld7haauv8LWoKhnKNroAKcT7U9aEqy80YJrXAMKJeuaWBgcTZUtpulxNqhb5FltsbNX8eY1
  lastmodified: '2026-01-19T16:47:01Z'
  mac: ENC[AES256_GCM,data:AFDge+505PwfAzccXfS8LVNTOjkT2v5AUoY6IUz50sieh+Ro+i8ikCCUzCWN998bn+1XryZq0CcIjL8+xE+f7gnZczLn9jq+Z7lJpvNM+YytO4YDXlg/QUMAz+1zajJiZ4+y/+cclP5kAFE/2mlijeHjNJWx5sfJojA6HsoEBQQ=,iv:USO4qCH/IQw+Yc8vtjkDZPEedQdkKc2ue2kvKKwFbc8=,tag:Vvec06CnPRuJzisEPeSRpQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
