prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:f8lY928i4TKCdoxC0pu6UMbMASWI4ycIuNX+/JtZL3zz+uaMQYpp/5/qtt6Hz59Js0ZMd5TDAQGZiPOfy9o0wtoOyVSPgNQnOSGXu6Kwau3eUzqt8Hwo+EVhlcHPb4C54OFgpKkTDYpIltRgaizVIc1FPncUqUBICFQBmEjHHpbZhxEzuUh4TEFnuVGy6LsuEtpu/UydEtf7YNRD,iv:BeXof0+xXY6XHovqnPICfmTA8TFOCyfDlFIY4oK+0Sg=,tag:oQQXFOHQWqF9844iGGpbOw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:90K8JMI+C4BPIUJA1etuBAjj6r1lz/cmy13GiEiGtVoufCOYFAfpKAK6gCS2DbvSqhaZMlP8Pn+NFFeID46qPQ==,iv:eIaToK1dzSaBpIbFTmJTy2ZMhAg9xGjp4G9+o5cPhsc=,tag:IbT8DTukdcQrvH9TmphgBA==,type:str]
    password: ENC[AES256_GCM,data:kGtDvk/G/mLl5djNDpq0Dk6cqIS+QoIGV5YQ+sGtSkD9XSsAaKaSmz0vb2fEV3vVxIqnSQKhG5+kc2qVU5O0zg==,iv:TOVFOBLvcGIlDqXOo6Ce4ipDcCVE4zD2NF69i5pWIWw=,tag:Db17sQ3sIEoAY0scs7VlnA==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:rT5XoRffAdIt9Y4C0LLn7KxxV7A=,iv:NpeBjSJwizoyXYR5DLmWEV2hGK3zaQ5A22wBIy0cn88=,tag:wC2VK3ZmAFJPy0g2+ZElrw==,type:str]
      client_secret: ENC[AES256_GCM,data:HSk5+83TGAqfM82q96A73pQMTDpSbqXf2wBjha7pGpi187vcvtsPqg==,iv:8RbA/U5i32m7sNBZSgyZ4Hz9Fp0KtVrxKA3RzBCobW8=,tag:7lJ9szGVupSsPLgv1R6X+w==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:07Z'
    enc: CiUA4OM7ePFi/xf5v470rIDWU5UyY+ACoo8zOm7ZEy89pLMlr/JiEkkAZoeZppGR5p+O2GE3/Vr7LmAiS47pr8w8ic9Jr99HpMw2eDRHZZgfl+vsi7XcRUuhLexE81dX2XWOqgAehIjI/knuNw5QXL4o
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:07Z'
  mac: ENC[AES256_GCM,data:dtmLUz4VTRSoBwlFzwaCSl64jq1kZWTTOr4pV8F8WI3G+LZTmVs7pMdwvvz17YoQZLCeGLGiRT0e/8YiUZ5QnRYj28eOwohlB2NtIy6kx0e88ii9Szr4Hxfq0equ2gXevCp4EK7doEjvfzyGLFDbLegXbooCPSgsM4+MLKXthRo=,iv:sHvb06FwLH2Yk3I9JZxH6l8pEtV18vIWSmeHWuhmR94=,tag:IQeT2bR1AsVaDFR5L39hwg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
