nfs:
  dirsizeReporter:
    enabled: false
  pv:
    mountOptions:
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - soft   # We pick soft over hard, so NFS lockups don't lead to hung processes
    - retrans=2
    - noresvport
    serverIP: 10.100.33.250
    shareNameOverride: prod
jupyterhub-home-nfs:
  enabled: false

userServiceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::891612562472:role/nmfs-openscapes-noaa-only

dask-gateway:
  gateway:
    backend:
      scheduler:
        extraPodConfig:
          nodeSelector:
            2i2c/hub-name: noaa-only
      worker:
        extraPodConfig:
          nodeSelector:
            2i2c/hub-name: noaa-only

jupyterhub:
  custom:
    2i2c:
      add_staff_user_ids_of_type: google
    singleuserAdmin:
      extraVolumeMounts: []
  ingress:
    hosts: [noaa.nmfs-openscapes.2i2c.cloud]
    tls:
    - hosts: [noaa.nmfs-openscapes.2i2c.cloud]
      secretName: https-auto-tls
  singleuser:
    initContainers: []
    storage:
      type: none
      extraVolumes:
        # We include the dev-shm extraVolume as the list of extraVolumes from base hub will be overwritten
      - name: dev-shm
        emptyDir:
          medium: Memory
      - name: shared-dir-pvc
        persistentVolumeClaim:
            # The name of the PVC setup by nfs.yaml for the ephemeral hub to use
          claimName: home-nfs
      extraVolumeMounts:
        # We include the dev-shm extraVolumeMount as the list of extraVolumeMounts from base hub will be overwritten
      - name: dev-shm
        mountPath: /dev/shm
      - name: shared-dir-pvc
        mountPath: /home/jovyan/shared
        subPath: _shared
        readOnly: true
    nodeSelector:
      2i2c/hub-name: noaa-only
    extraEnv:
      SCRATCH_BUCKET: s3://nmfs-openscapes-scratch-noaa-only/$(JUPYTERHUB_USER)
      GH_SCOPED_CREDS_CLIENT_ID: Iv23lie5oLneHExwicr2
      GH_SCOPED_CREDS_APP_URL: https://github.com/apps/nmfs-openscapes-noaa-push-access
    profileList:
    - display_name: Default
      description: Choose image and resource allocation
      default: true
      profile_options:
        image:
          display_name: Image
          dynamic_image_building:
            enabled: true
          choices:
            python:
              display_name: Py - NASA Openscapes Python, Dask Gateway 65d6916
              slug: python
              kubespawner_override:
                image: openscapes/python:65d6916
            pyrbase:
              display_name: Py-R - py-rocket-base image 4.4-3.10
              slug: pyrbase
              kubespawner_override:
                image: ghcr.io/nmfs-opensci/py-rocket-base:latest
            cryo:
              display_name: Py - Cryointhecloud base image latest
              slug: cryo
              kubespawner_override:
                image: quay.io/cryointhecloud/cryo-hub-image:latest
            asar:
              display_name: R - ASAR Stock Assessment
              slug: asar
              kubespawner_override:
                image: ghcr.io/nmfs-opensci/container-images/asar:latest
            cefi:
              display_name: Py-R - CEFI image latest
              slug: cefi
              kubespawner_override:
                image: ghcr.io/nmfs-opensci/cefi-image:latest
            pyrgeo2:
              display_name: Py-R - Geospatial + QGIS, Panoply, CWUtils - py-rocket-geospatial-2 latest
              slug: pyrgeo2
              default: true
              kubespawner_override:
                image: ghcr.io/nmfs-opensci/container-images/py-rocket-geospatial-2:latest
            coastwatch:
              display_name: Py-R - CoastWatch - coastwatch latest
              slug: coastwatch
              kubespawner_override:
                image: ghcr.io/nmfs-opensci/container-images/coastwatch:latest
            aomlomics:
              display_name: Py - Tourmaline Snakemake workflow for QIIME 2 v.2023.5
              slug: aomlomics
              kubespawner_override:
                image: ghcr.io/nmfs-opensci/container-images/aomlomics-jh:latest
            iorocker:
              display_name: R - Geospatial w sdmTMB - r-geospatial-sdm latest
              slug: rgeospatialsdm
              kubespawner_override:
                image: ghcr.io/nmfs-opensci/container-images/r-geospatial-sdm:latest
            echopype:
              display_name: Py - Echopype with pangeo - image-acoustics latest
              slug: echopype
              kubespawner_override:
                image: ghcr.io/nmfs-opensci/image-acoustics:latest
            arcgis:
              display_name: Py - ArcGIS Python 3.9
              slug: arcgis
              kubespawner_override:
                image: ghcr.io/nmfs-opensci/container-images/arcgis:latest
            vast:
              display_name: R - VAST with TMB - vast latest
              kubespawner_override:
                image: ghcr.io/nmfs-opensci/container-images/vast:latest
            pace:
              display_name: Py - PACE image with OCSSW tools
              slug: pace
              kubespawner_override:
                image: quay.io/pacehackweek/pace-2024:latest
          unlisted_choice:
            enabled: true
            display_name: Custom image
            validation_regex: ^.+:.+$
            validation_message: Must be a publicly available docker image, of form <image-name>:<tag>
            kubespawner_override:
              image: '{value}'
        requests:
          display_name: Resource Allocation
          choices:
              # r5.xlarge
              # [[[cog
              # from deployer.dev_commands.generate.resource_allocation.generate_choices import choices
              # choices(["r5.xlarge:5"], "proportional-memory-strategy", default=True)
              # ]]]
              # [[[end]]]

              # r5.4xlarge
              # [[[cog
              # from deployer.dev_commands.generate.resource_allocation.generate_choices import choices
              # choices(["r5.4xlarge:2"], "proportional-memory-strategy")
              # ]]]
              # [[[end]]]
              #
    - display_name: NVIDIA Tesla T4, ~16 GB, ~4 CPUs
      description: Start a container on a dedicated node with a GPU
      slug: gpu
      profile_options:
        image:
          display_name: Environment
          dynamic_image_building:
            enabled: true
          unlisted_choice:
            enabled: true
            display_name: Custom image
            validation_regex: ^.+:.+$
            validation_message: Must be a publicly available docker image of form <image-name>:<tag>
            kubespawner_override:
              image: '{value}'
          choices:
            pytorch:
              display_name: Pangeo PyTorch ML Notebook
              default: false
              slug: pytorch
              kubespawner_override:
                image: quay.io/pangeo/pytorch-notebook:2024.11.11
            tensorflow2:
              display_name: Pangeo Tensorflow2 ML Notebook
              default: true
              slug: tensorflow2
              kubespawner_override:
                image: quay.io/pangeo/ml-notebook:2024.11.11
      kubespawner_override:
        environment:
          NVIDIA_DRIVER_CAPABILITIES: compute,utility
        mem_limit:
        mem_guarantee: 14G
        node_selector:
          node.kubernetes.io/instance-type: g4dn.xlarge
        extra_resource_limits:
          nvidia.com/gpu: '1'

  hub:
    config:
      JupyterHub:
        authenticator_class: cilogon
      CILogonOAuthenticator:
        oauth_callback_url: https://noaa.nmfs-openscapes.2i2c.cloud/hub/oauth_callback
        allowed_idps:
          http://google.com/accounts/o8/id:
            username_derivation:
              username_claim: email
            allowed_domains:
            - noaa.gov
            - 2i2c.org
      Authenticator:
        admin_users:
        - eli.holmes@noaa.gov

binderhub-service:
  config:
    BinderHub:
      image_prefix: quay.io/imagebuilding-non-gcp-hubs/nmfs-openscapes-noaa-only-
