nfs:
  pv:
    serverIP: 10.100.19.201
dask-gateway:
  gateway:
    backend:
      scheduler:
        extraPodConfig:
          nodeSelector:
            2i2c/hub-name: workshop
      worker:
        extraPodConfig:
          nodeSelector:
            2i2c/hub-name: workshop

jupyterhub:
  custom:
    2i2c:
      add_staff_user_ids_to_admin_users: false
    homepage:
      # Remove once https://github.com/2i2c-org/default-hub-homepage/pull/51
      # is merged
      gitRepoBranch: unify-logins-2
    singleuserAdmin:
      extraVolumeMounts: {}
  ingress:
    hosts: [workshop.nmfs-openscapes.2i2c.cloud]
    tls:
    - hosts: [workshop.nmfs-openscapes.2i2c.cloud]
      secretName: https-auto-tls
  hub:
    allowNamedServers: true
    config:
      JupyterHub:
        authenticator_class: dummy
      Authenticator:
        manage_groups: false
        enable_auth_state: false
        admin_users: []
  singleuser:
    storage:
      extraVolumeMounts:
        1-shared-public-volumemount:
          name: home
          mountPath: /home/jovyan/shared-public
          subPath: _shared-public
          readOnly: false
    defaultUrl: /lab
    nodeSelector:
      2i2c/hub-name: workshop
    extraEnv:
      SCRATCH_BUCKET: s3://nmfs-openscapes-scratch-workshop/$(JUPYTERHUB_USER)
      PERSISTENT_BUCKET: s3://nmfs-openscapes-persistent-workshop/$(JUPYTERHUB_USER)
      GH_SCOPED_CREDS_CLIENT_ID: Iv23liopQ2cWF2zW212t
      GH_SCOPED_CREDS_APP_URL: https://github.com/apps/nmfs-openscapes-workshop-github

jupyterhub-home-nfs:
  eks:
    volumeId: vol-07154b7def3b80b96

binderhub-service:
  enabled: false
