prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:aG3ajGh8sP5arfWstAQABLdn4opjW/Sx9QlsV6ZgZZo/4tup8UgzQg8qlN1l6RNCW/Vh9axuD+fFX6Pfm8MvCrYL9jqSPatGY+rBqc9EZ+GtMWpwpAcK7LkhhTdDPuxZwSvMKiZqciFVbmzbZQe9JRxgNQvzZYTj1BJGNaTdWjjuB9z0+jxvRR0pQQeejNSlMWZSduslX5SSEuI0,iv:ZmYyEMw3Xh0qORDmOQ2jU2328OGo11N+xw+WFjgtKm0=,tag:B176yht0HwNFDsGmGvPsyg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:fxteSLtdbY8PW47BxADv9++A75iGBafLYjqkUBRqcZeocTiDo1EQqaq6IQFdSWkKXKFN6PINohPIFi/zJiRvLQ==,iv:hVHMPY/pSpK3ho3VhU5i4A+Od/0FMapVdjE8/GuPCUY=,tag:XvehRcfYe+fraUlgkUgS+w==,type:str]
    password: ENC[AES256_GCM,data:X3fzuhbpz6kAiyr2fzuJcutCIQwwceecEdT8ya0LRZDVMVyL/oRqMPccnbNyJXMdEJyihlEoKanQXaP7xRcdjg==,iv:r4Jh8ScQ7Um0AMn/DxVHtRutSp9c/s7rdZIL6f6WDdk=,tag:Zah9ziSqIIuKGLTuILulGw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:09Z'
    enc: CiUA4OM7eEju90qh3CXeIGvf4tLfpBfhurqOCw5y5M5pMj71O0wWEkgAZoeZplvd6cpNM7+tFtZRxjOX4wqCcheYLUjVadVoKsLzvgxFTGk8IyyuMSps1imHOTsm1u7umS3EjbX9p6q9jIZM+9iorEE=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:09Z'
  mac: ENC[AES256_GCM,data:dCY869uwEeoy0NONbLSr/OpFA6RYkzrtBKG8eUj0rXrUwV+uRAdJrV3+uANB5CdQQTrHx1G6ML9lQ6R+Dh7f7M4fkCHM9DYwZ0JG5QsHeZ15+N0XjDt88nkVVsw850uuYYAWQdGzEr1SKVQfyQbW5AwISf9MAFXtfC/XZ8q7dCE=,iv:N6QM5duYHMbFHLyhOWKDKeFCx5UJLgEuhPNhr8cfN3c=,tag:L2XKruRbIrRM9aus0kby1A==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
