prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:R0342+3/nfvyPxUaORZ3aQLSIP7tzCtzZP6KB+jH4LSJ+WXtWdONLDFTuqEReLbfsGF2BIf5B0WnPDJUUJepxA==,iv:F5R3//MMS/0n9VZzjsnSq7S+3a5Fig+//arfJFFoWEo=,tag:9soeUKagXMq9SSQEo8rO8A==,type:str]
    password: ENC[AES256_GCM,data:4Do/e/3gBQcmemRvh5aZ7Ow1GENRrVnbFDoKWkp9iZRgn5vd7QqfhM6keHHI5psLjCKyVx8O2/AdC5aVCX7A4g==,iv:5Ap8C4TmwfPqfEvxlncXMscPzWQ3rmWt974SqBxUvAs=,tag:D0U2tJn1wvGuA5lFI1fe0g==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:03Z'
    enc: CiUA4OM7eDiGmKQLtexiMBAtFZSXnTcEF8l+Eesfyg+M67enoqWpEkkAZoeZptL5DhsgWRsTeItibVDnDZhj7N0I0R+rGJFVab1s/zd9RIxW2Qc8gJxz7+8xX25L0EgqgJp+3m2MNjT7vkhgKxv2sb0H
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:04Z'
  mac: ENC[AES256_GCM,data:ZqVMHqvg9kHA3iag7ZeTJ5JVyLeXLofTNWakCpzOajF0aUWHKXqHLZYpSN+dQrZl3eurynREhwBoi0C63xh8ElETe1VoLFnUCsM2Erzbs99rDJqkYxcELGJnAlQJOovg5/6HzJo5boy5xfaZy2RjZdXZtmZcyIKxeKUdwPngK6s=,iv:iz6qyEuvlMJqEeaq2G7YypAsdZoF79G0p9D83uF60Q0=,tag:yfHmdjynEh9hh3mByXqe4A==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
