nfs:
  enabled: true
  pv:
    enabled: true
    # Recommended options from the Azure Portal UI for mounting the share
    mountOptions:
      - vers=4
      - minorversion=1
      - sec=sys
    serverIP: 2i2cutorontohubstorage.file.core.windows.net
    # Trailing slash is important!
    baseShareName: /2i2cutorontohubstorage/homes/
jupyterhub:
  scheduling:
    userScheduler:
      enabled: true
  prePuller:
    # hook prePuller shouldn't be enabled when configuring images in any other
    # way than singleuser.image
    hook:
      enabled: true
  custom:
    homepage:
      # Everyone hitting the home page directly is redirected to
      # https://datatools.utoronto.ca as the unified home page. The various parameters
      # here under templateVars are no-op - UToronto manages the unified homepage themselves.
      gitRepoBranch: "utoronto"
      templateVars:
        org:
          name: University of Toronto
          logo_url: https://raw.githubusercontent.com/2i2c-org/default-hub-homepage/utoronto-prod/extra-assets/images/home-hero.png
          url: https://www.utoronto.ca/
        designed_by:
          name: 2i2c
          url: https://2i2c.org
        operated_by:
          name: 2i2c
          url: https://2i2c.org
        funded_by:
          name: University of Toronto
          url: https://www.utoronto.ca/
  singleuser:
    cpu:
      # Each node has about 8 CPUs total, and if we limit users to no more than
      # 4, no single user can take down a full node by themselves. We have to
      # set the guarantee to *something*, otherwise it is set to be equal
      # to the limit!
      limit: 4
      guarantee: 0.01
    memory:
      limit: 2G
      guarantee: 1G
    extraFiles:
      github-app-private-key.pem:
        mountPath: /etc/github/github-app-private-key.pem
        # stringData field will be set via encrypted values files but added here
        # to meet the chart schema validation requirements without the need to
        # use secret values during the validation.
        stringData: "dummy"
      gitconfig:
        mountPath: /etc/gitconfig
        # app-id comes from https://github.com/organizations/utoronto-2i2c/settings/apps/utoronto-jupyterhub-private-cloner
        stringData: |
          [credential "https://github.com"]
          helper = !git-credential-github-app --app-key-file /etc/github/github-app-private-key.pem --app-id 93515
          useHttpPath = true
  hub:
    db:
      pvc:
        # Default seems too slow for our database, causes very bad response times
        storageClassName: managed-premium
    config:
      JupyterHub:
        authenticator_class: cilogon
        concurrent_spawn_limit: 100
        # We wanna keep logs long term, primarily for analytics
        extra_log_file: /srv/jupyterhub/jupyterhub.log
      CILogonOAuthenticator:
        allowed_idps:
          https://idpz.utorauth.utoronto.ca/shibboleth:
            default: true
            username_derivation:
              username_claim: "email"
            allow_all: true
