jupyterhub:
  singleuser:
    image:
      name: quay.io/2i2c/utoronto-image
      tag: c2d316fa18d9
  hub:
    config:
      Authenticator:
        admin_users:
          # 2i2c staff below, a list maintained in default-common r-common
        - yuvi.panda@utoronto.ca
        - georgiana.elena@utoronto.ca
        - chris.holdgraf@utoronto.ca
        - davidy.liu@utoronto.ca
