prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:3o8xVvSZqgC4cbbiCUd+4DTrIC3mue9b0qZQfrFaAmuPM2uys4dZtCRa7j3tOlooAviGBdT70KuTeAe7C8eeXg==,iv:yJOPiyby2gmGvCO3VPMvSX7W8+KgIcW/V5RFjbBa/GE=,tag:3MzYDDcQi0533HNnIbufBQ==,type:str]
    password: ENC[AES256_GCM,data:GbA2I1m+bxelacV+82Wvgzf6iN7m8r8+c6YxyOpBLEH7r09mrY1C0tgLyq1CxoYpEXBObkTVWC7Y3K479MBSWQ==,iv:1DHOIG1wo8KRoj0hLKnG0sA33KYjXXth1yI8p2jBrrA=,tag:zyzJaDNZ1DJbIKGwh13eTw==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:42gJ822jVWTBKvVYnsZ+iRdFq3k=,iv:tX/ZA9lThJ0NteG3j8hnQLwLkCke8v3LqhDzZ6Dffis=,tag:y+YSQVf5R6p5+PUjQ8E8lA==,type:str]
      client_secret: ENC[AES256_GCM,data:/44rf8Cb/MEuxfYN0ac1rratIBpwOVnpVrzftsqi2wNzdxLgd7qiHA==,iv:taVOa3gteara8Kc/pUxxcvpjhY3LVsIRL+XP4Q7Nyds=,tag:B6tszQySqZURa43CTpRQCQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:06Z'
    enc: CiUA4OM7eJ3ON7258tE/JpFzyDw2aA6+5xcmMqN50Tz7qR8V7IedEkgAZoeZpqrmJaA8qj53Cf0yv0K3KwE3NjMErN5mA/2YL9FQ2lPKLaYTxEyExI2uEyuwH5i5ahxJbzBqnjZVJ2kzwsr+VUnqZF4=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:06Z'
  mac: ENC[AES256_GCM,data:VV/+Xm7bQEsfS1zSg+ldTGiGDDXP6i8Qxx6tw3sUZ/beCaudgDc0YdAsww4TumTz2+rXZdCrOYAblR41yy86+2BzzOWr0IAENu/kkM6jJFQxYArVNbV3RPeqga4KrKiY7k+06zKcUrmspy9NahHQd1l+iLBCzL6qRtPvwk1BkGk=,iv:sxE7OaHCzxvwWZ3eeRHiKy/qhRCTGXm5ak60rqizumw=,tag:Q/8WHHrxK1O76l5JVK/V/Q==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
