prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:heliedz9McOfCuVmO50hd8hwXhnZpEdmOAb4wjg5IEp5nCtcyAc4hUMHlLe/StLj3QgtCnXzoFGh2uuOCeID0bmB+D7xfv3ioCmnSCreFhzw/PesWBKH4iXHUwaB2h+iQCHH9zmMtd7eJsvNyyAEFn2eCmAiUs48yMsqqLgRlIsmCD7WMq41PmuKk/IfIO5cdda7Y+2/VsSQ+NY3,iv:FWRz3s+INQ+Qjkyt+y9joVGb+PIL0jpsnkLPQaxv8zQ=,tag:werONNIIEt7fJUFerV8+aA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:wEGZkFbubc2islzyrRVDe+NXy5hXVRnsUQG6FrKVTsP9LnNhZ53M8QSEtZ1WwAghy9pkg1sGL7HLO36NV9xP6w==,iv:2DAnBnV3WpyR/lCOr4ED7kRqI2srJcj/eYYpaE0oe8U=,tag:bVJSfwn4kTfBBYGmYUrDVw==,type:str]
    password: ENC[AES256_GCM,data:aceEa79zeeHt9hK4lvoV2FH32pqQrBp+mn7/3FvXo0iTcM00Cm3WenoFBSWq+dv//MSNEwTfn5VFhYSZP4ps/g==,iv:tU6c8R24CLp34tXzIPuxavsGaJ0i9ahwWIEQlf8beC0=,tag:Ct2v7dkyB66Rjdf+zQmx9w==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:MFCkkaU9Gg8O0SqyEnhDUQ673gU=,iv:FudpK+LhscgdCR0PokEPA/rSK641iWk7NcAT2hTLWkE=,tag:se6nUJQGOYDD5+t5j02/fQ==,type:str]
      client_secret: ENC[AES256_GCM,data:eBRxF2L1eP6hMb6ZXLJDakW/LFAE5mCs6r8tJMvaG0YB17hyFPxytQ==,iv:mDsdvgpgjb0Y00QOqYDHEzF1XInXQCQPGu7wk5QoIHk=,tag:jaA8Ln+TNm0efqaYReoN9A==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:12Z'
    enc: CiUA4OM7eHdHH5NoXOVp1zwGlKIvG/E0UpjjkAdSE7epjs+eVmO3EkkAZoeZps/GE9EqYov3tY9v7cZ9rdL9UeBUoNDbMM/GuU/9tqXeq0ibjuumcnkenCqOcgwyyylfnHoYIWqJ1XnVkx6glkjpgVh2
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:12Z'
  mac: ENC[AES256_GCM,data:cKL721fPd8tIN1GbkElT+gqFkD4s7v6OksAW38b2U0fOsBXEUF13MVd4vKLpTuwO1+6+C8Q1MHNBSccj6ZrudpqyZSZ4oEb4pTS71kCSgt2JWSP5yJWyK1lcMM488xKoDf4rl/IET0ioxM7mQwpUMr2aZrf9QoSn6X7pyBuYpWc=,iv:5U9PXpYYb9W91Lu4RWRcpDBngq5UnXR9LyYGS5ELS/I=,tag:UWLjK/DwdQKK+I6cUG0uuw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
