prometheusIngressAuthSecret:
  enabled: true

prometheus:
  server:
    ingress:
      enabled: true
      hosts:
        - prometheus.utoronto.2i2c.cloud
      tls:
        - secretName: prometheus-tls
          hosts:
            - prometheus.utoronto.2i2c.cloud
    resources:
      requests:
        cpu: 0.5
        memory: 4Gi
      limits:
        cpu: 2
        memory: 16Gi
grafana:
  grafana.ini:
    server:
      root_url: https://grafana.utoronto.2i2c.cloud/
  ingress:
    hosts:
      - grafana.utoronto.2i2c.cloud
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.utoronto.2i2c.cloud
