prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:FIlg59UaWMecx0e8wOoCipZ43GrZxaCvp4ayFvGsb5Xauk7e+re7ZYF2wrO7CtzBUfWzK4rSCxKJ2C9uoDRSSQ==,iv:8uooNTiWKp/bFNvf/zJrb3dBmeI8vHpFeo1jH3xGd2c=,tag:JPVWBS9z7jhSxhAeszlASg==,type:str]
    password: ENC[AES256_GCM,data:CCTZDoz9xoWMJp2JYV/oKv2vUGVyEo1KgXjiR2Z6r0kRfS3crB7TnH7I3HoHeNRFoxv18+vmSKICggStuKCi5A==,iv:hIOinWnQqZ/iwnS3gnG25hb9BBtrw9YkxLxKXYpfRfw=,tag:McUcNIdEcUCSbth1CqooXg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:40:58Z'
    enc: CiUA4OM7eE/u4fvkkAwRGhz1VtOTpIdsCbTW9YUnA8eaNGWleFUCEkkAZoeZpnD1FSMdgBoTDNK7KGGbNLlpNkHTPecZUlUW7Ls9ke1nwsu61/Tzk1zNNPw2yWEcJX2e4VxFR/6rvvC2pPm0yPRnRGW5
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:40:58Z'
  mac: ENC[AES256_GCM,data:IzflrDzF/f+qDZSq9uFZ2gjUGVeQiZAZTM++JzoMTXdkENwIWPUVmbZhrP6dqZfHCpOZfhuCBZ9rHfmmbL1vhS54cONPHGA2SOlhGqHwPmCizkOJJAntcc+XQoxfCJtn2OoMHR0Fsj0QIvInkW+Wm3buEDl7kL1Qs5vr4bX/1aI=,iv:BJgcxMxYm7CctOXynINbsFAN14PN2CMRmvticKYtRVE=,tag:QgVlo48UgFNlelLeL3OBGA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
