prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:Yz4tMg3ZWQ99+R5hWAuS/90rhG6H10M4Dd8ZfEwSSxF/N990YLqzcjAaWSI+F2S1uwCr+w2wGypbJ4V1sy0tLG2qtba0JQuCU+X/8+gj9DSO7hPYU1j72tGoZaa+wl6RG/enVuv6JQUe0J8dOkDNoOsWQLr7mScO6nLE5CDiQA8wlbGEAGlWvfi/FYZKAK09S61dgPNEbN6m4+bE,iv:xQ6t8YW0Mz2bterE80ZtOTSIoWmhzUHRsbCLCa1/Gic=,tag:mVJ6RdAm50pIQlfnPkhCQw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:uNwkS54H3rzaO/JtVdG2jeIHb8w5aLB7VqTDb6cdDUJ3VDOZDZROcNZjcNVmXgjESmncv1lix09MUsI1DOFgXg==,iv:/BOtpanVNZeMvERs1KvOm7zr/fD1AWJF0VjmKDsTDFc=,tag:Qx5tM/2iSBMMcxta6nQzbA==,type:str]
    password: ENC[AES256_GCM,data:Nd/eV4RbUe934uPap1mKQdTG43kxGE4pepcm/bGhMyEY8lTkl1wgNZMNXe+hzuhvtJ2K+x71SL8l/Qo+bfJ7bg==,iv:muC3oN1d3a00n0LOis7sX6HdF2mpluDfGG3rcapGKY4=,tag:n0jCISTJlYpKRNTiRc6Y4g==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:04Z'
    enc: CiUA4OM7eBSy/DD0LT7IItj9gafXhbbp1DT+/LcXvnoYK07I5IMkEkkAZoeZppv+gMxqnKkmSxkxlx2YUddNTAuJ379IL/eevXM/wgQxkHwbj6M4So9djkVXtwhw9mtCiXinhLi5GCqa7WGUPpY3z5Dd
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:04Z'
  mac: ENC[AES256_GCM,data:8itFTFkFHlbc5fKOkEiKGcGHzVR1WsJY26d1w2yl6dF9wzShGRO3BYsh/Sz/UmpGzizmgnKE1LKkvij4LyHIva9dD2COx82Zuq5aMIoYbqeiEP0+U6cu48PR1vaE5fNDqbu9GjxNNfvVzaDDuhKhX0vRG0hKRLk0zQtYSIrmsJo=,iv:AhQYWwMN46eWZcImppc3qxrz5HTXyur7nnteutekA6k=,tag:s8/EPryk30eA1p+KTC01eQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
