grafana:
  adminPassword: ENC[AES256_GCM,data:oNCAulbNDA7g4jJ3G9j7I5Uqd/XaKo5MvatryHVfat+2bjcqFOlpdHfiZsVZNgNP8kxMNwAlkeLJ7BGlFqYA2g==,iv:lJlTLyO9bvDp0zsE+dZQh1thfE7IfnABhAeynKLDUhA=,tag:jw3PN8OVr7+zl4ThdDlAAw==,type:str]
prometheus:
  alertmanager:
    config:
      receivers:
        - name: ENC[AES256_GCM,data:07mFH5D36H9XR9yGkLJM,iv:jQgUKCV/lWeT1qGICj1/961tgSjSDOio1dk+ybWboyc=,tag:/DLa17ekhqBbjNLzbdb4hg==,type:str]
          pagerduty_configs:
            - routing_key: ENC[AES256_GCM,data:wecu/x0cTsUODGxoDbIh35sPvZI5NyMxtKeM3Hrvyno=,iv:IdZQ6BPbzXGO+evAlYB50G8fxgLajIPWu0utRovYxpk=,tag:V451xfOWo4bDyOhFfa31mw==,type:str]
        - name: ENC[AES256_GCM,data:iEMiTUTCYxdVWag3O7Zn8lfALbi0sxYU/jk=,iv:3fpZdP4wMyZLycvh75a6zXNmudXR+SF6rbD3PLozhc0=,tag:Hmfz+bji/tUYkUkVB0nrhQ==,type:str]
          pagerduty_configs:
            - routing_key: ENC[AES256_GCM,data:9vUBomoVOIyvWv/5BCppAc5FWrib2+dm4U+5iY9tIUA=,iv:yX7BbeCvaD7wc6KAQvACJxHw4h4PXdbvHXHf/Rr0H40=,tag:EBfMsgePe62iKBFdtpDniw==,type:str]
        - name: ENC[AES256_GCM,data:3H1uE0zM5/dTpnjrJOOhdznBziZlNPBl,iv:o0oqunEPVep9txxxlqrdeTqwQJKC9tYOpa6piTg8RWw=,tag:nq9tBEFGhgFwF2hR1v0ZqQ==,type:str]
          pagerduty_configs:
            - routing_key: ENC[AES256_GCM,data:D2JPkGj8Ai6pa+0K78f4IeVIpwPAI+uh77JTMp0Mt04=,iv:G2GWWp7IXWV+m//CjYe134wnWuEQiJHxDehKmN59UyY=,tag:JoBVxQrCrL4sF/5bBmautA==,type:str]
        - name: ENC[AES256_GCM,data:lNppPrxGAL3JPZkhaQRsM+gd,iv:jB5EymgGnsGAW97jtCf/n7tlJI0M7pqB+k5qA01cHi4=,tag:Hk17ZdO3W6HNDjM/xOdL/Q==,type:str]
          pagerduty_configs:
            - routing_key: ENC[AES256_GCM,data:9bFt0hSoJFUkY3S5rDTMNSR73dEAxN8m+GB+QtriIuc=,iv:Hqq+6AKckW0WCIPAeEBVId9HEheuxRB3pm4u/fZHhKY=,tag:0jBt9CO9HU3FWk4MMDPI3w==,type:str]
              send_resolved: ENC[AES256_GCM,data:ZpteoqQ=,iv:0TrJjEF7tB2BrhbN2QAoHY3JssCr2NksfycYI6I9zyM=,tag:3zjKfmsMaycpnRrpwTKbLg==,type:bool]
        - name: ENC[AES256_GCM,data:msVs5EpwE6ymVYxx7fnp90FcVIE=,iv:QWvD3gDeHxjZmIOktRGdxYzHgItoxh7AcfTssTg5kGg=,tag:ysN8T/GIiplwUzv+f2MHlw==,type:str]
          pagerduty_configs:
            - routing_key: ENC[AES256_GCM,data:yWaHcQBV+4jlKBMHb0xTtwgFpLLVEN9pEj8e0sH1IeE=,iv:LFDdmMN99eqmkscE8LdZ5J1+i5wVGz4huZYovIfQyiQ=,tag:lYyBtLFCgMZG7FUfwTAMjw==,type:str]
              send_resolved: ENC[AES256_GCM,data:ZpteoqQ=,iv:0TrJjEF7tB2BrhbN2QAoHY3JssCr2NksfycYI6I9zyM=,tag:3zjKfmsMaycpnRrpwTKbLg==,type:bool]
sops:
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2024-12-18T10:09:21Z"
      enc: CiUA4OM7eOThrN3NqDXYd4belMxUdYfF8XpeUSYfiefKkYutN2KoEkkAnGhyNqzzrXyUXTvtS4xl4IjlJpo6hwm9FVbQAyh2Vw9dcXH6h1+NNUHGPYj6KQJvvWZzgXHFLiWdqOfUgTJME0YDx/DYgXgm
  lastmodified: "2025-11-27T14:44:45Z"
  mac: ENC[AES256_GCM,data:c4fhwv0CejF1CdFQj4xqf9RGmxpgMpBtB5whKBzA80+7i1nWGmgRBdKhauiOmFj48BZBpvKpknoq4Mx3aZrlW+2wSCYXtCKfmJOYkpo5Je6QpyuA0IhhNxrk6M+svMBWauC252cIyp7beDWj9/OtxtQzyOLt8tsduxYGhnTaOBo=,iv:/Yav3UoGeaIpHuv/LKErrQ1cbkUX1DXveqDpK9QK7JI=,tag:41c0NCYVY5c1g/BTfORIDw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
