# This schema (a jsonschema in YAML format) is used to generate
# values.schema.json which is, when available, used by the helm CLI for client
# side validation by Helm of the chart's values before template rendering.
#
# We look to document everything we have default values for in values.yaml, but
# we don't look to enforce the perfect validation logic within this file.
#
# ref: https://json-schema.org/learn/getting-started-step-by-step.html
#
$schema: http://json-schema.org/draft-07/schema#
type: object
additionalProperties: false
required:
  - cluster-autoscaler
  - ingress-nginx
  - prometheus
  - grafana
  - nvidiaDevicePlugin
  - prometheusIngressAuthSecret
  - cryptnono
  - redirects
  - gcpFilestoreBackups
  - global
properties:
  # cluster-autoscaler is a dependent helm chart, we rely on its schema
  # validation for values passed to it and are not imposing restrictions on them
  # in this helm chart.
  cluster-autoscaler:
    type: object
    additionalProperties: true
  # ingress-nginx is a dependent helm chart, we rely on its schema validation
  # for values passed to it and are not imposing restrictions on them in this
  # helm chart.
  ingress-nginx:
    type: object
    additionalProperties: true
  # prometheus is a dependent helm chart, we rely on its schema validation for
  # values passed to it and are not imposing restrictions on them in this helm
  # chart.
  prometheus:
    type: object
    additionalProperties: true
  # grafana is a dependent helm chart, we rely on its schema validation for
  # values passed to it and are not imposing restrictions on them in this helm
  # chart.
  grafana:
    type: object
    additionalProperties: true
  # Enables  https://github.com/yuvipanda/cryptnono/ to prevent cryptomining
  cryptnono:
    type: object
    additionalProperties: true
  redirects:
    type: object
    additionalProperties: false
    required:
      - rules
    properties:
      rules:
        type: array
        items:
          type: object
          additionalProperties: false
          required:
            - from
            - to
          properties:
            from:
              type: string
              description: |
                Domain to redirect from
            to:
              type: string
              description: |
                Domain to redirect to
            type:
              type: string
              enum: ["redirect", "permanent"]
              description: |
                Relates to the HTTP Status code to use for the redirect.

                Specify "redirect" for 302 (default), or "permanent" for 301.

  # nvidiaDevicePlugin is _not a dependent helm chart_. It is values directly
  # coupled with this helm chart and are influencing the rendering of templates
  # we provide as part of this helm chart.
  #
  # Due to that, we maintain a strict schema here but not elsewhere.
  #
  nvidiaDevicePlugin:
    type: object
    additionalProperties: false
    required:
      - azure
    properties:
      azure:
        type: object
        additionalProperties: false
        required:
          - enabled
        properties:
          enabled:
            type: boolean

  prometheusIngressAuthSecret:
    type: object
    # prometheusIngressAuthSecret is _not a dependent helm chart_. It is values directly
    # coupled with this helm chart and are influencing the rendering of templates
    # we provide as part of this helm chart.
    #
    # Due to that, we maintain a strict schema here but not elsewhere.
    additionalProperties: false
    required:
      - enabled
    properties:
      enabled:
        type: boolean
      username:
        type: string
        description: |
          Username for basic auth protecting prometheus
      password:
        type: string
        description: |
          Password for basic auth protecting prometheus

  prometheusStorageClass:
    type: object
    additionalProperties: false
    description: |
      Provision a separate storageClass specifically for storing prometheus
      data. Lets us control retentionPolicy (so we do not lose the data
      when the cluster is deleted) and type of disk used (for performance
      tuning)
    required:
      - gke
    properties:
      gke:
        type: object
        additionalProperties: false
        description: |
          Provision storageClass in a GKE environment, with the appropriate
          GCP PD CSI provisioner.

          https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/gce-pd-csi-driver has
          more information about this provisioner.
        required:
          - enabled
          - parameters
          - name
        properties:
          enabled:
            type: boolean
            description: |
              Enable creating this StorageClass
          parameters:
            type: object
            additionalProperties: true
            description: |
              Parameters defining properties of the volume provisioned by this
              StorageClass.

              For the GCP CSI driver in use here, the parameters are documented at
              https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/gce-pd-csi-driver
          name:
            type: string
            description: |
              Name of the StorageClass to create
  gcpFilestoreBackups:
    type: object
    additionalProperties: false
    required:
      - enabled
      - image
    # Require options to be set *only* if gcpFilestoreBackups is enabled
    if:
      properties:
        enabled:
          const: true
    then:
      required:
        - filestoreName
        - project
        - zone
        - annotations
    properties:
      enabled:
        type: boolean
        description: |
          Enable automatic daily backups of GCP Filestores
      image:
        type: string
        description: |
          The image name and tag to use for the gcp-filestore-backups pod.
          Will be set by chartpress.
      filestoreName:
        type: string
        description: |
          The name of the GCP Filestore to backup
      project:
        type: string
        description: |
          The GCP project the Filestore and backups are stored in
      zone:
        type: string
        description: |
          The GCP zone the Filestore and backups are stored in, e.g., us-central1-b
      annotations:
        type: object
        additionalProperties: true
        description: |
          Dictionary of annotations that can be applied to the service account.

          When used with GKE and Workload Identity, you need to set the
          annotation with the key "iam.gke.io/gcp-service-account" to the email
          address of the Google Service Account whose credentials it should have.
  global:
    type: object
    additionalProperties: true
