name: disasters
provider: aws # https://smce-aws-disasters.signin.aws.amazon.com/console
aws:
  account: 515966502221
  key: enc-deployer-credentials.secret.json
  clusterType: eks
  clusterName: disasters
  region: us-west-2
  billing:
    active_cost_tags: false
    paid_by_us: false
support:
  helm_chart_values_files:
  - support.values.yaml
  - enc-support.secret.values.yaml
hubs:
- name: staging
  display_name: Disasters - staging
  domain: staging.hub.disasters.2i2c.cloud
  helm_chart: basehub
  helm_chart_values_files:
  - common.values.yaml
  - staging.values.yaml
  - enc-imagebuilding-common.secret.values.yaml
  - enc-staging.secret.values.yaml
- name: prod
  display_name: Disasters
  domain: hub.disasters.2i2c.cloud
  helm_chart: basehub
  helm_chart_values_files:
  - common.values.yaml
  - prod.values.yaml
  - enc-imagebuilding-common.secret.values.yaml
  - enc-prod.secret.values.yaml
