prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:kBgho5NJNMKMVXFFLJ4fP+lBNiBUGZ1l/w8iXQidNwLdbRL740PTpX9ZUYpJc7bGoy7jsUWG5ReOp9awcmYjzg==,iv:2jqDnU5d5OmA2MMg8xdMa4D91D27Qg8zrU1RdyWtplc=,tag:UO7dbpYpr4aSVFaDAytJ9Q==,type:str]
    password: ENC[AES256_GCM,data:3JlmkzAdSi3Z1O+zKVX2E9vq8mCkeITLNlDXm97ycGdkJCIhzcUVTr1JsmTg1gSHFXMP3ApbzpgREDj6Nl3CHg==,iv:iyt9jwS3bmNCnL94usIhZA1DmvPL6WVvit2qdT8FUGs=,tag:o6LGcpr9D9H7Jo9BzMqFTg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:40:57Z'
    enc: CiUA4OM7ePSYf29G/GFUryt0GGxyIRCC9k1RMkU7B4pQrFQalq+PEkkAZoeZpqIDT7U0lgmSiT3NCi08JKGwFGeHEYPnkcOLeNUtyrHY9N3lwlW+ROWP/AvMIqAnvMvagKy+YlXQ4DzRDPULmF7MBMDi
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:40:57Z'
  mac: ENC[AES256_GCM,data:VHVrbbK5CNcSBVIj49vzy0mhXxhDMx2ujPMtjZZpAER+Mfy4ithE44Z8ZdU+szhPDOpY02xwGt9TnNFB2ywH/nnPQdgwFdF0+6ZGdnoDh33w+2k6JRXvrcuae6zEoebjMuD0yqI1R4bK1ucEsHe+pJMDXy1ZJmRJyWdARr9XhVU=,iv:PT6IMTX/Lnyxd/p6ywKDQxt9X0cA/Pt11r5Ob3owWsE=,tag:aH95V8rnRSITjFcPzZqyEg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
