prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:DfjxdpXj64JRWo2OSqFZiE72AegOUysv40zpH9J8M0S75gbaehxXCO0Gc2sa5gIRrYOTYRRDcL//IVagPq8lx2dzXCiRpqrBtaTBArUFlEtMnla/M0Jo+bWRNn0RXQWaNTouEFwcZKyXor4ejhhjLsp7wrcgNSEEU/ftc/vZnI3O72j3RhGpCNP466CNQvFMcLIgk+ZFMZJMkmxB,iv:YQGb/qTVvzxv+6Z6nOzs8tIU2D7MkW6HT6YQzdSAAac=,tag:SBMVXJVHL7FT8o2mP+8KyA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:XG5IHsVcNnMBEhAC/3D3MwwHNMjHdAFFgg5dNE/gle7+vjxBHFw0mcUNeWbz6oRnBcfPqOi2fWlFTRoJaWEP+w==,iv:RgzoHuHmDGiaCpifnynmxJcO4F2y+3MTEbHZkavQuho=,tag:uCT/6FsL6OcUVWxA0Gb9Ww==,type:str]
    password: ENC[AES256_GCM,data:tfNnrUUp7SladNwxeTxkXTKPaxFzAKrYW69Qn4kXLKZ9TTft5dnbJfkxi9CQWHFKVUa1V7sfSg/0E80bjW6JIQ==,iv:GvtNqkz5G4hK6AEUcQsrF7thHomhbFDqjNQiaC4PBhM=,tag:m48d7MQDqUug/XjXsOsXAg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:03Z'
    enc: CiUA4OM7eI6o8TGhbIN3gduvWwSHSKJhOQwz/JimzuhlG/W2l4SjEkkAZoeZppcVTfJt8OAqsa4BCm6MSAvCzT1VoS7cQU4l4ctOXvTJ9+A3Qr3py1/XEUWttqHHjF6nAOp9M6rEbrwcV/663nmUDDGh
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:03Z'
  mac: ENC[AES256_GCM,data:IGi9EIp59bkIfYctXah1WM/e+h3xgCpg9p+LUE/9qc1AjaRZN6j4tRo6soPwNpQDfbpilMwKjuPcZejDwRDxRadMkB9CUlsqa5DVHo97osW/YBj9wDy9g5c/FwommiPeG9p+fqyD1Jo/fFZbCnkKiY7867bnknh9nzk7cZZhBzI=,iv:3O1BceDyuEf0mLoS/nO1CzMasdAraW69q3MmzMD4B+I=,tag:27LjiYusVoXsvg7CSD7vZQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
