nfs:
  pv:
    serverIP: 10.100.200.179

userServiceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::515966502221:role/disasters-staging
jupyterhub:
  singleuser:
    nodeSelector:
      2i2c/hub-name: staging
  hub:
    image:
      name: quay.io/2i2c/z2jh-433
      tag: 0.0.1-0.dev.git.14741.h1ea063d04
    config:
      GitHubOAuthenticator:
        oauth_callback_url: https://staging.hub.disasters.2i2c.cloud/hub/oauth_callback
      GenericOAuthenticator:
        oauth_callback_url: https://staging.hub.disasters.2i2c.cloud/hub/oauth_callback
        token_url: https://keycloak.delta-backend.xyz/realms/veda/protocol/openid-connect/token
        authorize_url: https://keycloak.delta-backend.xyz/realms/veda/protocol/openid-connect/auth
      Authenticator:
        auth_refresh_age: 0
  ingress:
    hosts: [staging.hub.disasters.2i2c.cloud]
    tls:
    - hosts: [staging.hub.disasters.2i2c.cloud]
      secretName: https-auto-tls

dask-gateway:
  gateway:
    backend:
      scheduler:
        extraPodConfig:
          nodeSelector:
            2i2c/hub-name: staging
      worker:
        extraPodConfig:
          node_selector:
            2i2c/hub-name: staging
      imagePullSecrets: [name: image-pull-secret]

binderhub-service:
  dockerApi:
    nodeSelector:
      2i2c/hub-name: staging
  config:
    KubernetesBuildExecutor:
      node_selector:
        2i2c/hub-name: staging
    BinderHub:
      image_prefix: quay.io/imagebuilding-non-gcp-hubs/disasters-staging-

jupyterhub-home-nfs:
  eks:
    volumeId: vol-08f3d124fcfd518b0
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 10 # in GiB
