nfs:
  pv:
    serverIP: storage-quota-home-nfs.staging.svc.cluster.local

jupyterhub-home-nfs:
  gke:
    volumeId: projects/climatematch/zones/us-central1-b/disks/hub-nfs-homedirs-staging
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 1 # in GB

jupyterhub:
  ingress:
    hosts:
    - staging.climatematch.2i2c.cloud
    tls:
    - secretName: https-auto-tls
      hosts:
      - staging.climatematch.2i2c.cloud
  hub:
    config:
      GitHubOAuthenticator:
        oauth_callback_url: https://staging.climatematch.2i2c.cloud/hub/oauth_callback
