prometheusCreds:
  username: ENC[AES256_GCM,data:TwtI8p52jX4ZVYS4Ot3hKTgGx/V6Y/a1Xa2l5IfF+HlSWOZZ8FrejaKjZKkMW0p0o1GMpEEoyKQdyqmto9x8Rg==,iv:PDngcrrQY+0dohXl4pliye6o+On7rYucacJ+zDE0B68=,tag:ext4VmZ0F35p3ywjwD954w==,type:str]
  password: ENC[AES256_GCM,data:pofaP2/gt5/+nTtOCjeco+xHHEJ0OG+U9OEaG+r0RpHghKFkXIltf1CgK3Ci4r5zY/Ti7snpRwZYy7HD8JkLIw==,iv:6teG6NiWOs5zoOMlxEJLQY7tGr5bXKJTsrxbeT7uowQ=,tag:RwOme5NNSITradg7hyuZ4A==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2022-10-11T02:23:40Z"
      enc: CiQA4OM7eEfqyWjWWT5NNrbnfQ6simFNukOJuvNDdbPb8nBC0z4SSQDuy/p8wWK8SisznvEym2nJ0WnwcAvSuorPFWartNPq58qBkIog6D7mtv8nmh3MEWbdW4+XpDQeM7v97NvZwJXYxWO2NpQ/KKw=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2025-11-21T22:06:42Z"
  mac: ENC[AES256_GCM,data:P/NdV2LI6xd1+OprrqfNcngwa40fBE2kLDYrCdO8hb18XrUrJddOzQmg3SgO0R5jGH5Z9YI759uUQIrQ63IeF/aUv2teThTkjLJkUPqXxOj+C329lZTznANlRpdgGbLOT+ZmU6pbslgfvxJOlGJNN7GAId/rroS6l51u4ijdCQo=,iv:KIIPpqWm00kQTgy3hMuQBqNgUXfTpAeEUjSjPIjPL3w=,tag:1ic2TzsVolzTgwPJ04rjiQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
