prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:h0lL9L6BYYBsrnPrj4LXlDWzkC0d6RQz5+OOIumkEs50HOU4FADwt2XtmKgUqnmXtEREKhMI7XuUI2iACll16ItygqqhVTgy5Q4jvITyhbkLq43pp8huJBreUpZbBWWqL7tQVAWnB0uMfCth8ogZhva6rsAI6F63aAbEJXQOnTblRURwjbHORtQPoknOrsER3HM/Kl4wpaWEWY87,iv:KEOADY38rTfNsyA121PlAA515LBQru9gKTzHo3nlnkM=,tag:3AOW1W3TozTHuB7GbC+meg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:5iBOGjiCpWHNoao8ap/FCR8uu4MoN3SUUx5okV6mUy+CMMMI9e3F9lGL3XmOvW3+Nx4413057r5bLd0A8MopAg==,iv:qT8n8IF4bl0IXAT6b/LbPrabAVWR8ITylxFc57qN4W0=,tag:donosnkK+hrIhasQ0j9poQ==,type:str]
    password: ENC[AES256_GCM,data:BUwDEL0ti803k5PxZS4gMTRrFeifONGJk6a9+7RhWgirtYqhTa6TUR9Ej5dl1+wgPH1OXYFfbRTkDsYohWeZgA==,iv:vaWM3Va9jXbO1SZnSzhhPLORrD/NMDujrdJUiI8X6/Q=,tag:z5IK11W5z++g5ECUvxAQwQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:DsiJ6rOG4OIy4XhjKAdpKWZbIRI=,iv:unXYiPGyEWrtRI4OcqD3we2sr9C89GSWNsyzHCoOdFc=,tag:I/75GPZMjqo2FqPkjZok/Q==,type:str]
      client_secret: ENC[AES256_GCM,data:ndLSP6KlTRjIF71U/tvW00ivbelehCT6CC6zXt2OAJhCciWKzeiuMQ==,iv:LT63mUIavIunlq0alTBBsBioXgzXTOW5S3gyPQ2rQ+k=,tag:pBkDbbCdFfGoNN6kffXiew==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:19Z'
    enc: CiUA4OM7eHToUMIVQmzcSE3zYbMvYKmnfyWrJbS+gg1oVah+CrJ3EkgAZoeZpvHGIfMgMXr+iresAHtiB6ezKTmoH5iXEm34AIICSeYnbHms5G5SJor445ylDTSpPpAF0nPC0KKqhqAkZuFaY7mBm28=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:19Z'
  mac: ENC[AES256_GCM,data:okJazg+TFX78/QbW+MVtb7Tyhm+CjMvxdvpYHHwFH9TdFc5s0n9WeN8OzuZtX/dC7YHp7begvVtkVtU/xPW2W+SRrQ8v+vFYQ2/2o2BEH0Xmh6K7cJ3w/AWIclNLMu1q3piy0d5oRiCNT7tmY+U/3QPEkLmRntGeJ+gnxpEho1Y=,iv:L9RCFqLiM0d7vwp+ZVgAJcAYqT/tEIeUAEGuuvdl0Bw=,tag:RpdXLMEBWf/ws6nyxUw0aQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
