prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:qw7bJh+n+cPd049g7LtvtEkbiwPF7CAyLmEltZwJokAQKbuDwVCCVQuY7rvmUXhoQ8LSFAsHijxebt6+E3tttg==,iv:vSwHxQsjHKvc4PERlwr1llYzHhRQwfy41l6gJN74BI4=,tag:StNqcExegPTq24PCf1CGXQ==,type:str]
    password: ENC[AES256_GCM,data:dAcXV6SOkC/hK6VDrSjPFV6hTSCmtpu7ylnLViogMOd0zd95bQoChDQx9ntQd/+8qXpxawkxGRaF+67oCiIV8A==,iv:hXnfAmV4d+6LJ2wdGpX9jagIRwla/LvMv19PfR7s4Rk=,tag:/DL5SyJ7aSoNH06+S1NKOg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:Am4ai/n3ei10rTHR75SQ64zZyiU=,iv:DNv5hIqKSztcTk/sqJBTrEESmwZxnIH2gsFwiKU0aR4=,tag:724jaQ4SEYt0NrsOOihopg==,type:str]
      client_secret: ENC[AES256_GCM,data:vU1EJQP6CAFA/TyTOZdlQm2Eek8lmxCZMenUIXUkRgRD3f+krQVXew==,iv:nZvLWrSGLJ1fK4WT2vvE4xrWQ14sja04ksl2+HS4C7U=,tag:4kA2TDV01S9WXg+WFy8ynQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:13Z'
    enc: CiUA4OM7eM0lUDNexwwXZNdqm9uu0xWNsMQ8HKrEw6M1g+5XF7YnEkkAZoeZprmCWhfmVCHSL1SdXmvuivUrFfatYS8quvOGkQqUjWzFvLyDYIBFU/eZzPWERh6foxjuear2/u2Zm75/wSTUofHT+/De
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:14Z'
  mac: ENC[AES256_GCM,data:L+8/44sN9Wb5p1DaUk7/iwbFRahkSXUWifSQwNootKQA0bd+kK0IYtRbuPJn9bBxFpmpKzUN0y2Eg/msL/WjZYhXI2zlfDSD8t479jS/HzF/90ZrLyLa0wzIEESZ3GzZworrsWW8dCKK42BT4y/9MgSy09KWXd3+t3BNE7jP37g=,iv:Gql19JQjwjmrZOQIyd8gP085yLy9SFRyPcbBYkY7o4A=,tag:JfvcGnonhqOVf+uZAxH5Kw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
