grafana_token: ENC[AES256_GCM,data:XF1r1oEBYsoI03T99WlIhNgTAPNNccsDGJrz1+Rnj+O0EckwvAg4NshBT9ZmwLWC+in+LVbtuv6S04u70QnJAr6fKiAu3txyQtaXff6q8b0JOnAgJnGdBTeENJg=,iv:dxEC7INDDxq5rxx5OZTdsDarZ7sRPi7rSp0jn99zQF8=,tag:PcUgMyEq+eY+N712DG6qQg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2022-09-26T10:38:09Z'
    enc: CiQA4OM7eCR3iueV1778GFBq5kvv6CEvIT2bCsPyv9qvk0VnUUESSQDuy/p8VW7Qis9HbDQDw+E5HJgEO7axIi+1EGrorRA0YaDcflSdQkOSxuJe/7WGSe1S/BptKUSC8FLB+8S4cKVGsvAtQ0RenqA=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2022-09-26T10:38:41Z'
  mac: ENC[AES256_GCM,data:a5ArT+5azSnVzYEOsK1hE+r4/vOjMvkcrO/V/d40Qv8KQ6qmn2K3KIk0sZW2D/C69VZjXikJbDvXnmKthNBG5GQMm/eEvk1OixWi4PnIv7gpysrIO4eaYX/y/qgf5fvD9e8w8Z6Wte4udfI3F2kGkTJC+7FR2DQseMBb+ifwQvE=,iv:leGwAvQUbxkjX9vFFlLezWe9ug5lz75Dtoo/ohZS6Cg=,tag:zBcpTkcAIZ5aSPmfHvrUkw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
