basehub:
  userServiceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::740010314650:role/uwhackweeks-snowex
  jupyterhub:
    custom:
      homepage:
        templateVars:
          org:
            name: SnowEx Hackweek
            logo_url: https://snowex-hackweek.github.io/website/_static/logo.png
            url: https://snowex-hackweek.github.io/website/intro.html
    singleuser:
      # User image: https://quay.io/repository/uwhackweek/snowex?tab=tags
      image:
        name: quay.io/uwhackweek/snowex
        tag: "2021.07.07"
      extraEnv:
        SCRATCH_BUCKET: s3://uwhackweeks-snowex-scratch/$(JUPYTERHUB_USER)
        PANGEO_SCRATCH: s3://uwhackweeks-snowex-scratch/$(JUPYTERHUB_USER)
        GH_SCOPED_CREDS_APP_URL: https://github.com/apps/snowex-jupyterhub-push-access
        GH_SCOPED_CREDS_CLIENT_ID: Iv1.0d0934b2905d0b6c
    hub:
      config:
        GitHubOAuthenticator:
          allowed_organizations:
            - 2i2c-org:hub-access-for-2i2c-staff
            - snowex-hackweek:participants-2022
          oauth_callback_url: https://snowex.uwhackweeks.2i2c.cloud/hub/oauth_callback
