prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:RyLTHdvoMAohMp2AbsXkl8XLwZJl65AvnLnfMK7LV8eBylO2+P9N3HoPvDnFMsPZZZjpuCz4wdT1/ZORdcJa+3Ir4VFlU/400IxTtFVVzk+15jVH2lN+n3nnuSXIVDr0RF8gZXX1pyZKn/5py7p7xZ6x+FK0vv8A/zB3p04mA+KJg6WcSzyU04tMBo+a7BpV1iOLeto8grNsIRNB,iv:mfOfywI0TuMAv8/US6VYNfy1r1dh857QFlqgkDl2/34=,tag:GdzFt38UBrAWPkzprnl8mQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:s0BiqJesc2Asp7FkXjHx6FNdIE3oOvT5b0pyJFT87sSOUwpGB593bbqODYq8Bq88799u7BjLZoEIh2vX6k+P5g==,iv:9u0zbQXs3M/mersrEMBerTCbEoqSS2uBpb/LjGr0kpc=,tag:X0DYjFWDVh29HKoDP+jLtw==,type:str]
    password: ENC[AES256_GCM,data:hoK0NjYeur6Jzt/or3/9MWmr1LhoUJhVFtNSGCvkEL0D70BXAZfHN/o1LZt9fI/JVmwUDS2q/YkiQ5B+S2137g==,iv:bV9RAKHGjVVfMk6A6udfPE0Hl2yciHW3SfamnRRg+t8=,tag:wO6obCVj699wDuq+URiE3A==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:DVSfZ6WNZW7YqXIA1Gp3ydiwbQQ=,iv:iL+7nUbO84nJ18RFdT1fYZZU2heETYPBTvqzSjhfOMk=,tag:Py+zVS11sFYHFdsgsqfKJQ==,type:str]
      client_secret: ENC[AES256_GCM,data:0eZtEPhtuq6nxJVhHzUO2mYDzJWPojIUuz7AANQ8JQulw98zMvxZGw==,iv:sIZtlNRlkhnctPuuzfUlvXo73r2pXOLlBelzoPvqfCI=,tag:vm/bz50eZzZgukiPQGCwmg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:10Z'
    enc: CiUA4OM7eJF7eMFs4cLEpEqlexk4P6XawAbcuU9XdWiME26MOIH3EkkAZoeZppxvrOsYIAZNOKjN2umyaGkDV6wxWRUv/hSJKLbEwGUwdqJic8u6FEac+bUrB40i804KZMxVjOKXVVDNqcf2rAo9MMib
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:10Z'
  mac: ENC[AES256_GCM,data:UtldWhWiS42IJbcae+Aon4ZGt2Z+9DDCnGlal0tu3HJUJojSwtKshRsB1YmMeVo/713R7KVzZdZpb+qS2EyEibROQbAYKxjOpgeYArtfg2FSJuxUvAxkIBTaIE3GpC4/lYt0+ti2RKk34pjz3YHU9Me/4WUGp3GI0mQpkkGsv2Q=,iv:RWWbXw1o02alDnXHnHruTplqVm0XQLoAMC06xsw5X2w=,tag:M1iXiZMWgZnIAjO7IBXZlA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
