prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:dXhZgzAW16LukJwT2iGdBIw7WVGNsuahbFn3txTB9WXE7/gBpt6i+Ivp/LdUC66qbZ2y5gmPeE8pMYVH90C0rQ==,iv:GTAnzpcFA7w2Or1Hm5sdE6TrUqkAHoCSUVHzOCwG5dg=,tag:Kc908q2QLQRIEcr85t/wIg==,type:str]
    password: ENC[AES256_GCM,data:80clG11cRrYJib0/Yg6O5FHUvMzWqajSCu2EZvA7MspyL3WOCiZKXK0Ak3rgQYcWdREa7b0Vy3ukY6ZbtQK2HQ==,iv:CbxqP04QCwf20qhqyEYDLECes3DHrYXMniYSXdfemy8=,tag:4w4TvpvFDBeaJn021PwuMw==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:CMVeibvy6QBMNysrvBSaHNEUbYk=,iv:lBSm2JbPd7BtPXLSwkPAnb9eU+Urc5N/rVKY41uTUI8=,tag:fzcukJVje36q5mPQJKi86w==,type:str]
      client_secret: ENC[AES256_GCM,data:O2RcM7zrM/eLw4sb91UnT+u85U55cGp+smP4R+fuNSzlDJt8L/PgWQ==,iv:XNyvQl5bLLZ5h8QPQqJ3ViOfx5YIDRTB9xfdfff2ELI=,tag:/M/hOHYI+CvtLJN/Pkyanw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:04Z'
    enc: CiUA4OM7eC4g4k/73Qo2LmIADfER7H4yvnXh+7D6B7mZDJkzTnC6EkkAZoeZphFLEZvKFYhus0sODUANziXG7y+iuYZsuzee4DgiK29dGO8of+RH5GYp6UBBJjfL5R4v8FLCMiPBBgXcP/3ZfAKNgxED
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:04Z'
  mac: ENC[AES256_GCM,data:tmADtDyKnFv6qDipI95Vb58TJJtJHst6dC6VMWdC8UXeSOaFScR1XMBJf3t0/RsT8H2/ulwsKXCgy7Hgmo4Q7Iq9/gHxkMblLiJb2llpvtOBq2K7r1v4boqasEXBb5Mm6haU15xL/xKy5TegQs7F93FIJZbD6sTjBSeTffImAD0=,iv:yw/+9JM9s4UBn3JRnMyHbCJrGFIQI8f7Jg8eP3Rq5CE=,tag:3XhpKkQBdjPZxGk9w8xWCA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
