prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:8AQoQFwNGhlV7A6kj3AyqUvmlBIkM6+6AWYMrz6Fr0vo091Ie2dQufMu2Gri+8v8UEOZuwXmvXsN9BZ0v11R1cp1sUtwFAfy+McalJuWud76DxaMLt7pI8qDsQqRvW66fG2PBx+Ic7GI2NPOvkBGk4GPwMoahUjp6qfP4LhFXyR874t7sX38+9aNlnAdZWq7/7L3ERdWevJXeLj+,iv:JMQPF6+/7rFfn6CmVDpVkgSCaVmpVZPI0KjMj1EyMnA=,tag:0qQv+ThGHqmow/30VGYI9w==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:8Zlg11URnHJroRlQk9bYURKbHFQEAi7RxjXDU6pDbbp7nz7E0hA62l9KYcHXlDPCIC7JO+paeKapj1U+hkpPXw==,iv:kX1ru9taH/qaroAbP3eOOGEp4p8PhFR9yLR1CwGVF9g=,tag:NGuMJNRL5BgISWZnNkJJAw==,type:str]
    password: ENC[AES256_GCM,data:ythGJ8t4pEDfSOxW24w8LecqbWbf8hPaKz7oLwnYeiKD/VfFICUV5x3fYSnZ/rI2wA91aZyED8NHCF5CuEBGpA==,iv:vOzT0izcrXolaD7XFDvyv76a2yl7/p5hLfzn0SE6uBE=,tag:3O4ORfAb8UzMZKA7RgrOlg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:JNR5XzJL5se2M000uLxx3rB15wU=,iv:2y2d6ABBHtbCssdTpdY6O4zNMitKJ3BRBPhvgo4NfJI=,tag:kd9J6xNFr8SezBfOGc5F2w==,type:str]
      client_secret: ENC[AES256_GCM,data:X72lTFr6TO3uZ1MVNnex1o57w1svleh0qwcowL9LRx8kfnSwutEK3Q==,iv:LqnjjQDClIpxrzjqcbqKOXVoJ49c+vnrXz0C0E7hyUc=,tag:AwzwwGEaVd3ba2EXT8JZrA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:14Z'
    enc: CiUA4OM7eKQggCp4DFOcEYBYQlM4zq9npZ/K+wwpNypOubTv8gXzEkkAZoeZplHVEvkeDtH6soGfsJglBCXR+JNNe7+qxIrywNQ3Tm2v2Aw9RRt654DABpFj2VlwlpDHLIs0c9X/FY0Mcbsu5ZgjTr6a
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:15Z'
  mac: ENC[AES256_GCM,data:LZ8RWJkmTVOs+9dPdGNDLb757aNKshM+YV/p/c1ddGgAbAEMRQG/l3t4FJ1mChYBzTX7iialWY+h0wNmwF1CUBqXRLURkqV0PPKiz/YnxD2Q/ZqgQROGos8Ig2flo67LIg3HXiJVBjgerUnmO0oydw+vPjPEI7uGdejpipqLgqo=,iv:9cNIt0/P7oUVjjPe5DOrQ8gGOTUOgIMzTb664pa53E4=,tag:GSLi4YGayMG65M9igoNMtg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
