basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:ver7q/fDElBhXvEqLDqyC/g9kmQXsOjA3Mlspz6k2tL4KG/ot12AZ2cCWKQ9X2uW6yZ+23yQhB4blhK2dDg3UQpNSJ+z/4KGmwapsZ6+LCvo7sB8/KM6m5942U+SVA//h6mnPjaNyE7MYKWxbfsX70L3XX0pIBqHyc4aHtqX0479JCn/1+vTiPSe4MoArTps2rEsdEFMranv/tNGuIONI8lLqKMHM3nJwtSU5zInGCNlzInxovruxHCURyNUwbN7mHOVQ/X/Pzo2vhvGFJrhUEpUJ8LXNqQU/WtE6YxMERYyiaoEDcCozMwENljW4dO5IqsCCDzjNgJ70vlvHNScLCgpT9K151DvuHAbzorVrDRL/nir9PnCZCBUSMSVFgiojtmqfpNNUnvWUiG0wr2BAb9cYvjG85eIXapyI4iMgsHPtADsiOW631MKWxzhG5mBq/aMVUIDOMVd2IHq14dET9zzLPjjAJITSQA5+czcvzfIQ/uC1kZqG8A95oWLg+FNUa8K9+r/UttgtHGEwKOIaGbauKjCum6OE00iOvoKaRjkKQLpqRba3OLMvhFz24LGO0Cwf859TNSURw+/v5ITYkfF0MKKzYZoPr6zEFv8gT9gGp+/jgP9OPF8v/+Aotwn0eg9JgW56hZ5KLgLtSrifHuraT215Y/4vs6CDRD8KMR1qkyFs255phz2ft5x67ZgSyb/fiovQWvK6SUOt1pPMQvadVjqCZQ/mNq4oVlBunk7/6sVgXijx6QkEdyMqU57cuUvX1GpXAyANoGYKgvgZD35PxEUh0HECIyTl2y1cs+1M4I71jwIk3UVQxPG/iyEIExSOhasXkl47AW5eo5zacFI5dvXetp6ffx8V5u/trTR9ctFvit7NGsD4orFOoy8w9HOGkjw77ljMSN7fuajH9Xqksfk98x45b9q+oXvoLxD3mqrvIoVuIzIiVnXoyXzS7Me4SB96rDrS2F6NsvHlhdMmbRGSOSEXbId1/L42Js=,iv:Y+XrIn4EwEuli7SclvINWV4UOLqHrJOaIuWGlCcomNc=,tag:0XQfbQhael8Qdqi7hKaoZQ==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:ilEVTmjN83Y3YnOlBKjA9EOfUuM=,iv:C8143cwC6pB0sFueQq7T1XbbmABAHu6kiLnxbZy9hVc=,tag:Jc34Po9xZZShfq5l/2CEbQ==,type:str]
          client_secret: ENC[AES256_GCM,data:cSq7uA39SxQ9wIXAWp2FkEkGuzPXHCixp6iwRnkya9YngnUhufpIYg==,iv:dSXXOKhEt/ipOD1bWhcghks+Mjpn2oUexzJhjwEt6ek=,tag:8woToirTzLvX1WqHjbLpGw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2022-10-19T12:21:15Z'
    enc: CiQA4OM7eHhdeYFpxkSDTcwgJSCnGcXyuW+RXURXZyqVtBExJLgSSQDuy/p8cJdVxnALmGegCdGggKwgIqy27Dtr97EyJnjFxmQMGDQsWh3vL/2xXyL4Gw8E1cYoxh7r+ecwI4YmBOO+q6rBIM2fS4I=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-02-06T22:55:59Z'
  mac: ENC[AES256_GCM,data:YoSfJmkm07K+DBnneEDgAbjTUWM2npoho9t3aJnueoN27lp5eFgstQp8lhYvn2WaNc/RV+WMsXH30grwsVzkKBGw195hieRwMD+2wVbOSyUb3/iIsY3LUfhVewxXj6Z7z1mc9eFkn72uDhZnNTUuK9x0VJQebmx2qCojrMv7fW0=,iv:WGJ6bdyD90NHC7HbZ2872LXG4DtxAr9/wJxYanFyC/o=,tag:zV2HAQR8vW1j3jb5TB67SA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.11.0
