basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:7Hhx9JIjd9lW9ahKyZK6yrkQT2SA/qOJ/Y5xAUzf7/eq/6DpgDpjWKJbnzmnuLFeJasRNau9sJ/zpaop8vrpA6U7Z/UCo6X1EkKDAhoUquX5lnecw/zDbZYYCROzIHKlwKOnbnZERw+ajkxZHt+IHC53SP+/L1lTyyMPbrR6ZufCWlRGdn7IysDfA2xDm5tvE8r+YLfyvn89q3A/7tiR/SPIWhJ9OX8HfHrV2CBPohLgjZWiM8IFo6PfMAQ7jS6m2iGtquYX5n8ZtDjcQ7wggdJbolP4lmZ68gsmVR1VJxQX9+qOm3+4A6qqJO5WLCCz6VT4TWgVHGWa5jX8SNMayGSOv6MvzvptpaIitIliXgMbWIQvj77QIOTPWWICqmf/BKV7D0E2HK/OJZ2hqDFT86ylyj+UVeqVgAH9zb4+36zQowRyjNAkKfS8uqdP3+nFiDmQfYoG5WfzBD2CTHKiIqFF0/DKNVRIcS/Ldz5dIqiB1Zli0GJjQ8CP1qFxECqq5jb9cD2imaxGh5LFuFpTUAEYuFIL5oFJjiS17d7BbFRAlRtG+Z4KVW5rExtth5myJ9wT2R+9rGx/h59KzG2QNEIbnHg2HqUSXU/IEfcYzYnSR0qu+RIENNukEVfI1gjjhYoqBKMutSozMbPk02zGBVULjeVayRtsLEmMOKcfycf/fHtfZyAEJC6GaoCAQ+nHtLtxGszYazq7z+XbuoLn3oavXk1QxaOf6c0z2D7EsdZcQPOU9/lAns9bZGfkLhzfvkTXmKId4QM68smGURDrv7T4MUbb8/8aysw4ua44TXIwJDDFJ/2IkG+weDaLkmSozn2Yvd9qDziadG6XqDcdwNM4//pm8TbCR1EquREhEcMPS4wDMALYvd6L7JF/7/JXLADJd/VIQTx+f6ZJ3KsKHLsVZkaslfQauVX+wjh9Fgggqo/gdSJ8hnfXHqqqN2bKmq/JExbXhMU5rCtpvNhnABCYTYVDa0MH6wqON64e,iv:KCll9oU7McIH6g8szJSxfPgZHtWLoAJ1Z28lxoE5SfE=,tag:BtBKzsaW/81dRSx71bDP8w==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:ilEVTmjN83Y3YnOlBKjA9EOfUuM=,iv:C8143cwC6pB0sFueQq7T1XbbmABAHu6kiLnxbZy9hVc=,tag:Jc34Po9xZZShfq5l/2CEbQ==,type:str]
          client_secret: ENC[AES256_GCM,data:cSq7uA39SxQ9wIXAWp2FkEkGuzPXHCixp6iwRnkya9YngnUhufpIYg==,iv:dSXXOKhEt/ipOD1bWhcghks+Mjpn2oUexzJhjwEt6ek=,tag:8woToirTzLvX1WqHjbLpGw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2022-10-19T12:21:15Z'
    enc: CiQA4OM7eHhdeYFpxkSDTcwgJSCnGcXyuW+RXURXZyqVtBExJLgSSQDuy/p8cJdVxnALmGegCdGggKwgIqy27Dtr97EyJnjFxmQMGDQsWh3vL/2xXyL4Gw8E1cYoxh7r+ecwI4YmBOO+q6rBIM2fS4I=
  lastmodified: '2026-02-06T16:24:04Z'
  mac: ENC[AES256_GCM,data:SBs60IqHydSgeonl1W3DQkJyg0765hBp0wAVGojTMiCdXIJFOL2RbDLeX5Qjj3qCroVcuQG4+qnMUPU4l5cOhkQkevcI6NrBVU9LBbXEzIZL67jgBkkjEmbPIrLrYyN129633RepO7SyIV7Q16B0wVabDzJbcVeFF8hmc9EYb7s=,iv:a/8JlwzWW3qNzzpYWcAPBq0B0aUDAY3HD6pK3cd0Ibw=,tag:mun0EVP6ibZFGEfkESbNnw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
