basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:rZj7ZXQq+k8i4yi9rKjM/Vqg+mBXhznRGC8eP0k6XxHvCDYd/hzqQsEC4ZU/MQByIbWgK9ugW09V3E+a6+F016RiBcWPG0rNflzZSXMtlMZUZYiG426PXGf2ZMwQVlMurPy3NGPd2TdDZ0srL3d8wKBSgncS19umlOwfQ0LdOYHhTqX3a3cMPRIeuA9B2v68QvBAoMfm+dkiXCwGfmohU6lkwWKzVNNtj009WLjUVSwntd8x0VYVz9Rz4W8lcHLCTp0zUC3Lq/uzmeyaUFYwdvgekhwkNExxcHzKQt/AqtLLEBDLvznRsdV1f0NbYy6A/Ify8K696n4g85uDxbYgxBiwg5QYM+J42el4GagW4MUj7FmQ0uZiI5S6g+Hc1Cft19oWOVOFVXE/4mkxNYWmNWTZ4D/GlzKfCMAvBQZxDqaaRR8el5NjfqBLppCVVHSkg3WphTCBPlIVr0zKStIKyhMZ5xp5t9Yfb3xAiVu+Pgj1KpJ47d6BEQV0XIppoiZ6AbmyTZlIJLuEK1Xs7ioW8RCPcFsy8lhlcGsrnl1FOqAZw2VnEOxHTHGiX5bg2nbKg/3PBKgLpL7bdcSeZlmhxkYsO2d3bQVcdyranYX7eV4wESQVysC/ZzZwmLfdhHFWofS6pdUFQWHKW8Q2gp57NUCy2h1pD27g7YiPVNcJ/HXyFMH5JHm+2dE6aBXGDx0F2XpTNMKmJ4aADqjq+q6/+x2u8ujzdIWXfa1UjgHGK0zemY2bt1yTTMlTzxuEzRdMmjxb1mdpzhSyYf/4ZZ7WdfEjX0oj9RuQVJ1BPo+GabspYko1LulVgDuw08qtnbzD4waaoG5lpzCye6bCtZBDnVHGGtTfw3BgBaiDgAMUrUMzzwncrQ2czYfA3FW4G/AVkTVL/u27xNJJ/aGY2RBBCUkpFfeBH29kRXnqF9U5TyNEVhcHyh+u0qyC/VxNajU0f6v4ZoDaDTKCajMQIw==,iv:HX58h+sJZ5JhFVhz/K1+j2/gg/jt37eeRcKNexJBgwA=,tag:rMaSLKQY0DarUiO40sqXEQ==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:ilEVTmjN83Y3YnOlBKjA9EOfUuM=,iv:C8143cwC6pB0sFueQq7T1XbbmABAHu6kiLnxbZy9hVc=,tag:Jc34Po9xZZShfq5l/2CEbQ==,type:str]
          client_secret: ENC[AES256_GCM,data:cSq7uA39SxQ9wIXAWp2FkEkGuzPXHCixp6iwRnkya9YngnUhufpIYg==,iv:dSXXOKhEt/ipOD1bWhcghks+Mjpn2oUexzJhjwEt6ek=,tag:8woToirTzLvX1WqHjbLpGw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2022-10-19T12:21:15Z'
    enc: CiQA4OM7eHhdeYFpxkSDTcwgJSCnGcXyuW+RXURXZyqVtBExJLgSSQDuy/p8cJdVxnALmGegCdGggKwgIqy27Dtr97EyJnjFxmQMGDQsWh3vL/2xXyL4Gw8E1cYoxh7r+ecwI4YmBOO+q6rBIM2fS4I=
  lastmodified: '2025-11-19T20:51:53Z'
  mac: ENC[AES256_GCM,data:5DKkOOJoIy3Cd3cy8Ikem3K9Qt0hpfUSJSlqzhgg3KrOqsHaN1gsgzweKzemt469sZCOQVr0g4UO/UklnhLj/yLxZWfLR7DI8IAPShcwZlTdr1RS7AYNJOeDf1ZxFLRPwYlKoLEwGnCj8qA1Fq7r7OrHMmSsJfV4v+qzapLVld8=,iv:WYu0tJAb4BKX5s5Svx+RPEGCLyUJgd3w8Cus/M9jGrQ=,tag:n+63N7XA58MqdgIL9u+30A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
