basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:hn8NqIJ10X0kYJFolh0b1ItzXVfFztjvflPHClHuuFzsJTZkGR0gCtsaRfvYnfsVk/yiEzci54FmciHCt1tQ2eDlbM+iqmYuOjiUKjgLJYzOBx67cR/mGnzBCSiYhgLhkZayTCVcDckSB/nkiLMtPIVA7mr10MW0Pco+1MUjPdJV37nCCpsq3mb7OV4wtkJeW2GQUDbUKX3bUV6XH2isH0XpmlCnTAJq3cOQWhocZPHAs/2wik5F3xLKYYXW1+bsOzOp+k3c22oPvljh4FqWL7eJdzzOXn32WNjqpPa+F/4w6nCqQn9zbsxN5Pegzyt035fnyzgsU/izPWsdx74olxHlyeVjs7GWoPSUf8wwB4kwg/Sq1ckeT1qjbWL2d/8xRyZfHDBbemzwHjhzMgsC9abggYoz5XMdvLcHJOPl9Ti0IdTzzaOR+3FylU5WoDc0Xqvz0hKXQxfknGMIxSIcl3pnYkaIHRZX79SXqRaIA7pjy/dBhUH6ojj1Mxz6E4ja+z38O06TowJj3MaKPh041NklSqurWzE55BmILikAjjrCwPPq6cNvWezMyBr4cdNzbcg3K+jMlBX4A0IKWQ2IKOGwqO0pdB8r7HhdDZA22WMEgAnshC8WzBYYF4H7If+gwOt4U9rIxOJp0CA+BF6SveSTqRi0k/UsFtmfJAxNKdi0pIkvlNVcws8gvaHn9Q+EF99mn8cdlEZmdAaQoTtHKop+RNq54fiOYaCIjWH8AeyXLvI9X9p5AXjI6FcbwJ/bFq97PARjYuFwvsxw4cxzmudPHKC5WSOezHFNbCZt2YprIefXs3PMFz7EPXcIfym7Uy2Us/c+QhYmJ1E2BExwNOXEwMhecdcQZASFpjj42XEWmkUNK0iVo59pGVRyQLVBpZSGB6WtBH5lzJ0aGcq60LCv7EXmSFXccyUcIX78dpDkOwFeM7I194eFOXSZnw2Ypucusv6MUJL2KUJ2QglMYgHXGhZXxzzYKojwtdEk6SGY,iv:EQmn8xrhETpaN8hZqCWJ/GJ+fT5V3he84YxF+KWAp8U=,tag:Ev+nYkU/DbYlpmfh8Q/cGw==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:ilEVTmjN83Y3YnOlBKjA9EOfUuM=,iv:C8143cwC6pB0sFueQq7T1XbbmABAHu6kiLnxbZy9hVc=,tag:Jc34Po9xZZShfq5l/2CEbQ==,type:str]
          client_secret: ENC[AES256_GCM,data:cSq7uA39SxQ9wIXAWp2FkEkGuzPXHCixp6iwRnkya9YngnUhufpIYg==,iv:dSXXOKhEt/ipOD1bWhcghks+Mjpn2oUexzJhjwEt6ek=,tag:8woToirTzLvX1WqHjbLpGw==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2022-10-19T12:21:15Z"
      enc: CiQA4OM7eHhdeYFpxkSDTcwgJSCnGcXyuW+RXURXZyqVtBExJLgSSQDuy/p8cJdVxnALmGegCdGggKwgIqy27Dtr97EyJnjFxmQMGDQsWh3vL/2xXyL4Gw8E1cYoxh7r+ecwI4YmBOO+q6rBIM2fS4I=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2026-02-23T19:22:04Z"
  mac: ENC[AES256_GCM,data:P6naS9sDh52jiiHhgM3KFxXK5suD1e+LPoaVTyeMQMwl/0P28a68tDa0pq0y5Zu4EZXIAI1DTeGd5p27M0qh+/NrDYAy0Ux1XJ1+LCUi/Pyuf1gcvoIBNv7N6TbxTRgck1q7fZsyV7fYlKQYSZQj1Qpb5rx93dt94b5TTnlC/ZE=,iv:/n+FWHOH1yJ6cX+ZJ4GRfvOTluGhnt/DovkvTkdZb8o=,tag:uIQQ7b+qoqQpZU9c4UxA1A==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.11.0
