basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:lpsHN/dFs7ZoWp82gk2fh16gnKI9nUa+YyqX08oCtHhEo51V/VfCA+Tf/1cNHpkFyw7R/z/iYkRek0EnNhhuB9w2/KKmoM64rzk4uwKxhlFR1hvZFF/ZzqtOBB/DyyMLo8YRURMr3yYNp8lygtsYBimuD/9D6pUNnwFOxwjCJZKrJLAPDS5A6rdIJdbybON4MdB29VcRWwAXwFCK3ajElpFY6SWYnTLMjVsgktIgLowePI46FxPPGRfxBE9oUzss7xNjLb1ZrFIv+bQqPlWbJ6oMnFhPNkcWiEh1/1RjaJk6dLvGhOhdumSPJUfMebklPFkYSKEbJcSBReWygq4xOrImqSd8qUc5ege1bwuMZlZxqkjwoGWFBcl+0gRrulNpE5I0f1u52bl5fcmuVFFvPpwiDujHvyYSbNDkoGQX0HIo+vftF3X/UxNmpjg7rAR7oHj0gEZwUF0Dl8Z35XBtfXbBy41LU1dgnxYujy+1ARioMwJV2UboNx8U4OG4OazSMwBAbGs7jQ7+L4FE1a5Ktj7Sym7UnOVZzCeitVd50BsvyafQjW/3e4j/xtB4kxu+STWC5LWFjD5Odqf1XmyTzRczoe0vfEnsTAhICa096wm6vBjEbIxs/Yv/NpOT4B5bnoM2n1KtGkFn5oO3SSH79KzShbAwas3PYEPkS+TxkIdwf18vvWp8pTVubf4Ib8BfVfnL6wqa7ybpNQSHcDGTo7ivMbQWhu/hmuZcylum4CPcP3rv9l2UUzJo6tRD2kBXtWSaR4ZxJjkVq/srgNTZQ1WZIt+NvGy8VGYJKf3/DXSaeP95zlpH+Q6WJv17Jqtm0rv+KmbfcB9SXsQXlO2sY5mw0cRwuX/s,iv:1XEQ4Rne3jL4lfbA3pDQwebzY9TbWOGcOTJdHwG8RzQ=,tag:ETK7tLcDr0NybypnuH++mw==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:ilEVTmjN83Y3YnOlBKjA9EOfUuM=,iv:C8143cwC6pB0sFueQq7T1XbbmABAHu6kiLnxbZy9hVc=,tag:Jc34Po9xZZShfq5l/2CEbQ==,type:str]
          client_secret: ENC[AES256_GCM,data:cSq7uA39SxQ9wIXAWp2FkEkGuzPXHCixp6iwRnkya9YngnUhufpIYg==,iv:dSXXOKhEt/ipOD1bWhcghks+Mjpn2oUexzJhjwEt6ek=,tag:8woToirTzLvX1WqHjbLpGw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2022-10-19T12:21:15Z'
    enc: CiQA4OM7eHhdeYFpxkSDTcwgJSCnGcXyuW+RXURXZyqVtBExJLgSSQDuy/p8cJdVxnALmGegCdGggKwgIqy27Dtr97EyJnjFxmQMGDQsWh3vL/2xXyL4Gw8E1cYoxh7r+ecwI4YmBOO+q6rBIM2fS4I=
  lastmodified: '2025-11-19T20:33:00Z'
  mac: ENC[AES256_GCM,data:eEJtpukTiiFE8MIP++XEdpOL0qQjeVyBSYNc/+PfodAGUVzjKcSGFC0EmhmBYczD7ETMM6Oj4qj+HuKP3y9kImtv1DgNooOaOZ4Pq4LtvEKOpSUr7u1nrFospSDMbqmewcPhX3oZNffurnYi4qzfSQwkBSv46hXdBZJdU8F7SmQ=,iv:xN0bNx+Ko9Y49j2gojk5o6Po91UP3Ie8fzB9gf/hMvg=,tag:EcBZuvNy/wQXS81A3y6/1A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
