prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:sQbmkwJGzvCDtQ47PMl27IoRoyUymjDFk93QJeb2+3/5rUOjSsDWx676MRKlLlDDfKsY9aJahuquxpJAol7eqQ==,iv:4LLQmNucs8FYx2k4XRZgGu7c+YrQudrrJwqe0bNPOIg=,tag:2YsyxkvBAX5RQeRWymz5IQ==,type:str]
    password: ENC[AES256_GCM,data:ib/FWTBbtZvm/3YSTySvP1xnp7848H6z0klExebZ/cMdxim4tv7Agz63pCltrp1EyfJw6MLnOgUY2G1eWjRWqA==,iv:lO2/+tMwomJigbew9RM1DjXOlIK1Wnof0X9fQscCJL8=,tag:hW/umeMkPXpGz3hhVi6j3g==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:O3sVtJ6igOQDpebuBiZovwEmDOw=,iv:/mSwos0nLmAXXlaXc34YGt94u+jsorS2PBiUoOIX6VY=,tag:wAD9MlSs5H5NvSX28h/ltg==,type:str]
      client_secret: ENC[AES256_GCM,data:3q4GCySg/f8pKiziDPRd49JJxM+BMbNZ6omJcbHhHOarrwAolm9KYw==,iv:PwywAHofZrN8MKzDiB1KEG/snhKxyPUJk6lWtibYTzk=,tag:rsdXojwArfwedt1SJrSUEw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:09Z'
    enc: CiUA4OM7eD3V9D+p/xyBqP1Pr3pfV5q+XOgjalB7weYRWJU8N94uEkkAZoeZpnn/xE1NdeLfoAkFhR7tjyfEYl1GsoxYv9Tof04SRgzDOqW619GBFQ+9dp+TJ7d9SLIzmCSDF/SDj/Y+LxXtfzO/Rbsv
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:09Z'
  mac: ENC[AES256_GCM,data:pt8nGZiM0i0+Z0LeLVT71wDwSEuTbxobEwDVxJttkH+j3uBdbpYFTg7EMadXPr4wpMwNmL2JeSn87dY4QF3IS68FW5zrKxh7ARtzdnTrDkvsrRLCz3AzDdUB7E6SD1YFZrIuMaQSMyOx8Ko6A7Dkcz1LY6I9OZpRGP4lp9JnE0E=,iv:JLtazc7dwC8wWnaYElP4F1IquVcL1pjNC/YsyZqkuTs=,tag:kOqDaPzTMW2RSuA0/p5PrA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
