prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:bdRHmg5c8JHhO/wNZJjlyK89MRGg2upe1O5d6t8FKAFa9x+K4vWtZXPs+//xZClh0Bvu6H5p76GYCWHAwhqC5ylk4vOxRJUkdyZoBG3snSigljVipw/HeK55IZhU48hx5lEodclrf2GM5SY851cwlpXVnL1KfJKRIuZdOpGZ53/Pl1TglROtJSAs8hPOFFRVN0zgGg8gdzTxyItD,iv:oUtM0n38IA7XCEmYY0PBXTCRef5aPcpQHpEp0jc3fSw=,tag:wjcXgVZ2hVVFBcL3dFDRUw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:Bbt2vSi5m6iXef3gUOfe/9odt0kOAbv2nKNL6r3GtD4RDQbrwRtR2HECRBT+RluEgHS2kWDAlk50mKgBKLgjvg==,iv:BpPHzquV5yqeK2Iha6atmZIi1GLOwfElwLCEZbyCPLk=,tag:SriSF9P+DdGL9/U/nrtYYw==,type:str]
    password: ENC[AES256_GCM,data:IWaOXFjf5L2EbFfAjs/3hHyrJjc+o3psS+QPHkNp1QSfF6zahCiePi5BV628IpIWXD8WKc8y5jkdpBE800ZSuQ==,iv:UP49k4RbiqlMgUHfnw3Vf8kIffN4nJc+g9LMJNPeKSM=,tag:7xHA5eeH58pjvch61C5Lyw==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:Twg4/JHs+IW4ZvVSCU60iOLyFJA=,iv:S7w0JAV/LK5iFjqRJW0E2z7v5iiIzKZuHnispQSk0/c=,tag:MI36TK2AekiCXVeu1yt9sA==,type:str]
      client_secret: ENC[AES256_GCM,data:1KkrWzDh6G3wnDobmWLtny1q/gtQRiMhTDjcttM0zWq3oXVLslq8Gw==,iv:AjxsUbpnTxro2+UqsAV0LnhSbuCNJJvxADlJr22i07o=,tag:PYeWI4p6DZQ/JobP95nR7g==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:22Z'
    enc: CiUA4OM7eLlVbtcF53+tfg81HypbmlisHFEXhQ6PyrHqPYfS4fd5EkkAZoeZpkX+/UmxrhUToHKB85d821NZy1bpC6wfJsJx7fjwLiWa5voh+dU1NnK+Zzv1sLxwzf8TNL6wzPQWmzbocRitmqijBevS
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:22Z'
  mac: ENC[AES256_GCM,data:KjxUm0XVxYr4b84RRCMI7mzoIZ4nBP2/URu8CZWsNRzjvWPtnt/0nQ+A+HKeCdZrLNZTyxtp2UpOzMSaWMJb9I4/Cn6FQ+wCxKukAxSD99ks9j67VZrMkKYrNPffxI+/wAgTJKWkWrmSU8UwH4BkknjGUwMP5aRo6YqDepPYLEI=,iv:F+tyr3Tp14mZXBt7UkSfbG7ZLjCAHK5UlfHE1m47Xfc=,tag:EhSXVfMayr+dIm92aaStkQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
