basehub:
  jupyterhub:
    hub:
      config:
        DummyAuthenticator:
          password: ENC[AES256_GCM,data:/ufxRsGU1TLI1HR3VA==,iv:tiq/xX3Wuc/iltOyk+1i+S8CXItGyykgDwCyEV77lpo=,tag:BYJE6EbqGndK/31yAcG6iw==,type:str]
sops:
  gcp_kms:
    - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
      created_at: "2025-08-07T13:17:08Z"
      enc: CiUA4OM7eK/VsLTEtsrCh8V+s/m56JPwDsKI3mIE2+sMDVgsZRstEkkAXpa10DqAg6p8ZMfa5mZpJHr9S+C7Nj3FEh1eb5d0a1jju6HzcHi01x0rLTa2DB2b5sVthiKLT5l4SpkKBW0iPAwl3rXOBmNB
  lastmodified: "2025-11-30T16:32:27Z"
  mac: ENC[AES256_GCM,data:CyMeF39wl6w+jzYzMyxdL7MFluqlcHWvWt5O0O9CzMvBfkoLZ5lOGNMPaKuAQzbOfwMjasVugDLD6b7ikgYqsX4FKUsmlVyIIcDJsno0RIUckgiRHViSyOYxkX5GK8MQrLiSt6dwGMJ6582rZR53TF47doegJKpbT5LTCNVOcSw=,iv:jBwQfMZpPIn+ZcEAUmvTCl3g8nDef9yxKHPLiuVrAUw=,tag:r8A2XTXa8RhBPx6QeRoAPg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
