basehub:
  jupyterhub:
    hub:
      config:
        DummyAuthenticator:
          password: ENC[AES256_GCM,data:tweGHv0b9w==,iv:Gol8p3QohWfrR6Xc9Ekwo1wHYRVf8lN5oABuM1JTnNY=,tag:cBpNVtks681QiPjXmnxDuA==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-08-07T13:17:08Z'
    enc: CiUA4OM7eK/VsLTEtsrCh8V+s/m56JPwDsKI3mIE2+sMDVgsZRstEkkAXpa10DqAg6p8ZMfa5mZpJHr9S+C7Nj3FEh1eb5d0a1jju6HzcHi01x0rLTa2DB2b5sVthiKLT5l4SpkKBW0iPAwl3rXOBmNB
  lastmodified: '2026-01-06T17:47:43Z'
  mac: ENC[AES256_GCM,data:ueofKKmU+xafe7bLWzZ3EJ+vbTjadCDa3xXNEtjnvHcDeUHfUHCO1X1DD4pNdiZXuOUoYBpluGte49bWLVPBtK1L7tIj3vkg9CxUVtqel2shiM3TQctykqHlv5DRFidnyWbe5EPJU3/2D0ORY4nfZ7vo6bsLUztva9Tgrd3VeEY=,iv:/yER8KxoMaQ+wpNwPUnWAD+PFitAJfk1l35DupUXtrY=,tag:LPxKubyVsKxvKDvPET2H1Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
