basehub:
  jupyterhub:
    hub:
      config:
        DummyAuthenticator:
          password: ENC[AES256_GCM,data:l7b16pFj0GLRFzQ=,iv:l0dvvJzC9ZwpIsgF6sbxFEZYJOwKx/JKnSTDAhHah7k=,tag:xylfjLz4itXq5PqLkMGhaw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2025-08-07T13:17:08Z'
    enc: CiUA4OM7eK/VsLTEtsrCh8V+s/m56JPwDsKI3mIE2+sMDVgsZRstEkkAXpa10DqAg6p8ZMfa5mZpJHr9S+C7Nj3FEh1eb5d0a1jju6HzcHi01x0rLTa2DB2b5sVthiKLT5l4SpkKBW0iPAwl3rXOBmNB
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2025-11-12T17:57:07Z'
  mac: ENC[AES256_GCM,data:dfUMLvFA1KHyVrJse18yCN+ucpXFknhajDny92GTQ2oax21Ri0q1ysjzsYfDQWr2HFBMe0F+JCh6RndD7VTRyhQbXcbMqb9iX4KpjGzmjH5jclstypsIyIE1awSbrZZR5PHYepIjVuqOvxsvPKAdn07Br37Dvd61e28yqGoJzHE=,iv:7Qd0ylKDS26IJ54f07IgRX7M1vT6OfnhO7me7Xo3fO4=,tag:ExRzu9o2g3W+YH2w19jH8g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.10.2
