prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:VctBjymkQwMSawBX0pmdNbRbaxAAAOaZ/Cg9SguIgt5XM08SotvNQOg8lQOzX+sjIfNrcIqSSM5t6J2x/whV0Q==,iv:CGK+ovpQR6R27y2kz1BovNXpvyChKsJYMuYevndQyaU=,tag:/g9jv6FmAdbjrhHtXvcfhQ==,type:str]
    password: ENC[AES256_GCM,data:YqLEbbuqD7Y5I93L17rqXTMIU+NPoeugvdJHPU+oGB5uTAWm6QwRZZRDTRZQcjv3Au/KXNzHI9QzHHYTkGtzhw==,iv:x5DeBwV+jFuYl1ztGx1QnV/hUym0YxgXbZZEH0qrouc=,tag:ppr6/YT5z8GQ+8RrPcsY+A==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:4bEA0T61wS9QOFjZh8sOVqnB11c=,iv:VAiTWhkfus2Q3GRrqZ0pqeS1tLZDmSssMmyER/cm+wo=,tag:ESygmcurXpdg2P3YNyvZNQ==,type:str]
      client_secret: ENC[AES256_GCM,data:T4h9XdYxcao/x/8tIaeDm8nIpcC2Srz6xyseU6IN5ZOR/GeEt4N63w==,iv:NH2KyXtI5PQv+u72S5khPLbrufBL/wvjochu44P32w8=,tag:hRgQr6FeOjBqKZLH8HZRhA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:16Z'
    enc: CiUA4OM7ePL9ud5yOb1wyHiEj9j0bxM7Q0GnDMvP4kJSWnxr5cnmEkgAZoeZpjO701A64NsS4xZTW2c15l3H1KNyofxNakw4irA274x3EgITDbUEtUBD04Pw+/KWRc6pjZg5MlW6xeDkKyIyoRlKIYU=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:16Z'
  mac: ENC[AES256_GCM,data:LsrhZXgkqo+CpXKuU9CepC0mihSJDd4YEZegMi1I1vbnCxDdQEhXJhu+55sF3I7PSlh9govQl9CrMvO1ZGWUfLkw5S40NNC31hUaG8OwJSJe3vqdP7w/mxrhlK0IdUPMjVvsg9olM27Wf0daLaI/FeZsCZdBX9Nsh+hjuPYoQrw=,iv:eqBiD3YFsFvvILn75Ph3M6hMA/4CG+HtzsXQcI17V4s=,tag:u/frI8mRssKiVyBrVy56AQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
