prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:wLPYdftbsS1gcSNtHR5DHnEEgyb82IVL4AncA/8r3Ux7I4qmov8QcmCGV/C9BdNQ9igNo/QNVCRZz+qCySa5/qDZ7k6o1R1XbLguy7i9seJ91A/oxD0hfhQcv0LS49rhMQTMmESuc8MMOO01KK9UG0JZdr0mcqWuKG3j9HQQKyMLSAfMB4tadBJJjiT262e3VLVkRaquzMKiepE3,iv:W0YN+CA/5GxEiJ5ZGLjsfz96+3TO1jR4v8ePPCrkJAQ=,tag:82ICuzv9srXnS/kt5UDqWg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:5STTKC92XkoSUh8oGcVjGKr6Yl9t0O2YOicLy00ZKirrRu0p6EPDE7lU3U9CQLGTAnBGOVTTOyl2fyz2oK1+IQ==,iv:M03YNaKlri2WQcPp87WrvMH6wu7ldyleMu8KaMpY5HE=,tag:ZAZ2vRV8Pr230ukdf9YUCw==,type:str]
    password: ENC[AES256_GCM,data:uJLyTaxK4HpJEzOS7beZ2NPQqA311wo2N4DHyCcyaaCO2+qE8kWMvV1AjQptp3TkfI/PdkSH6/8eRgSy/W72BQ==,iv:biHw+TMskLzhe7RUZMn7vE/IorEI5iG8U8aAnmbvvvE=,tag:JBqFCFkNB31JU23Xl+PFEg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:02Z'
    enc: CiUA4OM7ePLJ6r5VniSH5S3Gks7GRzm3oVHzqemy6WT4PmEeKVFAEkgAZoeZpsOf3DxCz/6JCEvIMJkTJoSqtEWbzcX4nbwENfG9aHQPGV8z8F4l2+T9a5rmWrghbbFb+GcE/25H+bTVBA3e8Bjwby8=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:02Z'
  mac: ENC[AES256_GCM,data:732z2RYOcCTGKUgtJBL/U8aXBggmhl3ws8MZgkbOF9h/Nd/QV0bWD/qkuSmMG9mxU9UxCr3gjBbYC4oOdIunhEEtRiFZdC9PyGGPMKHI/31uMVkOR7BaCHmL2TH4BsrwzLdAbUWhdbrq/TkstdyocihaSLKT+ov4HbUxg/xqUPk=,iv:If7Ux5yH18oJ6Y7jAl08M4ado2ZzZsg8vS6OPF1fiDg=,tag:oCAu37qNK6dkRL/0xp/zKQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
