prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:SjFxgNSRynhPQnjAf1xb3PI7bRVBwVZ2CKIOQCQhN1hqlzcs6BIgrfdO7GlEbdrDwizQ3fv6jxrMXv03rLpD8w==,iv:Hoaw/0qGhsdgxjt8z5W28euaYaBUL0P9yKYuQoyZpHc=,tag:SvFPJQuqcZzLddOgc7RhoA==,type:str]
    password: ENC[AES256_GCM,data:fuzczd16qPjE2gTWHAB3XDtNMZzklbDlsaqnBMHTOKdTleFaLgIJXtSFIn0ya23Rpq5ERR9dGe3QUjCO45i0oQ==,iv:3lVrZ7RSamtInK1qv58K5i2tHGw2ejb0v7qiwi/Etn4=,tag:ixosr10mdQCoU5R/3PgtFA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:40:56Z'
    enc: CiUA4OM7eBKy13y2MUMvvPei2oberPSOi5P4DQ/6U4Cvv2fXMRdaEkgAZoeZpjpG8oN4zzOyqga2pX6fAERqzERtXTUKiSgLYp1s98Hr27lJJrNqxWfgfZQSbTWJsnVH2XSeC9H+XkznaOALaf8+axE=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:40:57Z'
  mac: ENC[AES256_GCM,data:+WWyuQtYnPaJS+4o4r/J7oGP9F+LOxLwiUmiMqC0mvdvtmj9lq3XUlzmU0NmG3KQEIjONfRRW/JOjcyhC93zKMz5EUfLA0DZ5WtWFiATCggAeAf9SAieTvCxMHpkJ2MU4P1xd0ZgZACSzxd1zwjDfeGrCDYSLMGFhCs18OQx4bo=,iv:SqsvNDv3+5ar6T8G3x1A7DdtUt5q3J5lzpSwhXq08uA=,tag:xaow0TP9LZxYo2zFUEG5PQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
