basehub:
  jupyterhub:
    hub:
      config:
        CILogonOAuthenticator:
          client_id: ENC[AES256_GCM,data:r2zgiteKZPMEEOJ9l4NDLBLi/e11KovO6fVzs0DpIcyr0IA9UmyFj5Nmnk0iFwD8v/BZ,iv:lu7QVAWZD6dkFR2F4bPllP0xbYUfaybEd9SoZfHfsJk=,tag:uYCFCqKqW3HwiypePTGuAw==,type:str]
          client_secret: ENC[AES256_GCM,data:806z/qybowfoXw4/RVUUk2mz66x5nUTkFOBzv2J7s/3MXDdf0+5gKM29PU4ZoZ83VgGYN9A82353+gogcaDdlGfyzMQo2UaeLI2Efsd5ks4aBGaUcjg=,iv:jjkeSLPHYhsgipHzkfJBgrIVy73/ZKdUbDaAVUEW6p0=,tag:sYC/BcV3JSYxOoTKse+7mA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-09-18T11:05:32Z'
    enc: CiUA4OM7eKr4oWzxTjrny1weQ4npthdLxvqmEjA195fTa3PxWcjMEkkAq2nhVc/CaVQ2T4qhofCoPKvJxrD0XKNGgveb4ZnX63xSVKk7k2BznMWcNfPV3RzN1NtIH3EdsOOvQJ1jjhcpWO5ofOxb+GNq
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2023-09-18T11:05:33Z'
  mac: ENC[AES256_GCM,data:Fg/nEC6j+36TbObzn7d6phI4Wr8OgXYSjpJSqrCnodHmkqarkDrKhtCMMVxmLYgzLK1sJrr3UkI6o+uqGQWw7cz8QE5a+Ma75W7/ahF9AQKUILyUd4RrGyU4MHkKAYnESn/MqhZdHPGqP+R6N/PtBStalM/W0T+ptdY516NudHk=,iv:QPC8RJrd916R72F9syk+EFa0obhcdQxkFYnXgFqjWm0=,tag:363q5RzmftDnZOljkTayMA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
