prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:QO9Y+5JcEWxwwFPyWjzBlXpK5nOFgL4C5izb4l7DucO0UZtCUYPXausN/6OwBSOCUs0ZDbRSGE3iBxdc2JPsiQ==,iv:EL2PBN+N0p1b7JpDeviCCjO87yIQfZldoP17KQ7GPFM=,tag:hOnLXBYVCKo4wC7gYbcjcA==,type:str]
    password: ENC[AES256_GCM,data:zdKcuBXohkYCR77bfHAQJvaP8lIpy05ud6Q5TLscJMvhloo9rbau5TzmxlzIJKRyfWte1VqBQJ5UKPed8sOGxA==,iv:nvLvSZnU3iqFBTB0wkhGJ3FMBd4D6Rzxh79AN1m269w=,tag:KswYiDdt5JMFZ533CwBwrA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:12Z'
    enc: CiUA4OM7eL8DM43mD4BMkdRbKdF6+3PLHOQHCh1HM4wVSD9rfdBAEkkAZoeZprby5UINfQcEKrscCuodN0aqYA1uAf9r/36BVxeDE3CHSoZ3Ptvmhq1ukecNjYqgud2sMbtX4+3AkPXDnoT0/I7yrnhD
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:13Z'
  mac: ENC[AES256_GCM,data:vrT/HD6xYPJtdEnRbTV0gpyzUXaiqIHZxXA2PG7O++J5xJcHFNzsdZiXE6FOlxtueanSdfn6hdvzthmaIqO7k3Tnrg77FXI3E/lWiYroSFxDdnnmYlSnUWx01DuyCg8Xk4JBtQ04QeEcaiWrf1g7aUfkBpjcoZaGTQ22nk96iq8=,iv:SzNAS1OVBhaKfCrLB4oez9ixEGgMKvM+atLSh2qo5Lo=,tag:ThVyykFcVf3nW8vGcXDuNg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
