prometheusIngressAuthSecret:
  username: ENC[AES256_GCM,data:Aasm/mL4U++rwt/6rz4L2/WpJ7wjItzmdwjtVb2WEk7LBleiGjYHdERk1w2lQIj1eGAY3K/2SmARRL7dyBw17Q==,iv:ed1GZFQQMGv0wsfWxrKz5YQBNyzPqCCqltPw7ynKgZc=,tag:VmimyrKGfyKZqrmLDiv58A==,type:str]
  password: ENC[AES256_GCM,data:8tCZRuMHSu3SkVqqGFiWJvMkDLLW1bePlnNbF7R5MjqnmiLdtQ4Z8/MRI3OQqljEjXFwzUzBa17eojkN0Fp8nw==,iv:tKIcafgyTeW7qwwvxMJhT6T3DKguHVl/TkRy0nwXzeA=,tag:BePTfijmqA98hucuvwsk+Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-09-13T13:09:48Z'
    enc: CiUA4OM7eCo0ChLrJtZPIdK0esBY6yPJNCBOt6zpOR8mqMVsLIP2EkkAq2nhVfzV1NUaxv0zFlqTejbtpDdHTNYqx354vac8Uwoi3gpabrloRUaFu7jsGcaYGK1TGHLxe4tnvT/XAyEaoEU/4cOqCtXm
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2023-09-13T13:09:48Z'
  mac: ENC[AES256_GCM,data:PTkLlif6Udxq5J1gpDvsKz8XzP27/rjNI7xSRt3RXsRc58I1Wv+3q998QZb/ThjFwFRUm7SOosakCsQu+sUF9BdpUKFTDCy/jvibdEUyVyFedRJEN+cuq30nkppmgYhXLFOC2xdYY4fqmuZ+JzkQ4ZvKbjS9vLprvD1q3umvXG4=,iv:WlwV7L5eTznuJuuzsGr2jshmfKWYqLXkrQR/Un9gZxQ=,tag:w5nRR64AaWZ8fLy9VqyRlg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
