basehub:
  jupyterhub:
    hub:
      config:
        CILogonOAuthenticator:
          client_id: ENC[AES256_GCM,data:hPkNAOd+268s7aHubTXjWAFE1xCjbpVhIGnwZVLuDRbzbVgwnzRgUaideNNbMM+DhOkB,iv:JdbuWUtIfdqHNMl+G2GGgjPQIUlnlrV+jqT7WX2s7tY=,tag:gYjABhP+nI/DPhbCL/iigw==,type:str]
          client_secret: ENC[AES256_GCM,data:OJSfy6DLSWyMRrrmsd3Y6vpmD/06PalNq+0Q9YrYwX0vbDj5sViFZIX3ZIvZ4HYW+o5bxti8/0k0p42A0xdMfMIFgTdgYHcOAmmAJSrroVn/C/Z/L4g=,iv:APEzlXwV7q82K/QB9e9q4d8Ua/Sjgw7ws/LSNpCjgk4=,tag:AoG/YgtuwfX4UVGi0xlNOA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-09-14T11:00:17Z'
    enc: CiUA4OM7eDQX+9H6FN4u1GdpFqKKGuz4KdAnZmxJeTqirX6bXio9EkkAq2nhVcrRfqiXkSIHUzv4gQ6mANVLXrfAzpPbEjlJaFdLf08AmG0SBTTe1bnnRaVhaZTBkWNIL7s3gp0Dq60uo4nw34rq4jPp
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2023-09-14T11:00:18Z'
  mac: ENC[AES256_GCM,data:jcJVPtC116vxS8n5EC9tvd3NCWQ/dZLmGKhMub16cQL3ZPs6W76M1tzm3K4QL3N3FPzJT0CGpBBo9EfjmjyZmPSwI+bqncWpkrDMuVu1Lt73KYIGM0aqkq/IW2tRZuKVNkDWjwA2x5gDXNoKmTSJ+T3eVEJDmuOZKdrYtH/ttLY=,iv:Vd+Lv+KUUetTb+zbue9hSIAeaqYOJj7B4W8LD1QdBng=,tag:XapEpY9z1iuUM6oyMGjqUw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
