prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:QMg9Y6KjSvY+/3ZNuTkSUlYV+HdbguPaIkq7rdt7STsQcSRUa/Nggq7dnIZwjFrlYiELJNCfovKVYXlDM6foMMa80fGyQOl7+Fgm72qp7zchjzeh/L5WevBSYno/Ym+dLPuGn4hnpYrOmD3lwig6Xh4FRHjVl4peaC5jZVFjs/JNcm7TdvZEfyuValRAP5TGLWLqocGOQNalt1KQ,iv:WEcPWLt2byvof+Q0oIeGT5Ifis4FZcDFMBYhp+nrgTE=,tag:Z56Gj0/ODryffhag7+Bq5A==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:Q4Ei6iBA2aLCQPjznAJzfPNTTW8xLt0zlUEeqj7GWWrvd9zoiweTXsmAqig43+mcJM6cfGu96TFiVFhyLWXHzw==,iv:lrs8J+WidQyTtuZwV/ZRQc9GGEIcARhau50QOMlYXrY=,tag:pSqmewVOt9lIl9rz2B/dFA==,type:str]
    password: ENC[AES256_GCM,data:0MJTKz5FzCCNHNqoDQmr/dcOL2fuFI5nVP5bM2KsaTBJ0mwf/NEgNrIifcXCkb6QOSSR8WrqKp3y26cs4CdkqA==,iv:cj9nfw//0mFpDmHNDwMl+7Dw5vaymZeiEkzHnL6HGZI=,tag:RSZUDHaIIqLyXbX35kVqBw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:18Z'
    enc: CiUA4OM7eJK4eCP+yKNb8JwAkThrRoGKQmydzbOLjf9x6IOGUfsgEkkAZoeZpna3Q40AW2Do+TeqYymnAxE70VY3TGU0wq7pyXy4EjrphQ9YLojh7yidjFDN0So4a3DBzwps98rdSnUlVX6/FVa1WSox
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:18Z'
  mac: ENC[AES256_GCM,data:lycjVTfLpP5U67ofhyvtQMatgopzzSfcPn24mM4Mu6dF3Z7DyT0YOkCcek6q3DrHrG/V6EfuSDlw+Tnm70f3vul2thosCtbK0JK9lj1knHUaE5fLaUp5b9KjwYx6Nyl/RmLGeVVnHTx2tKBMSmf/3NlIEQAPSrB5kqHn5q+fsMY=,iv:+qjNmmR7jO+IZr1q9M0PfnK3kjUxbY+28ZuHFnA9BZY=,tag:yaVj+6UIAEfNjajHlMeutA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
