prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:/At+j223ZnlS7HCLOC8CzXFkvr5TfdKhJzp0iYFewyeAUXLxlgcXLAh5bqemx6C3GHJBFXU2kW4h6dkAHduLuA==,iv:AZNZd0UObJgJZcj06KYlhFtyi9sfCS5wTuc/tQfI/j0=,tag:IfyrMJPH9zHiaqS6s2Qxyw==,type:str]
    password: ENC[AES256_GCM,data:KkzwaWtwEduxlVacvOhi3T/NsO1rKtdpowlPOEA6jDviA2ahh4NNfOpdVwZ7x2w/Ymj3bRLG7ANX+6A31nLvHQ==,iv:pn9jkqygMZ2kxHJe3y+2eQMShoKGYLUvw1sCEkvgV5g=,tag:d7/QhGm6T183Mq81Od8urA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:15Z'
    enc: CiUA4OM7eDm9CKqfxeeIuXw201enVfaKLHXvGxlVfEPHHajY3vvSEkkAZoeZpjJitJ6RYYl+vnpUSfeHUdpV69rJCZbtaF9CjUst5y5zgg0KoEBLhfz9R9aZF4227pl9hfYdQfkNCkUuiTYyiTEtxcM1
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:15Z'
  mac: ENC[AES256_GCM,data:LvJ4M99QCTmM+Z5+zgpUVDhCoBc8RKMQDywvpQ52PrpzbNWjFOVzYhUbfFkFCA730pvWaUOQLilp9KHz/vdnw+/6D29/TuieijWxGxvRzDYY00XeeGqumgKtv6p4CGjXlbwjd9NQhRZkbfTNj/JLhCv68ZGC31Kx4r+j6bIFim4=,iv:M5uk2/h7lAeEtrnJmVoU71RReXMwW0mPC4fzIXw20dQ=,tag:2gMIlQLrFT6CSq/Shp18fQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
