prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:yX/jY3X0OZlOL+JQcXhVpkJw6LXZVO8QC3oh0tuskZVJ2hEZL9IKTxqYe3Xdda/1RGCgKPQkSkQ0q80Fb6/XFDdmgcvv9ZAhmPZ1zMG4AH5Nb8etEUe2J9mmE+U+4aAjeZ9iyA/bntGbuhTWNOKsUMlhyUXBM58jxnqforkTDGOH1SALB+pZtneZ31AvVeJxt/WMlLCZklt9vfDU,iv:nxWu8bvtsI82e8woL69kgMRCPk9pY2QgTJcI78rZ92I=,tag:K7tzsa5JfLzlsDRq983EGA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:rOqMEUaRw9cnnk5gOdpeNfMVH+jpc78IF6JFv6j8pmetkfi2wqDNGj9dOBaxLh3AnbawyAwekU8SfmbKJ2acUg==,iv:d+HCJpo9jrJRFnqlU26JTyx5nmCVTx9u1OCFnBnMc00=,tag:MQbNuXsk67475iRziiYS2g==,type:str]
    password: ENC[AES256_GCM,data:VUOlmwvM7HmVDcpIfMCwRtEIlgKXNpn6x6zE6Xnn0mRGZZUuEXLnaIik5yqKAb4YC6wR9a29jyY4nT0RSKEAmQ==,iv:C6XRjLvBVI0POH+Fxjtds0x3pHdMl3uKyCH2tvVjGXw=,tag:bheTptic+gOxvHU0lfQa1Q==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:20Z'
    enc: CiUA4OM7eAGMXu2tlkK5c4LtFDV7M8ydWs7QQkoGYsBJnJ2hMfFxEkkAZoeZph7xrLLqjNr2qN68MfGNgkl6FeG1BA+Wfpi/tRax+N/LuByh1uwWvH3JIxxbKq2ELSFtyE/smfwWWeVUMSafnIEAYwGQ
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:21Z'
  mac: ENC[AES256_GCM,data:96mF4BoQhmm6CvH6DobBl80319FD5DRGvSME49vQJvCystZiXksmfG1xrC1sTZdXFJsd4CnGqlYMfmETQ2Et81AvHxjx8OYpdqipap2vikvKJyw2La4Vo/pJ/T7l5CrWZMZ9RUfh8iYeDbgtYfbAdVSY05/eI7GqRDGvXc2u0xI=,iv:raUgQFlbMltEJlRKOXphtDlkhuU7oIeoI+QMHJv47wM=,tag:SOjQWQ3GjcUH2iv5tRwbJw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
