basehub:
  jupyterhub-home-nfs:
    quotaEnforcer:
      extraConfig:
        secret-quota-overrides: ENC[AES256_GCM,data:dVqbrF0x/wRjy0fucxnBBBqVK6Aa1LvmwGZHCurrHWU2RUm7bghGizvMDA/AVcEpuqQHi3/HG9IMVMSusjLCsPOaiK5DQosFWVgFU6m4Jd1CwDajPiHNraW4eE+xHwNv6MPWOqwYEw==,iv:HfmxcE7LT+AfaV7KTejZ8oN+oWzlkv/MoQ5NBKtFiCQ=,tag:xqCl29H4iUFuPtZ3oYaJpg==,type:str]
  jupyterhub:
    hub:
      config:
        GitHubOAuthenticator:
          client_id: ENC[AES256_GCM,data:H0O+Ha2N/Ax3K6luitZ37k6EQdk=,iv:CP5BGeDMmE6uznVB6utuW78+UeP8Ge5CnDmocZIkSXU=,tag:Q4QG+b8Nq36bbANHIAfpuA==,type:str]
          client_secret: ENC[AES256_GCM,data:a0Xm3m7cHRCrBdV5q22ohFMYjdolj9dDnQhg9cG5E9W47Toqxwj2Gg==,iv:/1CHsZez3j26A8ODvlYgbjXtaRsKbGraxTzgoF2ZURs=,tag:cN59IZ+9J48QxSJ0IiqsAQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2023-01-26T14:56:28Z'
    enc: CiUA4OM7eCKAfS822SeCDOvwyvK2He3x++XchB5U0Z2uRygrlE6PEkkA+0T9hQrtx2RjWzpuy8LDTafDdeFrNE1Ehco2aOXWi5EaMoT3PrOR9aaeynZo+a9RFNp3duwN37lnDIEBdrV0pxASZ+Ok1ct3
  lastmodified: '2026-02-05T17:11:24Z'
  mac: ENC[AES256_GCM,data:+En1mE6GVnu1+q6GPmUIKiGw6vvjNBL1ST43YT1+FTmquHpW5+WziAxp69iPiGCurvO3G9MhIg84Wkj7v+AwmMkBmqN4kto1tYceWagGxkxaWz/lWK+bi94fkCcjmVKIdVtSr1AR96YYjjMIO4643mW5iKHcF5uwXgVava8rq/g=,iv:yLwmbpwaGwZMMw4DfadA+boPADbk526Fo0wizYnQyrs=,tag:5757ZAcJMSy8AQXC3RHWmA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
