prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:cYP9Y75W2e3HAcEjt+q/IYCUfx7DeRqpfFWI5vgi7tjbHiGQCT+Ow/cgYb2QBMxv1r+zgeJ1cDgy80SO1ge85A==,iv:dJla169ZzA/zaJIolM6VzXK+4iGW5I96V0eraqbMEa8=,tag:LmjiE5T/SLkTeIhAPwRP0Q==,type:str]
    password: ENC[AES256_GCM,data:mmPvDP7CK4wbQB5bIFBeIFtILvl5C1OKy761ixHtx1nye731oxNuO6AxxvNH/NMVlm4r/91w7hU7R/WEJT9toQ==,iv:pBnolvom2nUqFRvTkC/bY0lhgHvsETSfoLZy6Zfg1wg=,tag:tojh20WHu/L6tVjrw6izYg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:9domqHDdI4ehwUTok1N1D/aEaoI=,iv:3VATebQSeRBcSXOKBgZc4KaYDpuV5iEHvp7XBUdEg18=,tag:eSoA/WrUp2n18FVx7wGc1g==,type:str]
      client_secret: ENC[AES256_GCM,data:5jejDzkHtM2UGsDlRmAyGwNq8USt0uzkDgULAxokFeoxgcq1t4QFVg==,iv:CLyKcZSGi+ZN4uDtCBfZqqsZktowMnVW63uSgJ6dhjU=,tag:1WAm7QZMYFbzvvVuDnGn/g==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:04Z'
    enc: CiUA4OM7eDbHL1e0Aq8yZea1l4aeTiisjlF2ymz9dfqxl7nMSfdZEkkAZoeZpgF8e6UFcfC28jsfj7NRJR8NEJKaMuwCLQGTLB1Elzqra+JY2fqibTqJ2SYvGJPE3acdMhHZu/EX4Xes8GIdzF1zGl6Y
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:05Z'
  mac: ENC[AES256_GCM,data:zH5A/Lo7+0Exwmu+i5yS2waEilYeuEEKLtQLFWc5wWpbRJ7yswHcoBvo+Y1tCuISXySMEyrrd41f7cCCL1KP37kWETKs3jXnKf8a1lor3EQ+Ho1aG7yzkwUSpJRNlfE3SwvsYvFLXBo9yGF0S1Cyv/RkveOa8hw6Vm91YyhmAuE=,iv:9nPrXJYRBxMj6dDXN7mexbeSLO8MpO3VIy1tDZ3MmV8=,tag:IqNxy/Q4Nv6gm2+ncnNBeg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
