prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:UHB3ilZOiXz7fhgFt8hzoGNVQXDHb8ShGHQs7yPOBCRluuv8yVlN+79amFz5qNH4EuJne3U1IfazfjTmgrZBBncJ0K2oWnd6asnhD+Bn/LnGCGfFvpsta58iZlkEv08zeADoS0aupGowEKqLGQG3RyHAXP2ibgg1g69vgqh5PGZzMf5PhyEZcRetVcVKX/ViUfK2aN7hmRzrsvlC,iv:iFywIcfda+tOq6BiuI6gaVrzBq1iCc9Zcun8WOxowSU=,tag:TicS0lVWTFJCzuuYeYaXeA==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:8WOp+oepcxHVkgc01U9n3bcPXJSTxbYwNnqWt3otsS8i64KhtHXoPCPoLT9fAcPMNGJon7pV+Dp3tEkNplJhMg==,iv:iOuFl/jDABTwpZbxkwtx/Htm8eh5a0ww0pmE2Cnjuh0=,tag:IcTKUYrWALbwpRF9LL2c3Q==,type:str]
    password: ENC[AES256_GCM,data:pXuMi4NKMFGTOWRsuhfEjIO33F/10CLyJzBQz6c3bBl7VNwAy/zdQQqSCCJsA7dZUVGc033ob5Iekm2IKJY8aQ==,iv:jSM7gT2WtKKSyBX+UC8oVb2riX7Sn8DNTJ1K7nF1+20=,tag:bvdicHaQGxUR2UZ37sgkJQ==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:mX4YwH8vZqempLnFXSd5B9avO5s=,iv:bfv7IuOTCZab2GyIinR/r4UVoK6Yz26fJiHg9GITozs=,tag:qK1/a9aQb9ace7vKfV9zMA==,type:str]
      client_secret: ENC[AES256_GCM,data:4kKuEYFh9yUr9cDyMKVg7EoidGv+mxCA33fq31rcss/NSr9IwcfiFA==,iv:xph35TitqJQCBMgxELRMKO6sjhvR16HPKc/lVEb85DA=,tag:pHGPATWnoi14imB33sEKjw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:10Z'
    enc: CiUA4OM7eDjom/YhqyJBu4YcKUq215OYU8wOfuAQ/IhPKC0BzdkvEkkAZoeZpkoKWUGNMal1SbZzZnM8gvdAO8v6SB7Q2AEzwwF09MxW/JLPEP19Ud/RdJKp84dzL/V5xPY/e5C7lIB/K/SaKxHPqPxl
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:10Z'
  mac: ENC[AES256_GCM,data:Oe/EpJMEQWY6RHdW2li0OQAWp12Ly86TFNTyy0UDLISAunnRbqyc/LnbB7G5mi/3cFWBeN6VvPMbjnpmmojk8hPOI8dgeHl9Y5s3FY3xKvpuTEzyVQ1k0PZ67QyjVyiWgyG0llek+noIjQlqxXbPDc/op1Rgos6TkyfSiNFwz1M=,iv:ZFp3f0rmBUc0pHGhe+uZ4sPDJaNZcCbDxE4aExLC/AI=,tag:YqxWYrvfA+Vnbr4WG4uN7g==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
