prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:XuQPUUzIlId5kwNxj/yRg7YC8T8JggWqqme3ZTOtGMcEYqmJGor/gzChNwqoiaLuycnUimgC+KYlKxjC31D4GJQDeGo9J5omIa7Q5TC3FRZeMwggflmmFrYJ++AtP63hQhPV3qBKpOBKFjpGEVu4pn8j9XuHBOO1ja4Te5MauDHI/P86+dEnvPz2+EhbpmMhPMxTuqSRq7o+LI88,iv:E7gGuqd0ZhIYZm8jbKnGTk/vMUaHGbsQX1d5ziQGIbU=,tag:HblAg/E2c0QQmbwwtLfrcg==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:cGKPJzhDIxOwWXVVrecNSx1KJ+XnOHx6U8w1URYD789l8TCaA7F8w4iwgyqnCfYtCuLLRbyxECVtGTKLeydG2A==,iv:IkxGNrab/qsHUGapbLsqN3+M0LUBOZlG1d7PZvMcGs4=,tag:8p67bYR7w3BG4WFRCS6lNw==,type:str]
    password: ENC[AES256_GCM,data:jcXT00FChb/Yj5J8oZgs0NrYFA5MOI6lHM2ukhzGtmreJEKBOFYeo3DStWkXtOXjCOHQlJc4PcJPJNnQMey8CA==,iv:sTQB7vwOEyROnL821jEjKwBuQ4neRxgl4qlp7jEk6Pc=,tag:ouZzQZvTnwojRVZupS7FHg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:15Z'
    enc: CiUA4OM7eKNmo3Um3bLBklca/IZm56sG9KRwdjU/Bl3aa+PWIIyGEkkAZoeZpt22/M8rSH2VaI/eR/HX1LyZcr4hP2gD5zXz23l7VFGmdUw80jByH2iX9BIM3c8pvgkm+sCv0DCkmtuJfFYIJFmD7l16
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:15Z'
  mac: ENC[AES256_GCM,data:2i2NO2cx7Pnm81oAYXEwTjLDo1/yeHPBLtE4/pid2kwj91n7kzY7ZQi1GC/Om2GKuJdt9vu5ccVajYfuYPRjOYp2bGq3D4Htgxhgu+Zugt0n8hp8z27Zb1uj67HLcdABibpefSzutdq8sB8EkTvueqPcow5U4FojBtrWjglLaPk=,iv:hoCGOtM4q32JXXaM42JF7ZnRqGI8vxdvhfwx7Wru/NE=,tag:h0iJ8lJB3uwQ4ss2Mowhsw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
