prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:0QQDTpvpz/pUM5Qhj7l6nxfKAe9XGFUngcB+QBsSXvi56U7nJF18bBioqw161JxADvKsTZK099HzFnVVkaLvww==,iv:w7ptfIL26IoYPC0G7njTcwWdFtf7Xzm0/eypjNsNhjU=,tag:cj1HK4OOSVgIcZTVne1Rfg==,type:str]
    password: ENC[AES256_GCM,data:R67jdkGQuxjAS/mYf1EsMg5Q5qE/vcedXeDBeqII851I7nkB6pikewjU+ufuTFbO1WfBnJoI9f3Y24WksT+MoA==,iv:NPBh/HZO+RCxtBSSSNjzTii6sgSHxKsaBgCv7QOtROk=,tag:FHWeP1IwRrqXxFskBsCjZw==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:09Z'
    enc: CiUA4OM7eGzt3oJjBrQjE2k9dKC4Tw7rdTB4f1GJ50A7QQU9quF8EkkAZoeZpqN3RkaJIOo/Edd/kHvjxfokytQZuRNFOFGrRbfKvQforUKFS6nbxj7QqaU3MkAUPynW1jZG1xzhDz766+QPLwsG42cN
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:09Z'
  mac: ENC[AES256_GCM,data:OvN99iHPl0DxHS8+eWhlzOcC214TCTmUHF/daFs1VehkiJ+ZPsgkBWRl/yRBwP6d58uvCAMko1nqv4zKhUno19S0G9CdJUcinetkSUA2MnQ0lydKnbBjAw5U2VPdTM3gvV6N85Kb3WWjdSwNI1j86CWJ9H4pqRTzAE4Gk9QGt3o=,iv:QGXVhAa3BlOeGgtKAsSdrOjQUUZ8+8Ql8Bf1O0oi3X4=,tag:qAn+8u/61JBcchOJFdWgbw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
