prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:sM1DAMaOcvSJw3TM5BV9J+nGpuHi8SJIL5a3GutqG/RL159T80B4CV2XUSRrk5wVT9Cu2D96oyNN1h5B5AtVPA==,iv:DRT0bd38HsX+iu9SMxKTXHcjd2Qzruy/GFVoPPxpVxg=,tag:8bXjtNP+csAHk9W2kj9eWw==,type:str]
    password: ENC[AES256_GCM,data:MpSs8ua0kbNe3bNpdlA8fFVLMI6IM82Lmcq5Pq9p3j18TbKaxKyy9WCeRqfXyduNYF+RC0kHw0YXPJ5Q2ZN9qg==,iv:ofDUEAULDeAWNZQuGTPvkDp/fZ3VtU+vf9S8F2LqA+g=,tag:tZ2V6U27TXI4kgz6GGmCTA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:40:56Z'
    enc: CiUA4OM7eA23HzYhMwnpsUkl3VWZdBP4v8ft+ghs2TCjsW7XikSREkkAZoeZppLirQMwn9j2YlVTcy/LXaZEFs/IfEDQDsncdyfWe5+Eco0zznsKhhANiQQQLDIEXmynFsOr3zpUKbmTWM149PDA064C
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:40:56Z'
  mac: ENC[AES256_GCM,data:8GUPWeWFs1VcdxS9iqR8ouaLMUv7n4rJj7zFRlv4id/DaDqd1mKXYMnOxSwdjoe3+8uS2wgpmaBf8otMCfO6BVKigai1IfdF6D4Ooxs2eNpIgSdtxMjRV7NSsDcIGvoMPPQBYYeJUXXp+UadiLwtumEikIYGOLWw91VVaGM5/gA=,iv:b74gvotU05fnRkji6bjm3mzl2VJ0s7AP2dUjgvcU5lI=,tag:ZAiXJXdGLtoZHmW3152lzQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
