prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:aTplVTDAz4BmBEcdFx0rjgSHFVwH4DYlJxeRPsA+BEUeMuANFoeLU8YfIeXjvEQUPIritPXKCK9FSg1lZ7bDqusL36ChwJtncJr+KI/KidXpj8FYZADEmTLeE6w8D9nvpWgOrKcwAZEqRFhngbmNnmaiv/aZsEtgrHEO/P7YN8qSjglXuvRGgmsBfiR9uN8QXz8DUhDUXsmMJvgr,iv:MTnd/gKNaOFix+Gdtu0iHpvWcZti4CIhHz31HgkXhPI=,tag:al5/QwkpkVON0qFvJx5dZQ==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:pU/z/9aezU0Xncg+hKjtyODTJv3ebe4CNvUtm8UOm/FkfZhAMRvKZtjW+5eRwuCMhPX22PoMco4rC0WjfbD7aw==,iv:S7E11hUJPnCF/3ujNiDREvZYamZwJeSbFQseSCRlaTk=,tag:nCsboQe3LlRN6XZHUo6Sog==,type:str]
    password: ENC[AES256_GCM,data:eHr0HdoSejDPKdBA+uXjmKm2cUilRVlMCNIh4rRoDsXr47pa71qG2jciHU2dT0pCAyxrcuiXaDoWE+mdWva8Aw==,iv:8D519NaT+z7AWNRJAin/Wj53KiKmn3lfLIbjypEtiEg=,tag:iwAtx08IT0qFcNug4MAeWA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:01Z'
    enc: CiUA4OM7eDjCx9AeAwW8yVCHJYQzUM/VIhxsXGr9tCR6Mv+1NJsjEkkAZoeZpkoUBjbDSAVFjNslCqR1bNkpG6nb2NCSkCdx3qtdFwpCHMhpe6rawryutq2in6FNa5oiS9VYV75kQDEQ20q6t572UhuK
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:02Z'
  mac: ENC[AES256_GCM,data:L3SQ+H0jJC/ZLuuge9NSD/7Cs9lnjS2u6CL6a4iTKs2vuTGa7ospHJvr1hvVTWlOc2ingZBwsKyd1IAhc2f6ePfda7pt5RMweEIsPigTKknECQSD5kk1qIJYZ9DcDz8K3EUGKI8KLLxNqfMAR2eQksjNiBY/qOOWbmd+29AsmUY=,iv:kTeAt/6CQr4LnyYIrQAYI3SqO3uRT9E/IYPOZUdQuUM=,tag:54EzgBnJFdY5AKuK87ukbA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
