prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:SlsIGUsU4ZGPSLyUikGh/x59xp/OEgEMGj/l1TDWJHmfmx8fp/+pxXzFqOpu06kR9U3dJJiOHgMCb6McDmy+8Q==,iv:ntilEMWRakvT2fzr3DpDglBoy71XtNtjnkEkItt/RLQ=,tag:N0aox6mq0UtJkOlrtvb8tg==,type:str]
    password: ENC[AES256_GCM,data:7k8AF95uaVkp7hXj6pcm7nopsielW8lJfJxtyf6bDNIAcbd6rNbMd7vDzlqqj0gwiqDM5CC3QOBNBazj6A+VZw==,iv:K62U05dTAq6gtnQub2rPhC/NWf6Y9mRUK0x6LF4lf9c=,tag:gePnlcee7qR7Vk+DLY5ihg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:FQAQ0Uh8SbPQjDtYqPttf7x8iO0=,iv:OFrhPEwfmrqhMCeSw9qz1v6m80aM4M69Z0PXsRjE36U=,tag:MllJuGdpDDVW6PmrKe6slg==,type:str]
      client_secret: ENC[AES256_GCM,data:fqZ+6p2YH+ldtU/sG+fHSYgCNDz1K4UFAG1YXi2YeiReQ0UKEbb5Dw==,iv:PnzFAj+1am7+gElIrahNzSbDaBzyuX6xUZUkOhkLTHU=,tag:pb9Up7c7g8Qk7L7BvZWGJg==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:10Z'
    enc: CiUA4OM7eGpiYSPbHdHYHMc2WBIGfbnGBdtnFBhbPGP73ncHIevXEkkAZoeZpgEtTIhEyydiHUNgPfnuQ0cznBG639oRDtzTHXVhT0P5i+UZxJHNW7dKn30NIzZjWeAzpih8M1ZEOzu3OxAtaYrGUN0r
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:11Z'
  mac: ENC[AES256_GCM,data:g5nUqykbYlSB7o3aSlJS2HxWwx+SwVE6hKUSTPF5zeNHLBQ20cxdCOi/nUkhu6OLmYWJWpIbM5nD/RCskdN9MR1X7Ae9PNRpr3ngtoBxyy0+cqbpE7QGfSkEqdES/UyIIM4dVEwHWtBaDLo708E/cHUEatoW+3S1HIADJvgwEh4=,iv:atE53BAwmdz2YLE3D2PNOVXoec7dTK8JmLY0a2elYWE=,tag:kFrJocC3MKX7CNbvL8MLMQ==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
