prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:GsIL1kozRcF5vq6HkMNHzPmsmpkcID7CeHXUZ0ylbQVmm2xyCyUt5rk8eO6I9+aggCSRqYv70/BA79mHGtbMV8EPGPVX1o/uAIe/4HvTKdprnkvghVorsCZzA2b6PVbat2C1Q+WPX6qluROpAx9nF6n+T8XUYBxSUk9hRt/33JSrpbHtD8rDBl0JDOHEL8V2M5HFitjHxtpDX1l5,iv:GDLLc/NiXqFP0sz38Bu3namGh+RG+zTZUKBZ60o7sjw=,tag:AH7cMHvGFJPLmQrJh/UmRw==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:Mdrvwlp+xkuHDSgHdcI+QTWap0rs7dBWo17dK2S0DYRSjX4e3j0z1i3ydXA7pCGKxcUX7D4AC8NhwyRgDeRIDg==,iv:It6JYudbtEV1/vwGrPPWvYfqn4sakoHa/nShiP1IDag=,tag:W7prvPU5DZj8F/Jv3CqjkQ==,type:str]
    password: ENC[AES256_GCM,data:htLVHsxrygd2z0hkqnJ+MvmndJJp7XtW/T7YQOd7+7WUvBcurtLmF51NUvwzWSQsZxCqPziUCFs3q0tAIukPcA==,iv:jd1jKuyS0M+eRlRpzepBi5oSKn2TdT1MEOMp5kxRGRM=,tag:ZLLRGX0xDW5qXcDVdBNOSg==,type:str]
grafana:
  grafana.ini:
    auth.github:
      client_id: ENC[AES256_GCM,data:N5Py7bw2O0bPtBGN2zIrIf5Z9Wo=,iv:0sjJaB0HNb1xbo4gWeFDfa9dPcv6UTuHlnKlpmj6o1o=,tag:whLmj0tsfL6/otwg5XRILA==,type:str]
      client_secret: ENC[AES256_GCM,data:dWLEWauN/W40ckgdlndsGwR6rEK/zfgrW7+mi9j7FDbWdRUvEVK7DA==,iv:c2EnS50MEwZ2Yyc78IIN8SJeQp6VvD3hHs5HZZykTSE=,tag:kaz2Ds2WYDU8oZJUyAPnOQ==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:16Z'
    enc: CiUA4OM7eAtyX+OGmyJ4Y3k1MzCYJOPPo/lGarytG/j3DE7OtI/BEkkAZoeZpqz0eaf4OeCO1NRalheh3RGnq1Fu+HClSzdprb9NR1y3ZzjAJw/2ewMrbFq9bw0QyIjiv/tNZeu1VpGGsCarVeEuhQ8l
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:16Z'
  mac: ENC[AES256_GCM,data:vpFMrrcXmYr2jnyoTwg+5GzZpK4J/LZh83SOVqDL7DAjVy/aBFnV4dRR0WwfV0XSdIv4n/8LvWib/UIelt3yOl6CTqiMU3F9NOV1+oYqD1W29CgQgHCih/L/KtwKqRvdfBQuB0BXOT4hrPoBquBmXQiXDV8G7uZtVcxDa96bhnk=,iv:LH2Z+MP/kiox4MqHVhcFEksShNQTJTGkAGDdmfWMRQg=,tag:hMgq1mxgMP41tETQtgHolw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
