name: Auto-merge user placeholders change
on:
  workflow_run:
    workflows:
    - Deploy and test hubs
    types:
    - completed

jobs:
  debug:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      ( !github.event.workflow_run.head_repository.fork ) &&
      startsWith(github.event.workflow_run.head_branch, "placeholders/")
    steps:
    - name: Merge placeholders PR
      run: |
        gh pr merge --squash ${{ github.event.workflow_run.head_branch }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
