name: Auto-merge user placeholders change
on:
  workflow_run:
    workflows:
    - Validate clusters
    types:
    - completed

jobs:
  merge-placeholder-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    # Once we know that hubs are valid
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      ( !github.event.workflow_run.head_repository.fork ) &&
      startsWith(github.event.workflow_run.head_branch, 'placeholders/')
    steps:
    - uses: actions/checkout@v6
    - name: Generate a token
      id: generate-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ vars.PLACEHOLDERS_APP_ID }}
        private-key: ${{ secrets.PLACEHOLDERS_APP_PRIVATE_KEY }}
    - name: Merge placeholders PR
      run: |
        gh pr merge --squash ${{ github.event.workflow_run.head_branch }}
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
