name: Lint terraform

on:
  pull_request:
    paths:
      - terraform/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: terraform-linters/setup-tflint@v2
      - name: Run terraform linter
        run: tflint terraform
      - name: Check terraform formatting
        run: terraform fmt -check -diff terraform/
