name: Run tests on the deployer code

on:
  push:
    branches:
    - main
    paths:
    - deployer/**
    - tests/**
    - requirements.txt
    - dev-requirements.txt
    - pyproject.toml
    tags:
    - '**'
  pull_request:
    branches:
    - main
    paths:
    - deployer/**
    - tests/**
    - requirements.txt
    - dev-requirements.txt
    - pyproject.toml
  workflow_dispatch:

jobs:
  test-deployer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install --editable .
    - name: Run tests
      run: |
        python -m pytest -vvv --color=yes
