name: PagerDuty Extension Action
on:
  repository_dispatch:
    types: [pagerduty-action]
jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
    - env:
        MESSAGE: ${{ github.event.client_payload.title }}
      run: echo $MESSAGE
