name: ucmerced
provider: aws
provider_url: https://2i2c.awsapps.com/start#/
aws:
  account: 596308305316
  key: enc-deployer-credentials.secret.json
  clusterType: eks
  clusterName: ucmerced
  region: us-west-1
  billing:
    paid_by_us: true
support:
  helm_chart_values_files:
  - support.values.yaml
  - enc-support.secret.values.yaml
hubs: []
  # Uncomment the lines below once the support infrastructure was deployed and
  # you are ready to add the first cluster


  # - name: staging
  #   # Tip: consider changing this to something more human friendly
  #   display_name: "ucmerced - staging"
  #   domain: staging.ucmerced.2i2c.cloud
  #   helm_chart: basehub
  #   helm_chart_values_files:
  #     - common.values.yaml
  #     - staging.values.yaml
  #     - enc-staging.secret.values.yaml

  # - name: prod
  #   # Tip: consider changing this to something more human friendly
  #   display_name: "ucmerced - prod"
  #   domain: prod.ucmerced.2i2c.cloud
  #   helm_chart: basehub
  #   helm_chart_values_files:
  #     - common.values.yaml
  #     - prod.values.yaml
  #     - enc-prod.secret.values.yaml
