prometheusIngressAuthSecret:
  #ENC[AES256_GCM,data:zcl6F0RUTuVEE7+qmhYf/7gh3l8k+1+trsSHqKkb4LAejp9MpeJFfg0g/3LBbtPqLW1Iar+/zOVqviAEnrOkZyvsk2lNxQKrvNuec1vVOdArbZsdMgRJKp+mT6T5RbhdkVt4iVmQslk+z7gqyAOxibKuu3+1iScxhfFxln2f4ZwRufx6IpjTSjba9VrCy8GJsCKnn6EK6GVHc94S,iv:puHXZwr6SLL/7QC1VkVLZYLKVd/5V1zCXHwbKGMN2rM=,tag:ZrQMktVMxuczsR1pg/1e5w==,type:comment]
  users:
  - username: ENC[AES256_GCM,data:GziHGId0CsYOhQS7ty7JMJ8eGoTBm7mjo96ZOI9xMfDZlD4Cx47j7aNdpYLN4Tu5WdVRH3zELDTaS1MuoIc+Dg==,iv:lh5FFByhBWnXIfXNeE0f0n4QnWmqXfzcsumOqV8rP+E=,tag:6eTCpx/j5h8b4nSJcRGOSQ==,type:str]
    password: ENC[AES256_GCM,data:4GYgBmTabswrExlx1SGSYOWnJQP+qQG4oxA4LyvbqrQe0wR4XOIuVMmfopp9niochvTHUA+P+ntFKJXNAyrI3g==,iv:/l3qDl4pVJj1cglXY9Ib87kjO+SID1kchTwPIWX6fMQ=,tag:gc+wl/yB24hlYFlFrCFA6w==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-12T10:07:13Z'
    enc: CiUA4OM7eKPVxs2PIwo4gk8GMWh3DjQXT8l5kdVvMtCT119CePoSEkkAZoeZpk+87tV9MFS6nX+ndg0W/ir1mDGplSzfzkdA5a3pxXnP3tixXObLRwcVfvqVMF8goJwqlzplrHViYubyfPf4xl2ouB2Y
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-12T10:07:14Z'
  mac: ENC[AES256_GCM,data:n3YFNbhFbvaZi0Pzw4UuB9cQ+5v/p2C3en7G3HJ3f8NVHM8CtFh5B+6K7WaQrzpi8vy3OdzllvzxT2HhICDnt1VIUJykGEApR53zv20EYPmli1nKz9+dfhX3o7C+v3YGiYI/xgtrMz+8RU9sIYzD+MpcVay+gLXVZ4buVtxW62o=,iv:Vvn0atVnZBBuTCWGwhLe1DTqBpSwZDD6N0KsGzKgVBU=,tag:qRcHV3PYhQwymmxqrqI9Sg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
