prometheusIngressAuthSecret:
  users:
  - username: ENC[AES256_GCM,data:FW5UXGtbFtWcqiM23oNsa1k9V07QgAD0lOdPDsCqk4qVAKW2/T8mohGrW05/GZuW8LdNjz/mg0kjjb7/Y7pl+g==,iv:+eJqjfVIw8j02WL+vHZBsUhwOw2fyto0P7QJ0fyRd7M=,tag:g65seclm9aGc8aj/jRzZyA==,type:str]
    password: ENC[AES256_GCM,data:MUZSK+aRni41M7AAuN5GQLh4kfH66zbNGgwXK+Cf1zwwYDl43QS+hr7zVc14hZZu9rYJYtA+ix9YpuLXrK1e9g==,iv:tOQRLkRM5F66uHi45KK3jX5mYnsKqq+wEN+6q37Yt6s=,tag:PybxkVU9E1vgge1p32O7vA==,type:str]
sops:
  kms: []
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-10T11:41:07Z'
    enc: CiUA4OM7eMZ6qojPJH0Ro2TF0DOeCRD/uXTWWBpDOSA/sY+gB+/1EkgAZoeZpp5xiJc1qY3ElHDhux1dmTUbei3I4oYTUQic2us/rneBmpYk7StfKrVcklplCHJW4L27d098MQ1y93gJXv9NUHTvb5c=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: '2026-01-10T11:41:08Z'
  mac: ENC[AES256_GCM,data:d0x9t82swip5GrPdICw3gFr+o8aIh+y6TlEmyNxsKXbHkdnCCFSNT2nuhNAYKM+qnVA7WfxHJKRiFHUveB7I8gCZizDNuyjNuQp9H7o7oDRW9J5v5ngFfR8wd7w8ckNe7lNSLuB3Wu3/TxyJOFuruBq00+j4iPwGUi8FtljYOGk=,iv:FG6K+cws2hYnp5z1jFBAED16mTu+ZndRne5AwuGZSOQ=,tag:h45cyVueO1fNWgW4cijucw==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.1
