grafana_token: ENC[AES256_GCM,data:oDLTI8Qf7dvELugu/g2ft8SgSJ9kfK6zCDOxFPBXzJK2n/SazSUQp0mqy0BxMg==,iv:McECe77q9EEqgvnR/I2YI4b5YCksVhLGy++UUnRCoM4=,tag:56uVv+1BzcwT4eSTjVaqKQ==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-13T10:59:34Z'
    enc: CiUA4OM7eNpzxXZ914fvd+1qwnaGzIFepiIlWoMMEgo5WW3iJMWUEkkAZoeZpqJbxiSMZobB33KjqOGgrQrjbZwDghh5HLOJLYWC5IgvOnYZ4ykLm09YrhoE8IF2I8SITAOA53IPwFWiuFdm2h0RdqVN
  lastmodified: '2026-01-13T10:59:35Z'
  mac: ENC[AES256_GCM,data:aUL3x6GBT6F2HszF/lGpz0wifwwAZ4ZZMZPrGlpOzXvTC02tFGf60vhUfb53+X6hUOpetYpVNeZlBEe48KDoru6hgR5Z6adv2KAMEN8sFIycnLacsygE+Anb4hjDy0clBHz5Scxbfem3J7AXOWt9a+RlGv/hoUYJ55tThb+0M0w=,iv:d1h5sw4Jmak8Cr7fObgb0Ghi4FfXrz+rle66CDZ0BZ8=,tag:RVuG/cmrTW/UFT0jYoeO0w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
