prometheusIngressAuthSecret:
  username: ENC[AES256_GCM,data:VvrgmbYzQXQ/rlZk69osZq2cpnyLyY2C2fxsnaDen9QusZLhvmPbQ8CC4vm8qdEw2LB1PT2QroFJGU2PUlPsrw==,iv:MIVp4S+kaeP14KWSFBUanADwrPP+F7ZSHcO7a9gvTkQ=,tag:NBClmOndx1WXwgJR2MWO7w==,type:str]
  password: ENC[AES256_GCM,data:jIVo9NOL5reUexWZusJFCfwo1nkQwJYQqTgWOFyGPtJYMXQC7cRklMG64nNrw8aJgpwwWBo9PfS6e1gmgoQF8w==,iv:+Dowz/xamxLJdkBGkxZB4i5DK1e3H9zLyjGtBKojLEY=,tag:zbmJOsjl7uApc7qI+lMKRw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-07T11:54:13Z'
    enc: CiUA4OM7eMzZtBuQdHYQynYSfR+wDgsxYOxYm+O3hrEuLXn92NiUEkkAZoeZpqG2yIhB33uoiGMEOnf237IRU/YeBh92d9OIinpcIGdNk6JRr1gV2sDDlG5mBTzF+CWgjUBAdVOGaEMlU3TKOjzHrnRK
  lastmodified: '2026-01-07T11:54:13Z'
  mac: ENC[AES256_GCM,data:3nQWmsDKtOwSIjS/hcAN1Cr3nOjmHJNoiIUWxUwONQnTGpxOgsWheQIbNtG9cIqpLcO/a1qBxBB9Ji80xQhmTdjUfbqMuTZiygbccn5DDpNAmC49ABq96xmj2t4IQKk1aY6Idu3sk/jlUNJSFL0sPumEgANfgA6QWTSgwPdyTsc=,iv:KqAI5U9qgF5V3XqTabRH6NOTZDbJhthqwLOobvmKTN8=,tag:4j6qGgM/Ip9Cg+i/OFNq6Q==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
