jupyterhub:
  hub:
    config:
      CILogonOAuthenticator:
        client_id: ENC[AES256_GCM,data:ENfjgmOR9LeI/WfpbFl99SocmzRpwojI5DPuHsZqJV1+T2CifZ3mSGqjzXUpkbQQ1dfC,iv:VjlWvXmRQhMY7GSZ2NgtQD1RQMeGYdDJFaCO3Oz4JCM=,tag:4z/sj4Ij7u0PtgnlhhNzvw==,type:str]
        client_secret: ENC[AES256_GCM,data:nKya5L9d/Xez/r4sBa+dN7mw2jyBujP8V5UWHVWYDbaRddGuOwU2vmcRjGE7/RJE2VwEkvaxPz/kjQy05aRoBZX+CjIa+4i57aMoP+4QA5D8mpSMwQM=,iv:pDaISsGE/sbo/z1zK5VA5EC88E7snp6NWFXpPwzUGyE=,tag:jvONXNlsoE9nGoopZbF2sg==,type:str]
jupyterhub-home-nfs:
  quotaEnforcer:
    extraConfig:
      secret-quota-overrides: ENC[AES256_GCM,data:vuDjHE3t8LuJoqYcQVVspXvJ8/05S43b8K7PNj9UUCqk+MrqTFmXcHVi33V69To2CAPqdfmTiOD7ByT3YSnARy0ia/C8lt6MugqKT9ST3dmvxU8v1pAGI83w2YQ=,iv:S5zdcoO7apUnW+7GGMu1D0sIlqy6XBS/IOCEZupNadU=,tag:mkeqDHyhkr/ug7MxJxzPkw==,type:str]
sops:
  gcp_kms:
  - resource_id: projects/two-eye-two-see/locations/global/keyRings/sops-keys/cryptoKeys/similar-hubs
    created_at: '2026-01-08T18:41:33Z'
    enc: CiUA4OM7eHG7Zfa/LngNOZ6ClwVy9u28F0bJgJcjdOwHXG57fD2PEkkAZoeZptq/iUOUBzVCrtn7lK3NnZRHObb1WaKQdYtllQ6G/b8m/R6xFHXotUTDW63lIg2qkRhmMXqgfOLoh62g6jlEA7Ah3/RC
  lastmodified: '2026-01-08T18:41:33Z'
  mac: ENC[AES256_GCM,data:+JtYm08kcGP/9bg5lPajFG5KwJZEpRCCg0cZqPp4IjDmWFkgVj7QWZ1sjHmXlCd14/ipPKPU4aeJ//6XZFfjOITKAG+GTPJqVuyBPA92G81pUQnBaUURFluMlM9alcs1OAK4+eAMCxrGXImfbGPUQV00ikbobfhREPXjKsw5C90=,iv:8NiYHQPFGYuuERZSc51h4x0IphOUXJV1P6NsZgDg7+w=,tag:acE0GekP3859dcjHA4hZKA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
