prometheusIngressAuthSecret:
  enabled: true



prometheus:
  server:
    persistentVolume:
      size: 100Gi
    ingress:
      enabled: true
      hosts:
      - prometheus.ucmerced.2i2c.cloud
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.ucmerced.2i2c.cloud

grafana:
  grafana.ini:
    server:
      root_url: https://grafana.ucmerced.2i2c.cloud/
  auth.github:
    enabled: true
    allowed_organizations: 2i2c-org
  persistence:
    # We don't need 10Gi on the Grafana persistent directory
    size: 1Gi
  ingress:
    hosts:
    - grafana.ucmerced.2i2c.cloud
    tls:
    - secretName: grafana-tls
      hosts:
      - grafana.ucmerced.2i2c.cloud


cluster-autoscaler:
  enabled: true
  autoDiscovery:
    clusterName: ucmerced
  awsRegion: us-west-2

calico:
  enabled: true


# FIXME: remove this once eksctl is fixed
nvidiaDevicePlugin:
  aws:
    enabled: true
