channels:
  - conda-forge
dependencies:
  # for jupyter-desktop-server
  - websockify

  # language runtimes
  - python=3.8.*

  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - sympy
  - networkx
  - scikit-learn
  - beautifulsoup4
  - statsmodels
  - nltk
  - spacy
  - geopandas
  # From https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/29
  - astroquery
  - astropy
  - galpy

  - pip

  - pip:
    # Infrastructure things
    - jupyterlab==2.*
    - voila==0.1.23
    - nbgitpuller==0.9.*
    - nbresuse==0.3.6
    - nbinteract==0.2.5
    - jupytext==1.6.*
    - RISE==5.6.1
    - jupyter_contrib_nbextensions==0.5.1
    - jupyter-desktop-server==0.1.3
    - notebook==6.1.4
    - jupyterhub==1.1.0
    - jupyter-server-proxy==1.5.0
    - jupyter-rsession-proxy==1.2
    - jupyter-tree-download==1.0.1
    - ipywidgets==7.5.1

    - datascience
    - geojson
    - folium
    - geopy
