name: grss-veda
provider: aws
provider_url: https://870461445243.signin.aws.amazon.com/console
aws:
  account: 870461445243
  key: enc-deployer-credentials.secret.json
  clusterType: eks
  clusterName: grss-veda
  region: us-west-2
  billing:
    paid_by_us: false
support:
  helm_chart_values_files:
    - support.values.yaml
    - enc-support.secret.values.yaml
hubs: []
  # Uncomment the lines below once the support infrastructure was deployed and
  # you are ready to add the first cluster


  # - name: staging
  #   # Tip: consider changing this to something more human friendly
  #   display_name: "grss-veda - staging"
  #   domain: staging.grss-veda.2i2c.cloud
  #   helm_chart: basehub
  #   helm_chart_values_files:
  #     - common.values.yaml
  #     - staging.values.yaml
  #     - enc-staging.secret.values.yaml

  # - name: prod
  #   # Tip: consider changing this to something more human friendly
  #   display_name: "grss-veda - prod"
  #   domain: prod.grss-veda.2i2c.cloud
  #   helm_chart: basehub
  #   helm_chart_values_files:
  #     - common.values.yaml
  #     - prod.values.yaml
  #     - enc-prod.secret.values.yaml
